#ifndef GENERATED_ASN1SCC_Context_pusservices_H
#define GENERATED_ASN1SCC_Context_pusservices_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_pusservices --------------------------------------------*/

typedef struct {
    asn1SccPusUInt11 apid;

} asn1SccContext_pusservices;

void asn1SccContext_pusservices_Initialize(asn1SccContext_pusservices* pVal);

#define ERR_CONTEXT_PUSSERVICES_APID		1  /**/
flag asn1SccContext_pusservices_IsConstraintValid(const asn1SccContext_pusservices* pVal, int* pErrCode);

extern const asn1SccContext_pusservices pusservices_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
