/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>


#include "Context-pusservices.h"

const asn1SccContext_pusservices pusservices_ctxt = {
    .apid = 1
};


void asn1SccContext_pusservices_Initialize(asn1SccContext_pusservices* pVal)
{
	(void)pVal;



	/*set apid */
	asn1SccPusUInt11_Initialize((&(pVal->apid)));
}

flag asn1SccContext_pusservices_IsConstraintValid(const asn1SccContext_pusservices* pVal, int* pErrCode)
{
    flag ret = TRUE;
	(void)pVal;
	
    ret = (pVal->apid <= 2047UL);
    *pErrCode = ret ? 0 :  ERR_CONTEXT_PUSSERVICES_APID; 

	return ret;
}

