/* Body file for function Function1
 * Generated by TASTE on 2020-06-16 16:00:50
 * You can edit this file, it will not be overwritten
 * Provided interfaces : hola
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 88257 34335 117598 52049
 * Timers              : 
 */
/* There are no required interfaces for this function... */

