/* Header file for function Function1 in C language
 * Generated by TASTE on 2020-06-16 16:00:50
 * Context Parameters present : NO
 * Provided interfaces : hola
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 88257 34335 117598 52049
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

/* The purpose of this file is to provide a wrapper around the user code,
 * with a single interface that is independent of the implementation language
 * of the function. The parameters of each PI are blackboxes encoded
 * in the form specified in the interface view (Native, uPER, or ACN)
*/

#pragma once
#if defined(__unix__) || defined (__MSP430__)
   #include <stdlib.h>
   #include <stdio.h>
#else
   typedef unsigned size_t;
#endif

#ifdef __cplusplus
extern "C" {
#endif

#include "function1.h"

// Function initialization - calls user startup code of all dependent functions
void init_function1(void);


/* Provided interfaces */
void function1_hola(void);


#ifdef __cplusplus
}
#endif

