/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-groundapid.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccContext_groundapid_Initialize(asn1SccContext_groundapid* pVal)
{
    *pVal = (asn1SccContext_groundapid) {
    .apid = 0
};
}
#endif

 
flag asn1SccContext_groundapid_IsConstraintValid(const asn1SccContext_groundapid* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusApid_IsConstraintValid(&pVal->apid, pErrCode);


	return ret;
}

const asn1SccContext_groundapid groundapid_ctxt = {
    .apid = 1
};
