#ifndef GENERATED_ASN1SCC_CONTEXT_GROUNDAPID_H
#define GENERATED_ASN1SCC_CONTEXT_GROUNDAPID_H
/*
Code automatically generated by asn1scc tool
*/
#include "dataview-uniq.h"
#include "asn1crt.h"

#ifdef  __cplusplus
extern "C" {
#endif



typedef struct {
    asn1SccPusApid apid;
} asn1SccContext_groundapid;

#define asn1SccContext_groundapid_REQUIRED_BYTES_FOR_ENCODING       2 
#define asn1SccContext_groundapid_REQUIRED_BITS_FOR_ENCODING        11
#define asn1SccContext_groundapid_REQUIRED_BYTES_FOR_ACN_ENCODING   2 
#define asn1SccContext_groundapid_REQUIRED_BITS_FOR_ACN_ENCODING    11
#define asn1SccContext_groundapid_REQUIRED_BYTES_FOR_XER_ENCODING   74

void asn1SccContext_groundapid_Initialize(asn1SccContext_groundapid* pVal);
flag asn1SccContext_groundapid_IsConstraintValid(const asn1SccContext_groundapid* val, int* pErrCode);


extern const asn1SccContext_groundapid groundapid_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
