/* Body file for function OnBoardSW
 * Generated by TASTE on 2020-05-21 12:14:37
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger
 * Required interfaces : getOnBoardParam, getParamValue, pushNewEvent, setOnBoardParam, setParamValue
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 199364 64408 238261 91808
 * Timers              : 
 */

#include "onboardsw.h"
//#include <stdio.h>


void onboardsw_startup(void)
{
   // Write your initialisation code, but DO NOT CALL REQUIRED INTERFACES
   // puts ("[OnBoardSW] Startup");
}

void onboardsw_PI_trigger(void)
{
   // Write your code here
}


