/*
 * H2020 ESROCOS Project
 * Company: GMV Aerospace & Defence S.A.U.
 * Licence: GPLv2
 */ 
 
#ifndef PUS_ENABLED_SERVICES
#define PUS_ENABLED_SERVICES

//Comment the service/tables that user don't want to enable.

#define PUS_CONFIGURE_ST01_ENABLED
#define PUS_CONFIGURE_ST03_ENABLED
#define PUS_CONFIGURE_ST05_ENABLED
#define PUS_CONFIGURE_ST08_ENABLED
#define PUS_CONFIGURE_ST09_ENABLED
#define PUS_CONFIGURE_ST11_ENABLED
#define PUS_CONFIGURE_ST12_ENABLED
#define PUS_CONFIGURE_ST17_ENABLED
#define PUS_CONFIGURE_ST18_ENABLED
#define PUS_CONFIGURE_ST19_ENABLED
#define PUS_CONFIGURE_ST20_ENABLED
#define PUS_CONFIGURE_ST23_ENABLED


#define PUS_CONFIGURE_HK_PARAMS_TABLE
#define PUS_CONFIGURE_ONBOARD_PARAMS_TABLE
#define PUS_CONFIGURE_EVENTS_TABLE
#define PUS_CONFIGURE_OBCP_ENGINE


// TODO delete, it is just to avoid eclipse colors
/*#define PUS_CONFIGURE_ST200_ENABLED
#define PUS_CONFIGURE_ST201_ENABLED*/




#endif
