/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "dataview-uniq.h"

#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccT_Int32_Initialize(asn1SccT_Int32* pVal)
{
    *pVal = (asn1SccT_Int32) -2147483648LL;
}
#endif

 
flag asn1SccT_Int32_IsConstraintValid(const asn1SccT_Int32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-2147483648LL <= *pVal && *pVal <= 2147483647LL);
	*pErrCode = ret ? 0 : ERR_asn1SccT_Int32;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccT_UInt32_Initialize(asn1SccT_UInt32* pVal)
{
    *pVal = (asn1SccT_UInt32) 0;
}
#endif

 
flag asn1SccT_UInt32_IsConstraintValid(const asn1SccT_UInt32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_asn1SccT_UInt32;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccT_Int8_Initialize(asn1SccT_Int8* pVal)
{
    *pVal = (asn1SccT_Int8) -128;
}
#endif

 
flag asn1SccT_Int8_IsConstraintValid(const asn1SccT_Int8* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-128 <= *pVal && *pVal <= 127);
	*pErrCode = ret ? 0 : ERR_asn1SccT_Int8;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccT_UInt8_Initialize(asn1SccT_UInt8* pVal)
{
    *pVal = (asn1SccT_UInt8) 0;
}
#endif

 
flag asn1SccT_UInt8_IsConstraintValid(const asn1SccT_UInt8* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 255);
	*pErrCode = ret ? 0 : ERR_asn1SccT_UInt8;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccT_Boolean_Initialize(asn1SccT_Boolean* pVal)
{
    *pVal = (asn1SccT_Boolean) FALSE;
}
#endif

 
flag asn1SccT_Boolean_IsConstraintValid(const asn1SccT_Boolean* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt3_Initialize(asn1SccPusUInt3* pVal)
{
    *pVal = (asn1SccPusUInt3) 0;
}
#endif

 
flag asn1SccPusUInt3_IsConstraintValid(const asn1SccPusUInt3* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 7);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt3;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt4_Initialize(asn1SccPusUInt4* pVal)
{
    *pVal = (asn1SccPusUInt4) 0;
}
#endif

 
flag asn1SccPusUInt4_IsConstraintValid(const asn1SccPusUInt4* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 5);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt4;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTimeReferenceStatus_Initialize(asn1SccPusTimeReferenceStatus* pVal)
{
    *pVal = (asn1SccPusTimeReferenceStatus) 0;
}
#endif

 
flag asn1SccPusTimeReferenceStatus_IsConstraintValid(const asn1SccPusTimeReferenceStatus* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt4_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt8_Initialize(asn1SccPusUInt8* pVal)
{
    *pVal = (asn1SccPusUInt8) 0;
}
#endif

 
flag asn1SccPusUInt8_IsConstraintValid(const asn1SccPusUInt8* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 255);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt8;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusServiceType_Initialize(asn1SccPusServiceType* pVal)
{
    *pVal = (asn1SccPusServiceType) 0;
}
#endif

 
flag asn1SccPusServiceType_IsConstraintValid(const asn1SccPusServiceType* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt8_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSubserviceType_Initialize(asn1SccPusSubserviceType* pVal)
{
    *pVal = (asn1SccPusSubserviceType) 0;
}
#endif

 
flag asn1SccPusSubserviceType_IsConstraintValid(const asn1SccPusSubserviceType* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt8_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt11_Initialize(asn1SccPusUInt11* pVal)
{
    *pVal = (asn1SccPusUInt11) 0;
}
#endif

 
flag asn1SccPusUInt11_IsConstraintValid(const asn1SccPusUInt11* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 2047);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt11;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusApid_Initialize(asn1SccPusApid* pVal)
{
    *pVal = (asn1SccPusApid) 0;
}
#endif

 
flag asn1SccPusApid_IsConstraintValid(const asn1SccPusApid* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt11_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt14_Initialize(asn1SccPusUInt14* pVal)
{
    *pVal = (asn1SccPusUInt14) 0;
}
#endif

 
flag asn1SccPusUInt14_IsConstraintValid(const asn1SccPusUInt14* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 16383);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt14;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSequenceCount_Initialize(asn1SccPusSequenceCount* pVal)
{
    *pVal = (asn1SccPusSequenceCount) 0;
}
#endif

 
flag asn1SccPusSequenceCount_IsConstraintValid(const asn1SccPusSequenceCount* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt14_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt16_Initialize(asn1SccPusUInt16* pVal)
{
    *pVal = (asn1SccPusUInt16) 0;
}
#endif

 
flag asn1SccPusUInt16_IsConstraintValid(const asn1SccPusUInt16* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 65535);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt16;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketDataLength_Initialize(asn1SccPusPacketDataLength* pVal)
{
    *pVal = (asn1SccPusPacketDataLength) 0;
}
#endif

 
flag asn1SccPusPacketDataLength_IsConstraintValid(const asn1SccPusPacketDataLength* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt16_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusMessageTypeCounter_Initialize(asn1SccPusMessageTypeCounter* pVal)
{
    *pVal = (asn1SccPusMessageTypeCounter) 0;
}
#endif

 
flag asn1SccPusMessageTypeCounter_IsConstraintValid(const asn1SccPusMessageTypeCounter* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt16_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusChecksum_Initialize(asn1SccPusChecksum* pVal)
{
    *pVal = (asn1SccPusChecksum) 0;
}
#endif

 
flag asn1SccPusChecksum_IsConstraintValid(const asn1SccPusChecksum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt16_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt18ObcpChecksum_Initialize(asn1SccPusSt18ObcpChecksum* pVal)
{
    *pVal = (asn1SccPusSt18ObcpChecksum) 0;
}
#endif

 
flag asn1SccPusSt18ObcpChecksum_IsConstraintValid(const asn1SccPusSt18ObcpChecksum* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt16_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt32_Initialize(asn1SccPusUInt32* pVal)
{
    *pVal = (asn1SccPusUInt32) 0;
}
#endif

 
flag asn1SccPusUInt32_IsConstraintValid(const asn1SccPusUInt32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 4294967295LL);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt32;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt12pmonId_Initialize(asn1SccPusSt12pmonId* pVal)
{
    *pVal = (asn1SccPusSt12pmonId) 0;
}
#endif

 
flag asn1SccPusSt12pmonId_IsConstraintValid(const asn1SccPusSt12pmonId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_12_1_2_Data_Initialize(asn1SccPusTC_12_1_2_Data* pVal)
{
    *pVal = (asn1SccPusTC_12_1_2_Data) {
    .pmonId = 0
};
}
#endif

 
flag asn1SccPusTC_12_1_2_Data_IsConstraintValid(const asn1SccPusTC_12_1_2_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt12pmonId_IsConstraintValid(&pVal->pmonId, pErrCode);


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusStepId_Initialize(asn1SccPusStepId* pVal)
{
    *pVal = (asn1SccPusStepId) 0;
}
#endif

 
flag asn1SccPusStepId_IsConstraintValid(const asn1SccPusStepId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt09ExponentialRate_Initialize(asn1SccPusSt09ExponentialRate* pVal)
{
    *pVal = (asn1SccPusSt09ExponentialRate) 0;
}
#endif

 
flag asn1SccPusSt09ExponentialRate_IsConstraintValid(const asn1SccPusSt09ExponentialRate* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_9_1_Data_Initialize(asn1SccPusTC_9_1_Data* pVal)
{
    *pVal = (asn1SccPusTC_9_1_Data) {
    .exponentialRate = 0
};
}
#endif

 
flag asn1SccPusTC_9_1_Data_IsConstraintValid(const asn1SccPusTC_9_1_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt09ExponentialRate_IsConstraintValid(&pVal->exponentialRate, pErrCode);


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt20OnBoardParameterId_Initialize(asn1SccPusSt20OnBoardParameterId* pVal)
{
    *pVal = (asn1SccPusSt20OnBoardParameterId) 0;
}
#endif

 
flag asn1SccPusSt20OnBoardParameterId_IsConstraintValid(const asn1SccPusSt20OnBoardParameterId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt05EventId_Initialize(asn1SccPusSt05EventId* pVal)
{
    *pVal = (asn1SccPusSt05EventId) 0;
}
#endif

 
flag asn1SccPusSt05EventId_IsConstraintValid(const asn1SccPusSt05EventId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_19_X_Data_Initialize(asn1SccPusTC_19_X_Data* pVal)
{
    *pVal = (asn1SccPusTC_19_X_Data) {
    .eventId = 0
};
}
#endif

 
flag asn1SccPusTC_19_X_Data_IsConstraintValid(const asn1SccPusTC_19_X_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt05EventId_IsConstraintValid(&pVal->eventId, pErrCode);


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusConfigDummyType_Initialize(asn1SccPusConfigDummyType* pVal)
{
    *pVal = (asn1SccPusConfigDummyType) 0;
}
#endif

 
flag asn1SccPusConfigDummyType_IsConstraintValid(const asn1SccPusConfigDummyType* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt01FailureCode_Initialize(asn1SccPusSt01FailureCode* pVal)
{
    *pVal = (asn1SccPusSt01FailureCode) 0;
}
#endif

 
flag asn1SccPusSt01FailureCode_IsConstraintValid(const asn1SccPusSt01FailureCode* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt08FunctionId_Initialize(asn1SccPusSt08FunctionId* pVal)
{
    *pVal = (asn1SccPusSt08FunctionId) 0;
}
#endif

 
flag asn1SccPusSt08FunctionId_IsConstraintValid(const asn1SccPusSt08FunctionId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_8_1_Data_Initialize(asn1SccPusTC_8_1_Data* pVal)
{
    *pVal = (asn1SccPusTC_8_1_Data) {
    .functionId = 0
};
}
#endif

 
flag asn1SccPusTC_8_1_Data_IsConstraintValid(const asn1SccPusTC_8_1_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt08FunctionId_IsConstraintValid(&pVal->functionId, pErrCode);


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt03HousekeepingReportId_Initialize(asn1SccPusSt03HousekeepingReportId* pVal)
{
    *pVal = (asn1SccPusSt03HousekeepingReportId) 0;
}
#endif

 
flag asn1SccPusSt03HousekeepingReportId_IsConstraintValid(const asn1SccPusSt03HousekeepingReportId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt03ParameterId_Initialize(asn1SccPusSt03ParameterId* pVal)
{
    *pVal = (asn1SccPusSt03ParameterId) 0;
}
#endif

 
flag asn1SccPusSt03ParameterId_IsConstraintValid(const asn1SccPusSt03ParameterId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt32_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusUInt64_Initialize(asn1SccPusUInt64* pVal)
{
    *pVal = (asn1SccPusUInt64) 0;
}
#endif

 
flag asn1SccPusUInt64_IsConstraintValid(const asn1SccPusUInt64* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal <= 9223372036854775807LL);
	*pErrCode = ret ? 0 : ERR_asn1SccPusUInt64;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusMemAddr_Initialize(asn1SccPusMemAddr* pVal)
{
    *pVal = (asn1SccPusMemAddr) 0;
}
#endif

 
flag asn1SccPusMemAddr_IsConstraintValid(const asn1SccPusMemAddr* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt64_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt20StoredParam_Initialize(asn1SccPusSt20StoredParam* pVal)
{
    *pVal = (asn1SccPusSt20StoredParam) 0;
}
#endif

 
flag asn1SccPusSt20StoredParam_IsConstraintValid(const asn1SccPusSt20StoredParam* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt64_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_TM_20_X_Data_Initialize(asn1SccPusTC_TM_20_X_Data* pVal)
{
    *pVal = (asn1SccPusTC_TM_20_X_Data) {
    .paramId = 0,
    .value = 0
};
}
#endif

 
flag asn1SccPusTC_TM_20_X_Data_IsConstraintValid(const asn1SccPusTC_TM_20_X_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt20OnBoardParameterId_IsConstraintValid(&pVal->paramId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt20StoredParam_IsConstraintValid(&pVal->value, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt05EventAuxData_Initialize(asn1SccPusSt05EventAuxData* pVal)
{
    *pVal = (asn1SccPusSt05EventAuxData) {
    .data1 = 0,
    .data2 = 0
};
}
#endif

 
flag asn1SccPusSt05EventAuxData_IsConstraintValid(const asn1SccPusSt05EventAuxData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt64_IsConstraintValid(&pVal->data1, pErrCode);
	if (ret) {
	    ret = asn1SccPusUInt64_IsConstraintValid(&pVal->data2, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt05Event_Initialize(asn1SccPusSt05Event* pVal)
{
    *pVal = (asn1SccPusSt05Event) {
    .eventId = 0,
    .data = {
        .data1 = 0,
        .data2 = 0
    }
};
}
#endif

 
flag asn1SccPusSt05Event_IsConstraintValid(const asn1SccPusSt05Event* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt05EventId_IsConstraintValid(&pVal->eventId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt05EventAuxData_IsConstraintValid(&pVal->data, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTM_5_X_Data_Initialize(asn1SccPusTM_5_X_Data* pVal)
{
    *pVal = (asn1SccPusTM_5_X_Data) {
    .eventId = 0,
    .data = {
        .data1 = 0,
        .data2 = 0
    }
};
}
#endif

 
flag asn1SccPusTM_5_X_Data_IsConstraintValid(const asn1SccPusTM_5_X_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt05Event_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt03StoredParam_Initialize(asn1SccPusSt03StoredParam* pVal)
{
    *pVal = (asn1SccPusSt03StoredParam) 0;
}
#endif

 
flag asn1SccPusSt03StoredParam_IsConstraintValid(const asn1SccPusSt03StoredParam* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusUInt64_IsConstraintValid(pVal, pErrCode);

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt03ParameterArray_Initialize(asn1SccPusSt03ParameterArray* pVal)
{
    *pVal = (asn1SccPusSt03ParameterArray) {    .nCount = 0,    .arr = 
    {
        
    }
};
}
#endif

 
flag asn1SccPusSt03ParameterArray_IsConstraintValid(const asn1SccPusSt03ParameterArray* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (0 <= pVal->nCount && pVal->nCount <= (int)pus_ST03_MAX_REPORT_LENGTH);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt03ParameterArray;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccPusSt03StoredParam_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTM_3_25_Data_Initialize(asn1SccPusTM_3_25_Data* pVal)
{
    *pVal = (asn1SccPusTM_3_25_Data) {
    .reportId = 0,
    .parameters = {    .nCount = 0,    .arr = 
        {
            
        }
    }
};
}
#endif

 
flag asn1SccPusTM_3_25_Data_IsConstraintValid(const asn1SccPusTM_3_25_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt03HousekeepingReportId_IsConstraintValid(&pVal->reportId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt03ParameterArray_IsConstraintValid(&pVal->parameters, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusInt32_Initialize(asn1SccPusInt32* pVal)
{
    *pVal = (asn1SccPusInt32) -2147483648LL;
}
#endif

 
flag asn1SccPusInt32_IsConstraintValid(const asn1SccPusInt32* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (-2147483648LL <= *pVal && *pVal <= 2147483647LL);
	*pErrCode = ret ? 0 : ERR_asn1SccPusInt32;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt01FailureInfo_Initialize(asn1SccPusSt01FailureInfo* pVal)
{
    *pVal = (asn1SccPusSt01FailureInfo) {
    .subcode = -2147483648LL,
    .data = -2147483648LL,
    .address = 0
};
}
#endif

 
flag asn1SccPusSt01FailureInfo_IsConstraintValid(const asn1SccPusSt01FailureInfo* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusInt32_IsConstraintValid(&pVal->subcode, pErrCode);
	if (ret) {
	    ret = asn1SccPusInt32_IsConstraintValid(&pVal->data, pErrCode);
	    if (ret) {
	        ret = asn1SccPusMemAddr_IsConstraintValid(&pVal->address, pErrCode);
	    
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt01Failure_Initialize(asn1SccPusSt01Failure* pVal)
{
    *pVal = (asn1SccPusSt01Failure) {
    .code = 0,
    .info = {
        .subcode = -2147483648LL,
        .data = -2147483648LL,
        .address = 0
    }
};
}
#endif

 
flag asn1SccPusSt01Failure_IsConstraintValid(const asn1SccPusSt01Failure* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt01FailureCode_IsConstraintValid(&pVal->code, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt01FailureInfo_IsConstraintValid(&pVal->info, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusInt64_Initialize(asn1SccPusInt64* pVal)
{
    *pVal = (asn1SccPusInt64) LLONG_MIN;
}
#endif

 
flag asn1SccPusInt64_IsConstraintValid(const asn1SccPusInt64* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (LLONG_MIN <= *pVal && *pVal <= 9223372036854775807LL);
	*pErrCode = ret ? 0 : ERR_asn1SccPusInt64;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTime_Initialize(asn1SccPusTime* pVal)
{
    *pVal = (asn1SccPusTime) {
    .tv_sec = LLONG_MIN,
    .tv_nsec = LLONG_MIN
};
}
#endif

 
flag asn1SccPusTime_IsConstraintValid(const asn1SccPusTime* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusInt64_IsConstraintValid(&pVal->tv_sec, pErrCode);
	if (ret) {
	    ret = asn1SccPusInt64_IsConstraintValid(&pVal->tv_nsec, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTM_9_2_Data_Initialize(asn1SccPusTM_9_2_Data* pVal)
{
    *pVal = (asn1SccPusTM_9_2_Data) {
    .exponentialRate = 0,
    .time = {
        .tv_sec = LLONG_MIN,
        .tv_nsec = LLONG_MIN
    }
};
}
#endif

 
flag asn1SccPusTM_9_2_Data_IsConstraintValid(const asn1SccPusTM_9_2_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt09ExponentialRate_IsConstraintValid(&pVal->exponentialRate, pErrCode);
	if (ret) {
	    ret = asn1SccPusTime_IsConstraintValid(&pVal->time, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt23RepositoryPath_Initialize(asn1SccPusSt23RepositoryPath* pVal)
{
    *pVal = (asn1SccPusSt23RepositoryPath) {1,
    {
        0x00
    }
};
}
#endif

 
flag asn1SccPusSt23RepositoryPath_IsConstraintValid(const asn1SccPusSt23RepositoryPath* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= (int)pus_ST23_MAX_SIZE_REPOSITORY_PATH);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt23RepositoryPath;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt23FileName_Initialize(asn1SccPusSt23FileName* pVal)
{
    *pVal = (asn1SccPusSt23FileName) {1,
    {
        0x00
    }
};
}
#endif

 
flag asn1SccPusSt23FileName_IsConstraintValid(const asn1SccPusSt23FileName* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= (int)pus_ST23_MAX_SIZE_FILE_PATH);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt23FileName;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_TM_23_1_4_Data_Initialize(asn1SccPusTC_TM_23_1_4_Data* pVal)
{
    *pVal = (asn1SccPusTC_TM_23_1_4_Data) {
    .repository = {1,
        {
            0x00
        }
    },
    .fileName = {1,
        {
            0x00
        }
    },
    .maxSize = 0
};
}
#endif

 
flag asn1SccPusTC_TM_23_1_4_Data_IsConstraintValid(const asn1SccPusTC_TM_23_1_4_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt23RepositoryPath_IsConstraintValid(&pVal->repository, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt23FileName_IsConstraintValid(&pVal->fileName, pErrCode);
	    if (ret) {
	        ret = asn1SccPusUInt64_IsConstraintValid(&pVal->maxSize, pErrCode);
	    
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_23_2_3_Data_Initialize(asn1SccPusTC_23_2_3_Data* pVal)
{
    *pVal = (asn1SccPusTC_23_2_3_Data) {
    .repository = {1,
        {
            0x00
        }
    },
    .fileName = {1,
        {
            0x00
        }
    }
};
}
#endif

 
flag asn1SccPusTC_23_2_3_Data_IsConstraintValid(const asn1SccPusTC_23_2_3_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt23RepositoryPath_IsConstraintValid(&pVal->repository, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt23FileName_IsConstraintValid(&pVal->fileName, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_23_14_Data_Initialize(asn1SccPusTC_23_14_Data* pVal)
{
    *pVal = (asn1SccPusTC_23_14_Data) {
    .sourceRepository = {1,
        {
            0x00
        }
    },
    .sourceFileName = {1,
        {
            0x00
        }
    },
    .targetRepository = {1,
        {
            0x00
        }
    },
    .targetFileName = {1,
        {
            0x00
        }
    }
};
}
#endif

 
flag asn1SccPusTC_23_14_Data_IsConstraintValid(const asn1SccPusTC_23_14_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt23RepositoryPath_IsConstraintValid(&pVal->sourceRepository, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt23FileName_IsConstraintValid(&pVal->sourceFileName, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSt23RepositoryPath_IsConstraintValid(&pVal->targetRepository, pErrCode);
	        if (ret) {
	            ret = asn1SccPusSt23FileName_IsConstraintValid(&pVal->targetFileName, pErrCode);
	        
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt23RepositoryDomain_Initialize(asn1SccPusSt23RepositoryDomain* pVal)
{
    *pVal = (asn1SccPusSt23RepositoryDomain) {1,
    {
        0x00
    }
};
}
#endif

 
flag asn1SccPusSt23RepositoryDomain_IsConstraintValid(const asn1SccPusSt23RepositoryDomain* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= (int)pus_ST23_MAX_SIZE_REPOSITORY_DOMAIN);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt23RepositoryDomain;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketVersion_Initialize(asn1SccPusPacketVersion* pVal)
{
    *pVal = (asn1SccPusPacketVersion) asn1Sccpus_CCSDS_V1;
}
#endif

 
flag asn1SccPusPacketVersion_IsConstraintValid(const asn1SccPusPacketVersion* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal == asn1Sccpus_CCSDS_V1);
	*pErrCode = ret ? 0 : ERR_asn1SccPusPacketVersion;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketType_Initialize(asn1SccPusPacketType* pVal)
{
    *pVal = (asn1SccPusPacketType) asn1Sccpus_TM;
}
#endif

 
flag asn1SccPusPacketType_IsConstraintValid(const asn1SccPusPacketType* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((*pVal == asn1Sccpus_TM) || (*pVal == asn1Sccpus_TC));
	*pErrCode = ret ? 0 : ERR_asn1SccPusPacketType;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSecondaryHeaderFlag_Initialize(asn1SccPusSecondaryHeaderFlag* pVal)
{
    *pVal = (asn1SccPusSecondaryHeaderFlag) FALSE;
}
#endif

 
flag asn1SccPusSecondaryHeaderFlag_IsConstraintValid(const asn1SccPusSecondaryHeaderFlag* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSequenceFlags_Initialize(asn1SccPusSequenceFlags* pVal)
{
    *pVal = (asn1SccPusSequenceFlags) asn1Sccpus_STANDALONE_PACKET;
}
#endif

 
flag asn1SccPusSequenceFlags_IsConstraintValid(const asn1SccPusSequenceFlags* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (*pVal == asn1Sccpus_STANDALONE_PACKET);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSequenceFlags;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt01RequestId_Initialize(asn1SccPusSt01RequestId* pVal)
{
    *pVal = (asn1SccPusSt01RequestId) {
    .packetVersion = asn1Sccpus_CCSDS_V1,
    .packetType = asn1Sccpus_TM,
    .secondaryHeaderFlag = FALSE,
    .apid = 0,
    .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
    .sequenceCount = 0
};
}
#endif

 
flag asn1SccPusSt01RequestId_IsConstraintValid(const asn1SccPusSt01RequestId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusPacketVersion_IsConstraintValid(&pVal->packetVersion, pErrCode);
	if (ret) {
	    ret = asn1SccPusPacketType_IsConstraintValid(&pVal->packetType, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSecondaryHeaderFlag_IsConstraintValid(&pVal->secondaryHeaderFlag, pErrCode);
	        if (ret) {
	            ret = asn1SccPusApid_IsConstraintValid(&pVal->apid, pErrCode);
	            if (ret) {
	                ret = asn1SccPusSequenceFlags_IsConstraintValid(&pVal->sequenceFlags, pErrCode);
	                if (ret) {
	                    ret = asn1SccPusSequenceCount_IsConstraintValid(&pVal->sequenceCount, pErrCode);
	                
	                }
	            }
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTM_1_X_Data_Initialize(asn1SccPusTM_1_X_Data* pVal)
{
    *pVal = (asn1SccPusTM_1_X_Data) {
    .request = {
        .packetVersion = asn1Sccpus_CCSDS_V1,
        .packetType = asn1Sccpus_TM,
        .secondaryHeaderFlag = FALSE,
        .apid = 0,
        .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
        .sequenceCount = 0
    },
    .step = 0,
    .failure = {
        .code = 0,
        .info = {
            .subcode = -2147483648LL,
            .data = -2147483648LL,
            .address = 0
        }
    }
};
}
#endif

 
flag asn1SccPusTM_1_X_Data_IsConstraintValid(const asn1SccPusTM_1_X_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt01RequestId_IsConstraintValid(&pVal->request, pErrCode);
	if (ret) {
	    ret = asn1SccPusStepId_IsConstraintValid(&pVal->step, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSt01Failure_IsConstraintValid(&pVal->failure, pErrCode);
	    
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTmSourceData_Initialize(asn1SccPusTmSourceData* pVal)
{
    *pVal = (asn1SccPusTmSourceData) {
    .kind = st_1_X_PRESENT,
    .u = { .st_1_X = {
    .request = {
        .packetVersion = asn1Sccpus_CCSDS_V1,
        .packetType = asn1Sccpus_TM,
        .secondaryHeaderFlag = FALSE,
        .apid = 0,
        .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
        .sequenceCount = 0
    },
    .step = 0,
    .failure = {
        .code = 0,
        .info = {
            .subcode = -2147483648LL,
            .data = -2147483648LL,
            .address = 0
        }
    }
}}
};
}
#endif

 
flag asn1SccPusTmSourceData_IsConstraintValid(const asn1SccPusTmSourceData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case st_1_X_PRESENT :
	        ret = asn1SccPusTM_1_X_Data_IsConstraintValid(&pVal->u.st_1_X, pErrCode);
	        break;
	    case st_3_25_PRESENT :
	        ret = asn1SccPusTM_3_25_Data_IsConstraintValid(&pVal->u.st_3_25, pErrCode);
	        break;
	    case st_5_X_PRESENT :
	        ret = asn1SccPusTM_5_X_Data_IsConstraintValid(&pVal->u.st_5_X, pErrCode);
	        break;
	    case st_9_2_PRESENT :
	        ret = asn1SccPusTM_9_2_Data_IsConstraintValid(&pVal->u.st_9_2, pErrCode);
	        break;
	    case st_20_2_PRESENT :
	        ret = asn1SccPusTC_TM_20_X_Data_IsConstraintValid(&pVal->u.st_20_2, pErrCode);
	        break;
	    case st_23_4_PRESENT :
	        ret = asn1SccPusTC_TM_23_1_4_Data_IsConstraintValid(&pVal->u.st_23_4, pErrCode);
	        break;
	    default:
		    *pErrCode = 805568513;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusVersionNumber_Initialize(asn1SccPusVersionNumber* pVal)
{
    *pVal = (asn1SccPusVersionNumber) asn1Sccpus_V0;
}
#endif

 
flag asn1SccPusVersionNumber_IsConstraintValid(const asn1SccPusVersionNumber* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((((*pVal == asn1Sccpus_V0) || (*pVal == asn1Sccpus_V1)) || (*pVal == asn1Sccpus_V2)) || (*pVal == asn1Sccpus_INVALID_VERSION));
	*pErrCode = ret ? 0 : ERR_asn1SccPusVersionNumber;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTmHeader_Initialize(asn1SccPusTmHeader* pVal)
{
    *pVal = (asn1SccPusTmHeader) {
    .pusVersion = asn1Sccpus_V0,
    .timeRefStatus = 0,
    .serviceId = 0,
    .subtype = 0,
    .msgTypeCount = 0,
    .destination = 0,
    .time = {
        .tv_sec = LLONG_MIN,
        .tv_nsec = LLONG_MIN
    }
};
}
#endif

 
flag asn1SccPusTmHeader_IsConstraintValid(const asn1SccPusTmHeader* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusVersionNumber_IsConstraintValid(&pVal->pusVersion, pErrCode);
	if (ret) {
	    ret = asn1SccPusTimeReferenceStatus_IsConstraintValid(&pVal->timeRefStatus, pErrCode);
	    if (ret) {
	        ret = asn1SccPusServiceType_IsConstraintValid(&pVal->serviceId, pErrCode);
	        if (ret) {
	            ret = asn1SccPusSubserviceType_IsConstraintValid(&pVal->subtype, pErrCode);
	            if (ret) {
	                ret = asn1SccPusMessageTypeCounter_IsConstraintValid(&pVal->msgTypeCount, pErrCode);
	                if (ret) {
	                    ret = asn1SccPusApid_IsConstraintValid(&pVal->destination, pErrCode);
	                    if (ret) {
	                        ret = asn1SccPusTime_IsConstraintValid(&pVal->time, pErrCode);
	                    
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTmHeaderData_Initialize(asn1SccPusTmHeaderData* pVal)
{
    *pVal = (asn1SccPusTmHeaderData) {
    .header = {
        .pusVersion = asn1Sccpus_V0,
        .timeRefStatus = 0,
        .serviceId = 0,
        .subtype = 0,
        .msgTypeCount = 0,
        .destination = 0,
        .time = {
            .tv_sec = LLONG_MIN,
            .tv_nsec = LLONG_MIN
        }
    },
    .data = {
        .kind = st_1_X_PRESENT,
        .u = { .st_1_X = {
        .request = {
            .packetVersion = asn1Sccpus_CCSDS_V1,
            .packetType = asn1Sccpus_TM,
            .secondaryHeaderFlag = FALSE,
            .apid = 0,
            .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
            .sequenceCount = 0
        },
        .step = 0,
        .failure = {
            .code = 0,
            .info = {
                .subcode = -2147483648LL,
                .data = -2147483648LL,
                .address = 0
            }
        }
    }}
    }
};
}
#endif

 
flag asn1SccPusTmHeaderData_IsConstraintValid(const asn1SccPusTmHeaderData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusTmHeader_IsConstraintValid(&pVal->header, pErrCode);
	if (ret) {
	    ret = asn1SccPusTmSourceData_IsConstraintValid(&pVal->data, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusAcknowledgementFlags_Initialize(asn1SccPusAcknowledgementFlags* pVal)
{
    *pVal = (asn1SccPusAcknowledgementFlags) {
    .acceptanceReportRequested = FALSE,
    .startReportRequested = FALSE,
    .progressReportRequested = FALSE,
    .completionReportRequested = FALSE
};
}
#endif

 
flag asn1SccPusAcknowledgementFlags_IsConstraintValid(const asn1SccPusAcknowledgementFlags* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = TRUE; *pErrCode = 0;
	if (ret) {
	    ret = TRUE; *pErrCode = 0;
	    if (ret) {
	        ret = TRUE; *pErrCode = 0;
	        if (ret) {
	            ret = TRUE; *pErrCode = 0;
	        
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTcHeader_Initialize(asn1SccPusTcHeader* pVal)
{
    *pVal = (asn1SccPusTcHeader) {
    .pusVersion = asn1Sccpus_V0,
    .ackFlags = {
        .acceptanceReportRequested = FALSE,
        .startReportRequested = FALSE,
        .progressReportRequested = FALSE,
        .completionReportRequested = FALSE
    },
    .serviceId = 0,
    .subtype = 0,
    .source = 0
};
}
#endif

 
flag asn1SccPusTcHeader_IsConstraintValid(const asn1SccPusTcHeader* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusVersionNumber_IsConstraintValid(&pVal->pusVersion, pErrCode);
	if (ret) {
	    ret = asn1SccPusAcknowledgementFlags_IsConstraintValid(&pVal->ackFlags, pErrCode);
	    if (ret) {
	        ret = asn1SccPusServiceType_IsConstraintValid(&pVal->serviceId, pErrCode);
	        if (ret) {
	            ret = asn1SccPusSubserviceType_IsConstraintValid(&pVal->subtype, pErrCode);
	            if (ret) {
	                ret = asn1SccPusApid_IsConstraintValid(&pVal->source, pErrCode);
	            
	            }
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt18ObcpId_Initialize(asn1SccPusSt18ObcpId* pVal)
{
    *pVal = (asn1SccPusSt18ObcpId) {
    {
        0x00
    }
};
}
#endif

 
flag asn1SccPusSt18ObcpId_IsConstraintValid(const asn1SccPusSt18ObcpId* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (10 == (int)pus_ST18_SIZE_OBCP_ID);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt18ObcpId;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_18_2_6_12_Data_Initialize(asn1SccPusTC_18_2_6_12_Data* pVal)
{
    *pVal = (asn1SccPusTC_18_2_6_12_Data) {
    .obcpId = {
        {
            0x00
        }
    }
};
}
#endif

 
flag asn1SccPusTC_18_2_6_12_Data_IsConstraintValid(const asn1SccPusTC_18_2_6_12_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt18ObcpId_IsConstraintValid(&pVal->obcpId, pErrCode);


	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_18_4_5_Data_Initialize(asn1SccPusTC_18_4_5_Data* pVal)
{
    *pVal = (asn1SccPusTC_18_4_5_Data) {
    .obcpId = {
        {
            0x00
        }
    },
    .stepId = 0
};
}
#endif

 
flag asn1SccPusTC_18_4_5_Data_IsConstraintValid(const asn1SccPusTC_18_4_5_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt18ObcpId_IsConstraintValid(&pVal->obcpId, pErrCode);
	if (ret) {
	    ret = asn1SccPusUInt32_IsConstraintValid(&pVal->stepId, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_18_13_Data_Initialize(asn1SccPusTC_18_13_Data* pVal)
{
    *pVal = (asn1SccPusTC_18_13_Data) {
    .obcpId = {
        {
            0x00
        }
    },
    .repository = {1,
        {
            0x00
        }
    },
    .fileName = {1,
        {
            0x00
        }
    }
};
}
#endif

 
flag asn1SccPusTC_18_13_Data_IsConstraintValid(const asn1SccPusTC_18_13_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt18ObcpId_IsConstraintValid(&pVal->obcpId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt23RepositoryPath_IsConstraintValid(&pVal->repository, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSt23FileName_IsConstraintValid(&pVal->fileName, pErrCode);
	    
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt18ObcpCode_Initialize(asn1SccPusSt18ObcpCode* pVal)
{
    *pVal = (asn1SccPusSt18ObcpCode) {1,
    {
        0x00
    }
};
}
#endif

 
flag asn1SccPusSt18ObcpCode_IsConstraintValid(const asn1SccPusSt18ObcpCode* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= (int)pus_ST18_MAX_SIZE_OBCP_CODE);
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt18ObcpCode;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_18_1_Data_Initialize(asn1SccPusTC_18_1_Data* pVal)
{
    *pVal = (asn1SccPusTC_18_1_Data) {
    .obcpId = {
        {
            0x00
        }
    },
    .obcpCode = {1,
        {
            0x00
        }
    },
    .checksum = 0
};
}
#endif

 
flag asn1SccPusTC_18_1_Data_IsConstraintValid(const asn1SccPusTC_18_1_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt18ObcpId_IsConstraintValid(&pVal->obcpId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt18ObcpCode_IsConstraintValid(&pVal->obcpCode, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSt18ObcpChecksum_IsConstraintValid(&pVal->checksum, pErrCode);
	    
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusSt18ObservabilityLevel_Initialize(asn1SccPusSt18ObservabilityLevel* pVal)
{
    *pVal = (asn1SccPusSt18ObservabilityLevel) asn1Sccnone;
}
#endif

 
flag asn1SccPusSt18ObservabilityLevel_IsConstraintValid(const asn1SccPusSt18ObservabilityLevel* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = ((((*pVal == asn1Sccnone) || (*pVal == asn1Sccprocedure)) || (*pVal == asn1Sccstep)) || (*pVal == asn1Sccdetailed));
	*pErrCode = ret ? 0 : ERR_asn1SccPusSt18ObservabilityLevel;

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_18_3_Data_Initialize(asn1SccPusTC_18_3_Data* pVal)
{
    *pVal = (asn1SccPusTC_18_3_Data) {
    .obcpId = {
        {
            0x00
        }
    },
    .observabilityLevel = asn1Sccnone
};
}
#endif

 
flag asn1SccPusTC_18_3_Data_IsConstraintValid(const asn1SccPusTC_18_3_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt18ObcpId_IsConstraintValid(&pVal->obcpId, pErrCode);
	if (ret) {
	    ret = asn1SccPusSt18ObservabilityLevel_IsConstraintValid(&pVal->observabilityLevel, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTcApplicationDataReduced_Initialize(asn1SccPusTcApplicationDataReduced* pVal)
{
    *pVal = (asn1SccPusTcApplicationDataReduced) {
    .kind = PusTcApplicationDataReduced_st_8_1_PRESENT,
    .u = { .st_8_1 = {
    .functionId = 0
}}
};
}
#endif

 
flag asn1SccPusTcApplicationDataReduced_IsConstraintValid(const asn1SccPusTcApplicationDataReduced* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case PusTcApplicationDataReduced_st_8_1_PRESENT :
	        ret = asn1SccPusTC_8_1_Data_IsConstraintValid(&pVal->u.st_8_1, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_9_1_PRESENT :
	        ret = asn1SccPusTC_9_1_Data_IsConstraintValid(&pVal->u.st_9_1, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_12_1_2_PRESENT :
	        ret = asn1SccPusTC_12_1_2_Data_IsConstraintValid(&pVal->u.st_12_1_2, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_18_2_6_12_PRESENT :
	        ret = asn1SccPusTC_18_2_6_12_Data_IsConstraintValid(&pVal->u.st_18_2_6_12, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_18_3_PRESENT :
	        ret = asn1SccPusTC_18_3_Data_IsConstraintValid(&pVal->u.st_18_3, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_18_4_5_PRESENT :
	        ret = asn1SccPusTC_18_4_5_Data_IsConstraintValid(&pVal->u.st_18_4_5, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_18_13_PRESENT :
	        ret = asn1SccPusTC_18_13_Data_IsConstraintValid(&pVal->u.st_18_13, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_19_X_PRESENT :
	        ret = asn1SccPusTC_19_X_Data_IsConstraintValid(&pVal->u.st_19_X, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_20_X_PRESENT :
	        ret = asn1SccPusTC_TM_20_X_Data_IsConstraintValid(&pVal->u.st_20_X, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_23_1_PRESENT :
	        ret = asn1SccPusTC_TM_23_1_4_Data_IsConstraintValid(&pVal->u.st_23_1, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_23_2_3_PRESENT :
	        ret = asn1SccPusTC_23_2_3_Data_IsConstraintValid(&pVal->u.st_23_2_3, pErrCode);
	        break;
	    case PusTcApplicationDataReduced_st_23_14_PRESENT :
	        ret = asn1SccPusTC_23_14_Data_IsConstraintValid(&pVal->u.st_23_14, pErrCode);
	        break;
	    default:
		    *pErrCode = 805568514;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketDataReduced_tcData_Initialize(asn1SccPusPacketDataReduced_tcData* pVal)
{
    *pVal = (asn1SccPusPacketDataReduced_tcData) {
    .header = {
        .pusVersion = asn1Sccpus_V0,
        .ackFlags = {
            .acceptanceReportRequested = FALSE,
            .startReportRequested = FALSE,
            .progressReportRequested = FALSE,
            .completionReportRequested = FALSE
        },
        .serviceId = 0,
        .subtype = 0,
        .source = 0
    },
    .data = {
        .kind = PusTcApplicationDataReduced_st_8_1_PRESENT,
        .u = { .st_8_1 = {
        .functionId = 0
    }}
    }
};
}
#endif

 
flag asn1SccPusPacketDataReduced_tcData_IsConstraintValid(const asn1SccPusPacketDataReduced_tcData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusTcHeader_IsConstraintValid(&pVal->header, pErrCode);
	if (ret) {
	    ret = asn1SccPusTcApplicationDataReduced_IsConstraintValid(&pVal->data, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketDataReduced_Initialize(asn1SccPusPacketDataReduced* pVal)
{
    *pVal = (asn1SccPusPacketDataReduced) {
    .kind = PusPacketDataReduced_tmData_PRESENT,
    .u = { .tmData = {
    .header = {
        .pusVersion = asn1Sccpus_V0,
        .timeRefStatus = 0,
        .serviceId = 0,
        .subtype = 0,
        .msgTypeCount = 0,
        .destination = 0,
        .time = {
            .tv_sec = LLONG_MIN,
            .tv_nsec = LLONG_MIN
        }
    },
    .data = {
        .kind = st_1_X_PRESENT,
        .u = { .st_1_X = {
        .request = {
            .packetVersion = asn1Sccpus_CCSDS_V1,
            .packetType = asn1Sccpus_TM,
            .secondaryHeaderFlag = FALSE,
            .apid = 0,
            .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
            .sequenceCount = 0
        },
        .step = 0,
        .failure = {
            .code = 0,
            .info = {
                .subcode = -2147483648LL,
                .data = -2147483648LL,
                .address = 0
            }
        }
    }}
    }
}}
};
}
#endif

 
flag asn1SccPusPacketDataReduced_IsConstraintValid(const asn1SccPusPacketDataReduced* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case PusPacketDataReduced_tmData_PRESENT :
	        ret = asn1SccPusTmHeaderData_IsConstraintValid(&pVal->u.tmData, pErrCode);
	        break;
	    case PusPacketDataReduced_tmDataNoHeader_PRESENT :
	        ret = asn1SccPusTmSourceData_IsConstraintValid(&pVal->u.tmDataNoHeader, pErrCode);
	        break;
	    case PusPacketDataReduced_tcData_PRESENT :
	        ret = asn1SccPusPacketDataReduced_tcData_IsConstraintValid(&pVal->u.tcData, pErrCode);
	        break;
	    case PusPacketDataReduced_tcDataNoHeader_PRESENT :
	        ret = asn1SccPusTcApplicationDataReduced_IsConstraintValid(&pVal->u.tcDataNoHeader, pErrCode);
	        break;
	    default:
		    *pErrCode = 805568515;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketReduced_Initialize(asn1SccPusPacketReduced* pVal)
{
    *pVal = (asn1SccPusPacketReduced) {
    .packetVersion = asn1Sccpus_CCSDS_V1,
    .packetType = asn1Sccpus_TM,
    .secondaryHeaderFlag = FALSE,
    .apid = 0,
    .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
    .sequenceCount = 0,
    .dataLength = 0,
    .data = {
        .kind = PusPacketDataReduced_tmData_PRESENT,
        .u = { .tmData = {
        .header = {
            .pusVersion = asn1Sccpus_V0,
            .timeRefStatus = 0,
            .serviceId = 0,
            .subtype = 0,
            .msgTypeCount = 0,
            .destination = 0,
            .time = {
                .tv_sec = LLONG_MIN,
                .tv_nsec = LLONG_MIN
            }
        },
        .data = {
            .kind = st_1_X_PRESENT,
            .u = { .st_1_X = {
            .request = {
                .packetVersion = asn1Sccpus_CCSDS_V1,
                .packetType = asn1Sccpus_TM,
                .secondaryHeaderFlag = FALSE,
                .apid = 0,
                .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                .sequenceCount = 0
            },
            .step = 0,
            .failure = {
                .code = 0,
                .info = {
                    .subcode = -2147483648LL,
                    .data = -2147483648LL,
                    .address = 0
                }
            }
        }}
        }
    }}
    }
};
}
#endif

 
flag asn1SccPusPacketReduced_IsConstraintValid(const asn1SccPusPacketReduced* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusPacketVersion_IsConstraintValid(&pVal->packetVersion, pErrCode);
	if (ret) {
	    ret = asn1SccPusPacketType_IsConstraintValid(&pVal->packetType, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSecondaryHeaderFlag_IsConstraintValid(&pVal->secondaryHeaderFlag, pErrCode);
	        if (ret) {
	            ret = asn1SccPusApid_IsConstraintValid(&pVal->apid, pErrCode);
	            if (ret) {
	                ret = asn1SccPusSequenceFlags_IsConstraintValid(&pVal->sequenceFlags, pErrCode);
	                if (ret) {
	                    ret = asn1SccPusSequenceCount_IsConstraintValid(&pVal->sequenceCount, pErrCode);
	                    if (ret) {
	                        ret = asn1SccPusPacketDataLength_IsConstraintValid(&pVal->dataLength, pErrCode);
	                        if (ret) {
	                            ret = asn1SccPusPacketDataReduced_IsConstraintValid(&pVal->data, pErrCode);
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_19_1_Data_Initialize(asn1SccPusTC_19_1_Data* pVal)
{
    *pVal = (asn1SccPusTC_19_1_Data) {
    .eventId = 0,
    .packetReduced = {
        .packetVersion = asn1Sccpus_CCSDS_V1,
        .packetType = asn1Sccpus_TM,
        .secondaryHeaderFlag = FALSE,
        .apid = 0,
        .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
        .sequenceCount = 0,
        .dataLength = 0,
        .data = {
            .kind = PusPacketDataReduced_tmData_PRESENT,
            .u = { .tmData = {
            .header = {
                .pusVersion = asn1Sccpus_V0,
                .timeRefStatus = 0,
                .serviceId = 0,
                .subtype = 0,
                .msgTypeCount = 0,
                .destination = 0,
                .time = {
                    .tv_sec = LLONG_MIN,
                    .tv_nsec = LLONG_MIN
                }
            },
            .data = {
                .kind = st_1_X_PRESENT,
                .u = { .st_1_X = {
                .request = {
                    .packetVersion = asn1Sccpus_CCSDS_V1,
                    .packetType = asn1Sccpus_TM,
                    .secondaryHeaderFlag = FALSE,
                    .apid = 0,
                    .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                    .sequenceCount = 0
                },
                .step = 0,
                .failure = {
                    .code = 0,
                    .info = {
                        .subcode = -2147483648LL,
                        .data = -2147483648LL,
                        .address = 0
                    }
                }
            }}
            }
        }}
        }
    }
};
}
#endif

 
flag asn1SccPusTC_19_1_Data_IsConstraintValid(const asn1SccPusTC_19_1_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusSt05EventId_IsConstraintValid(&pVal->eventId, pErrCode);
	if (ret) {
	    ret = asn1SccPusPacketReduced_IsConstraintValid(&pVal->packetReduced, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTcScheduledActivity_Initialize(asn1SccPusTcScheduledActivity* pVal)
{
    *pVal = (asn1SccPusTcScheduledActivity) {
    .time = {
        .tv_sec = LLONG_MIN,
        .tv_nsec = LLONG_MIN
    },
    .packetReduced = {
        .packetVersion = asn1Sccpus_CCSDS_V1,
        .packetType = asn1Sccpus_TM,
        .secondaryHeaderFlag = FALSE,
        .apid = 0,
        .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
        .sequenceCount = 0,
        .dataLength = 0,
        .data = {
            .kind = PusPacketDataReduced_tmData_PRESENT,
            .u = { .tmData = {
            .header = {
                .pusVersion = asn1Sccpus_V0,
                .timeRefStatus = 0,
                .serviceId = 0,
                .subtype = 0,
                .msgTypeCount = 0,
                .destination = 0,
                .time = {
                    .tv_sec = LLONG_MIN,
                    .tv_nsec = LLONG_MIN
                }
            },
            .data = {
                .kind = st_1_X_PRESENT,
                .u = { .st_1_X = {
                .request = {
                    .packetVersion = asn1Sccpus_CCSDS_V1,
                    .packetType = asn1Sccpus_TM,
                    .secondaryHeaderFlag = FALSE,
                    .apid = 0,
                    .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                    .sequenceCount = 0
                },
                .step = 0,
                .failure = {
                    .code = 0,
                    .info = {
                        .subcode = -2147483648LL,
                        .data = -2147483648LL,
                        .address = 0
                    }
                }
            }}
            }
        }}
        }
    }
};
}
#endif

 
flag asn1SccPusTcScheduledActivity_IsConstraintValid(const asn1SccPusTcScheduledActivity* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusTime_IsConstraintValid(&pVal->time, pErrCode);
	if (ret) {
	    ret = asn1SccPusPacketReduced_IsConstraintValid(&pVal->packetReduced, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTC_11_4_Data_Initialize(asn1SccPusTC_11_4_Data* pVal)
{
    *pVal = (asn1SccPusTC_11_4_Data) {    .nCount = 1,    .arr = 
    {
        {
            .time = {
                .tv_sec = LLONG_MIN,
                .tv_nsec = LLONG_MIN
            },
            .packetReduced = {
                .packetVersion = asn1Sccpus_CCSDS_V1,
                .packetType = asn1Sccpus_TM,
                .secondaryHeaderFlag = FALSE,
                .apid = 0,
                .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                .sequenceCount = 0,
                .dataLength = 0,
                .data = {
                    .kind = PusPacketDataReduced_tmData_PRESENT,
                    .u = { .tmData = {
                    .header = {
                        .pusVersion = asn1Sccpus_V0,
                        .timeRefStatus = 0,
                        .serviceId = 0,
                        .subtype = 0,
                        .msgTypeCount = 0,
                        .destination = 0,
                        .time = {
                            .tv_sec = LLONG_MIN,
                            .tv_nsec = LLONG_MIN
                        }
                    },
                    .data = {
                        .kind = st_1_X_PRESENT,
                        .u = { .st_1_X = {
                        .request = {
                            .packetVersion = asn1Sccpus_CCSDS_V1,
                            .packetType = asn1Sccpus_TM,
                            .secondaryHeaderFlag = FALSE,
                            .apid = 0,
                            .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                            .sequenceCount = 0
                        },
                        .step = 0,
                        .failure = {
                            .code = 0,
                            .info = {
                                .subcode = -2147483648LL,
                                .data = -2147483648LL,
                                .address = 0
                            }
                        }
                    }}
                    }
                }}
                }
            }
        }        
    }
};
}
#endif

 
flag asn1SccPusTC_11_4_Data_IsConstraintValid(const asn1SccPusTC_11_4_Data* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	int i1=0;
	*pErrCode=0;

	(void)pVal;

	ret = (1 <= pVal->nCount && pVal->nCount <= (int)pus_ST11_MAX_SCHEDULED_ACTIVITIES);
	*pErrCode = ret ? 0 : ERR_asn1SccPusTC_11_4_Data;
	i1 = 0;
	while (ret && (i1< pVal->nCount)) {
	    ret = asn1SccPusTcScheduledActivity_IsConstraintValid(&pVal->arr[i1], pErrCode);
	    i1 = i1+1;
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusTcApplicationData_Initialize(asn1SccPusTcApplicationData* pVal)
{
    *pVal = (asn1SccPusTcApplicationData) {
    .kind = PusTcApplicationData_st_8_1_PRESENT,
    .u = { .st_8_1 = {
    .functionId = 0
}}
};
}
#endif

 
flag asn1SccPusTcApplicationData_IsConstraintValid(const asn1SccPusTcApplicationData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case PusTcApplicationData_st_8_1_PRESENT :
	        ret = asn1SccPusTC_8_1_Data_IsConstraintValid(&pVal->u.st_8_1, pErrCode);
	        break;
	    case PusTcApplicationData_st_9_1_PRESENT :
	        ret = asn1SccPusTC_9_1_Data_IsConstraintValid(&pVal->u.st_9_1, pErrCode);
	        break;
	    case PusTcApplicationData_st_12_1_2_PRESENT :
	        ret = asn1SccPusTC_12_1_2_Data_IsConstraintValid(&pVal->u.st_12_1_2, pErrCode);
	        break;
	    case PusTcApplicationData_st_18_2_6_12_PRESENT :
	        ret = asn1SccPusTC_18_2_6_12_Data_IsConstraintValid(&pVal->u.st_18_2_6_12, pErrCode);
	        break;
	    case PusTcApplicationData_st_18_3_PRESENT :
	        ret = asn1SccPusTC_18_3_Data_IsConstraintValid(&pVal->u.st_18_3, pErrCode);
	        break;
	    case PusTcApplicationData_st_18_4_5_PRESENT :
	        ret = asn1SccPusTC_18_4_5_Data_IsConstraintValid(&pVal->u.st_18_4_5, pErrCode);
	        break;
	    case PusTcApplicationData_st_18_13_PRESENT :
	        ret = asn1SccPusTC_18_13_Data_IsConstraintValid(&pVal->u.st_18_13, pErrCode);
	        break;
	    case PusTcApplicationData_st_19_X_PRESENT :
	        ret = asn1SccPusTC_19_X_Data_IsConstraintValid(&pVal->u.st_19_X, pErrCode);
	        break;
	    case PusTcApplicationData_st_20_X_PRESENT :
	        ret = asn1SccPusTC_TM_20_X_Data_IsConstraintValid(&pVal->u.st_20_X, pErrCode);
	        break;
	    case PusTcApplicationData_st_23_1_PRESENT :
	        ret = asn1SccPusTC_TM_23_1_4_Data_IsConstraintValid(&pVal->u.st_23_1, pErrCode);
	        break;
	    case PusTcApplicationData_st_23_2_3_PRESENT :
	        ret = asn1SccPusTC_23_2_3_Data_IsConstraintValid(&pVal->u.st_23_2_3, pErrCode);
	        break;
	    case PusTcApplicationData_st_23_14_PRESENT :
	        ret = asn1SccPusTC_23_14_Data_IsConstraintValid(&pVal->u.st_23_14, pErrCode);
	        break;
	    case st_11_4_PRESENT :
	        ret = asn1SccPusTC_11_4_Data_IsConstraintValid(&pVal->u.st_11_4, pErrCode);
	        break;
	    case st_18_1_PRESENT :
	        ret = asn1SccPusTC_18_1_Data_IsConstraintValid(&pVal->u.st_18_1, pErrCode);
	        break;
	    case st_19_1_PRESENT :
	        ret = asn1SccPusTC_19_1_Data_IsConstraintValid(&pVal->u.st_19_1, pErrCode);
	        break;
	    default:
		    *pErrCode = 805568516;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketData_tcData_Initialize(asn1SccPusPacketData_tcData* pVal)
{
    *pVal = (asn1SccPusPacketData_tcData) {
    .header = {
        .pusVersion = asn1Sccpus_V0,
        .ackFlags = {
            .acceptanceReportRequested = FALSE,
            .startReportRequested = FALSE,
            .progressReportRequested = FALSE,
            .completionReportRequested = FALSE
        },
        .serviceId = 0,
        .subtype = 0,
        .source = 0
    },
    .data = {
        .kind = PusTcApplicationData_st_8_1_PRESENT,
        .u = { .st_8_1 = {
        .functionId = 0
    }}
    }
};
}
#endif

 
flag asn1SccPusPacketData_tcData_IsConstraintValid(const asn1SccPusPacketData_tcData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusTcHeader_IsConstraintValid(&pVal->header, pErrCode);
	if (ret) {
	    ret = asn1SccPusTcApplicationData_IsConstraintValid(&pVal->data, pErrCode);
	
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacketData_Initialize(asn1SccPusPacketData* pVal)
{
    *pVal = (asn1SccPusPacketData) {
    .kind = PusPacketData_tmData_PRESENT,
    .u = { .tmData = {
    .header = {
        .pusVersion = asn1Sccpus_V0,
        .timeRefStatus = 0,
        .serviceId = 0,
        .subtype = 0,
        .msgTypeCount = 0,
        .destination = 0,
        .time = {
            .tv_sec = LLONG_MIN,
            .tv_nsec = LLONG_MIN
        }
    },
    .data = {
        .kind = st_1_X_PRESENT,
        .u = { .st_1_X = {
        .request = {
            .packetVersion = asn1Sccpus_CCSDS_V1,
            .packetType = asn1Sccpus_TM,
            .secondaryHeaderFlag = FALSE,
            .apid = 0,
            .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
            .sequenceCount = 0
        },
        .step = 0,
        .failure = {
            .code = 0,
            .info = {
                .subcode = -2147483648LL,
                .data = -2147483648LL,
                .address = 0
            }
        }
    }}
    }
}}
};
}
#endif

 
flag asn1SccPusPacketData_IsConstraintValid(const asn1SccPusPacketData* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	switch (pVal->kind) {
	    case PusPacketData_tmData_PRESENT :
	        ret = asn1SccPusTmHeaderData_IsConstraintValid(&pVal->u.tmData, pErrCode);
	        break;
	    case PusPacketData_tmDataNoHeader_PRESENT :
	        ret = asn1SccPusTmSourceData_IsConstraintValid(&pVal->u.tmDataNoHeader, pErrCode);
	        break;
	    case PusPacketData_tcData_PRESENT :
	        ret = asn1SccPusPacketData_tcData_IsConstraintValid(&pVal->u.tcData, pErrCode);
	        break;
	    case PusPacketData_tcDataNoHeader_PRESENT :
	        ret = asn1SccPusTcApplicationData_IsConstraintValid(&pVal->u.tcDataNoHeader, pErrCode);
	        break;
	    default:
		    *pErrCode = 805568517;   //COVERAGE_IGNORE
		    ret = FALSE;                    //COVERAGE_IGNORE
	}

	return ret;
}
#if !defined(_MSC_VER) || _MSC_VER >= 1800
void asn1SccPusPacket_Initialize(asn1SccPusPacket* pVal)
{
    *pVal = (asn1SccPusPacket) {
    .packetVersion = asn1Sccpus_CCSDS_V1,
    .packetType = asn1Sccpus_TM,
    .secondaryHeaderFlag = FALSE,
    .apid = 0,
    .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
    .sequenceCount = 0,
    .dataLength = 0,
    .data = {
        .kind = PusPacketData_tmData_PRESENT,
        .u = { .tmData = {
        .header = {
            .pusVersion = asn1Sccpus_V0,
            .timeRefStatus = 0,
            .serviceId = 0,
            .subtype = 0,
            .msgTypeCount = 0,
            .destination = 0,
            .time = {
                .tv_sec = LLONG_MIN,
                .tv_nsec = LLONG_MIN
            }
        },
        .data = {
            .kind = st_1_X_PRESENT,
            .u = { .st_1_X = {
            .request = {
                .packetVersion = asn1Sccpus_CCSDS_V1,
                .packetType = asn1Sccpus_TM,
                .secondaryHeaderFlag = FALSE,
                .apid = 0,
                .sequenceFlags = asn1Sccpus_STANDALONE_PACKET,
                .sequenceCount = 0
            },
            .step = 0,
            .failure = {
                .code = 0,
                .info = {
                    .subcode = -2147483648LL,
                    .data = -2147483648LL,
                    .address = 0
                }
            }
        }}
        }
    }}
    }
};
}
#endif

 
flag asn1SccPusPacket_IsConstraintValid(const asn1SccPusPacket* pVal, int* pErrCode)
{
    
    flag ret = TRUE;
	*pErrCode=0;

	(void)pVal;

	ret = asn1SccPusPacketVersion_IsConstraintValid(&pVal->packetVersion, pErrCode);
	if (ret) {
	    ret = asn1SccPusPacketType_IsConstraintValid(&pVal->packetType, pErrCode);
	    if (ret) {
	        ret = asn1SccPusSecondaryHeaderFlag_IsConstraintValid(&pVal->secondaryHeaderFlag, pErrCode);
	        if (ret) {
	            ret = asn1SccPusApid_IsConstraintValid(&pVal->apid, pErrCode);
	            if (ret) {
	                ret = asn1SccPusSequenceFlags_IsConstraintValid(&pVal->sequenceFlags, pErrCode);
	                if (ret) {
	                    ret = asn1SccPusSequenceCount_IsConstraintValid(&pVal->sequenceCount, pErrCode);
	                    if (ret) {
	                        ret = asn1SccPusPacketDataLength_IsConstraintValid(&pVal->dataLength, pErrCode);
	                        if (ret) {
	                            ret = asn1SccPusPacketData_IsConstraintValid(&pVal->data, pErrCode);
	                        
	                        }
	                    }
	                }
	            }
	        }
	    }
	}

	return ret;
}

const asn1SccPusPacketVersion pus_PACKET_VERSION_CURRENT = asn1Sccpus_CCSDS_V1;

const asn1SccPusApid pus_APID_TIME = 0;

const asn1SccPusApid pus_APID_IDLE = 2047;

const asn1SccPusVersionNumber pus_VERSION_CURRENT = asn1Sccpus_V2;

const asn1SccPusTimeReferenceStatus pus_TIME_REFERENCE_STATUS_NONE = 0;

const asn1SccPusMessageTypeCounter pus_MESSAGE_TYPE_COUNTER_NONE = 0;

const asn1SccPusStepId pus_STEP_NONE = 0;

const asn1SccPusServiceType pusService_NONE = 0;

const asn1SccPusServiceType pus_ST01_requestVerification = 1;

const asn1SccPusServiceType pus_ST02_deviceAccess = 2;

const asn1SccPusServiceType pus_ST03_housekeeping = 3;

const asn1SccPusServiceType pus_ST04_parameterStatisticsReporting = 4;

const asn1SccPusServiceType pus_ST05_eventReporting = 5;

const asn1SccPusServiceType pus_ST06_memoryManagement = 6;

const asn1SccPusServiceType pus_ST08_functionManagement = 8;

const asn1SccPusServiceType pus_ST09_timeManagement = 9;

const asn1SccPusServiceType pus_ST11_timeBasedScheduling = 11;

const asn1SccPusServiceType pus_ST12_onBoardMonitoring = 12;

const asn1SccPusServiceType pus_ST13_largePacketTransfer = 13;

const asn1SccPusServiceType pus_ST14_realTimeForwardingControl = 14;

const asn1SccPusServiceType pus_ST15_onBoardStorageAndRetrieval = 15;

const asn1SccPusServiceType pus_ST17_test = 17;

const asn1SccPusServiceType pus_ST18_onBoardControlProcedure = 18;

const asn1SccPusServiceType pus_ST19_eventAction = 19;

const asn1SccPusServiceType pus_ST20_parameterManagement = 20;

const asn1SccPusServiceType pus_ST21_requestSequencing = 21;

const asn1SccPusServiceType pus_ST22_partitionBasedScheduling = 22;

const asn1SccPusServiceType pus_ST23_fileManagement = 23;

const asn1SccPusSubserviceType pusSubtype_NONE = 0;

const asn1SccPusSubserviceType pus_TM_1_1_successfulAcceptance = 1;

const asn1SccPusSubserviceType pus_TM_1_2_failedAcceptance = 2;

const asn1SccPusSubserviceType pus_TM_1_3_successfulStart = 3;

const asn1SccPusSubserviceType pus_TM_1_4_failedStart = 4;

const asn1SccPusSubserviceType pus_TM_1_5_successfulProgress = 5;

const asn1SccPusSubserviceType pus_TM_1_6_failedProgress = 6;

const asn1SccPusSubserviceType pus_TM_1_7_successfulCompletion = 7;

const asn1SccPusSubserviceType pus_TM_1_8_failedCompletion = 8;

const asn1SccPusSubserviceType pus_TM_3_25_housekeepingReport = 25;

const asn1SccPusSubserviceType pus_TM_5_1_eventInformative = 1;

const asn1SccPusSubserviceType pus_TM_5_2_anomalyLowSeverity = 2;

const asn1SccPusSubserviceType pus_TM_5_3_anomalyMediumSeverity = 3;

const asn1SccPusSubserviceType pus_TM_5_4_anomalyHighSeverity = 4;

const asn1SccPusSubserviceType pus_TC_8_1_performFunction = 1;

const asn1SccPusSubserviceType pus_TC_9_1_setTimeReportRate = 1;

const asn1SccPusSubserviceType pus_TM_9_2_cucTimeReport = 2;

const asn1SccPusSubserviceType pus_TC_11_1_enableTimeBasedScheduling = 1;

const asn1SccPusSubserviceType pus_TC_11_2_disableTimeBasedScheduling = 2;

const asn1SccPusSubserviceType pus_TC_11_3_resetTimeBasedSchedule = 3;

const asn1SccPusSubserviceType pus_TC_11_4_insertActivity = 4;

const asn1SccPusSubserviceType pus_TC_12_1_enableParameterMonitoringDefinitions = 1;

const asn1SccPusSubserviceType pus_TC_12_2_disableParameterMonitoringDefinitions = 2;

const asn1SccPusSubserviceType pus_TC_12_15_enableParameterMonitoring = 15;

const asn1SccPusSubserviceType pus_TC_12_16_disableParameterMonitoring = 16;

const asn1SccPusSubserviceType pus_TC_17_1_connectionTest = 1;

const asn1SccPusSubserviceType pus_TM_17_2_connectionTest = 2;

const asn1SccPusSubserviceType pus_TC_18_1_loadObcpDirect = 1;

const asn1SccPusSubserviceType pus_TC_18_2_unloadObcp = 2;

const asn1SccPusSubserviceType pus_TC_18_3_activateObcp = 3;

const asn1SccPusSubserviceType pus_TC_18_4_stopObcp = 4;

const asn1SccPusSubserviceType pus_TC_18_5_suspendObcp = 5;

const asn1SccPusSubserviceType pus_TC_18_6_resumeObcp = 6;

const asn1SccPusSubserviceType pus_TC_18_12_abortObcp = 12;

const asn1SccPusSubserviceType pus_TC_18_13_loadObcpByReference = 13;

const asn1SccPusSubserviceType pus_TC_18_21_startObcpEngine = 21;

const asn1SccPusSubserviceType pus_TC_18_22_stopObcpEngine = 22;

const asn1SccPusSubserviceType pus_TC_19_1_addEventActionDefinitions = 1;

const asn1SccPusSubserviceType pus_TC_19_2_deleteEventActionDefinitions = 2;

const asn1SccPusSubserviceType pus_TC_19_4_enableEventActionDefinitions = 4;

const asn1SccPusSubserviceType pus_TC_19_5_disableEventActionDefinitions = 5;

const asn1SccPusSubserviceType pus_TC_20_1_reportParameterValues = 1;

const asn1SccPusSubserviceType pus_TM_20_2_reportParameterValues = 2;

const asn1SccPusSubserviceType pus_TC_20_3_setParameterValues = 3;

const asn1SccPusSubserviceType pus_TC_23_1_createFile = 1;

const asn1SccPusSubserviceType pus_TC_23_2_deleteFile = 2;

const asn1SccPusSubserviceType pus_TC_23_3_reportFileAttributes = 3;

const asn1SccPusSubserviceType pus_TM_23_4_reportFileAttributes = 4;

const asn1SccPusSubserviceType pus_TC_23_14_copyFile = 14;

const asn1SccPusSt05EventId pus_EVENT_ID_NONE = 0;

const asn1SccPusSt05EventAuxData pus_EVENT_AUXDATA_NONE = {
    .data1 = 0,
    .data2 = 0
};

const asn1SccPusUInt64 pus_EVENT_DATASTORED_NONE = 0;

const asn1SccPusUInt32 pus_ST03_MAX_REPORT_LENGTH = 20;

const asn1SccPusUInt32 pus_ST11_MAX_SCHEDULED_ACTIVITIES = 5;

const asn1SccPusUInt32 pus_ST18_SIZE_OBCP_ID = 10;

const asn1SccPusUInt32 pus_ST18_MAX_SIZE_OBCP_CODE = 15000;

const asn1SccPusUInt32 pus_ST18_SIZE_OBCP_CHECKSUM = 16;

const asn1SccPusUInt32 pus_ST23_MAX_SIZE_FILE_PATH = 30;

const asn1SccPusUInt32 pus_ST23_MAX_SIZE_REPOSITORY_PATH = 30;

const asn1SccPusUInt32 pus_ST23_MAX_SIZE_REPOSITORY_DOMAIN = 30;

const asn1SccPusUInt32 pus_ST23_MAX_SIZE_FILE = 1000;

const asn1SccPusSt01FailureCode pus_ST01_NO_ERROR = 0;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_APID_UNAVAILABLE = 1;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_SERVICE_UNAVAILABLE = 2;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_SUBTYPE_UNAVAILABLE = 3;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_APID_UNKNOWN = 4;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_SERVICE_UNKNOWN = 5;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_SUBTYPE_UNKNOWN = 6;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_WRONG_FORMAT = 7;

const asn1SccPusSt01FailureCode pus_ST01_ERROR_CHECKSUM = 8;

const asn1SccPusSt03HousekeepingReportId pus_ST03_DEFAULT_HK_REPORT = 0;
