# H2020 ESROCOS Project
# Company: GMV Aerospace & Defence S.A.U.
# Licence: GPLv2

from PySide2 import QtGui, QtCore, QtWidgets

from .Ui.Ui_MainView import Ui_MainView
from PusGui.Utilities import DigitalClock


class MainView:
    """
    This class represents a window. It references the class
    Ui_MainView, that class is where the graphical interface
    is created
    """

    def __init__(self):
        """
        This is the constructor of the class
        """
        self.view = QtWidgets.QMainWindow()
        self.window = Ui_MainView()
        self.window.setupUi(self.view)
        self.spacecraftTimeValue = DigitalClock(0, self.window.statusTab)
        self.system_params = dict()
        self.system_params_2 = dict()
        self.system_params_Added = dict()
        self.system_params_Added_2 = dict()
        self.extra_customization()
        self.window.centralwidget.resizeEvent = self.resize_elements

    def get_window(self):
        """
        This method returns the view that this class references

        :return: A view. It could be a QWidget, QMainWindow, etc.
        """
        return self.view

    def extra_customization(self):
        """
        This method allow us to define an extra configuration for the
        view without having to touch the code generated by the QtDesigner
        giving us a extra level of abstraction
        """
        header = self.window.packagesTable.horizontalHeader()
        header.setSectionResizeMode(0, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(1, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(2, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(3, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(4, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(5, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(6, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(7, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(8, QtWidgets.QHeaderView.ResizeToContents)
        header.setSectionResizeMode(9, QtWidgets.QHeaderView.ResizeToContents)
        self.window.packagesTable.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.view.setStyleSheet("background-color: white")
        self.window.menubar.setStyleSheet("background: 3c3b37")
        # self.window.label.setText(
        #     QtGui.QApplication.translate("MainView", "<html><head/><body><p>"
        #                                              "<img src=\"Views/Views_Ui/images/logo_gmv.svg\""
        #                                              "width=\"60\" height=\"35\"/></p></body></html>",
        #                                  None, QtGui.QApplication.UnicodeUTF8))
        header.sortIndicatorOrder()
        self.window.packagesTable.verticalHeader().setVisible(False)
        self.window.packagesTable.sortByColumn(0, QtCore.Qt.AscendingOrder)
        sctv_h = self.window.spacecraftTimeLbl.frameGeometry().height()
        sctv_w = self.window.spacecraftTimeLbl.frameGeometry().width()
        sctv_x = self.window.spacecraftTimeLbl.pos().x() + sctv_w + 10
        sctv_y = self.window.spacecraftTimeLbl.pos().y()
        self.spacecraftTimeValue.setGeometry(QtCore.QRect(sctv_x, sctv_y, sctv_w, sctv_h))
        self.spacecraftTimeValue.setText("")
        self.spacecraftTimeValue.setObjectName("spacecraftTimeValue")

    def resize_elements(self, event):
        """
        This method defines all the instructions needed to make
        our CreateTCView window responsive

        :param event: The event that triggers this method
        """
        padding = 10
        tw_w = self.window.packagesTable.frameGeometry().width()
        tw_h = self.window.packagesTable.frameGeometry().height()
        tw_x = self.window.packagesTable.pos().x()
        tw_y = self.window.packagesTable.pos().y()

        img_w = self.window.label.frameGeometry().width()
        img_h = self.window.label.frameGeometry().height()
        img_x = self.window.label.pos().x()
        img_y = self.window.label.pos().y()

        self.window.tabWidget.resize(self.window.centralwidget.frameGeometry().width() - 2*padding,
                                     self.window.centralwidget.frameGeometry().height() - 2*padding)
        self.window.label.move(self.window.centralwidget.frameGeometry().width() - img_w - 3*padding, img_y)

    def __add_system_params__(self, reportId, name: str):
        if name not in self.system_params:
            obj = QtWidgets.QListWidgetItem()
            obj.setHidden(True)
            if reportId == 0:
                self.window.hkParamList.addItem(obj)
            else:
                self.window.sysParamsList.addItem(obj)
            self.system_params[name] = obj

    def __add_system_params_2__(self, reportId, name: str):
        if name not in self.system_params_2:
            obj = QtWidgets.QListWidgetItem()
            obj.setHidden(True)
            if reportId == 0:
                self.window.hkParamList_4.addItem(obj)
            else:
                self.window.sysParamsList_4.addItem(obj)
            self.system_params_2[name] = obj

    def update_space_time(self, val):
        if val is not None:
            self.spacecraftTimeValue.setVisible(True)
            self.spacecraftTimeValue.setText(val)

    def update_system_params(self, apid, reportId: int, idx: str, val):
        if apid == 0:
            self.__add_system_params__(reportId, idx)  # The param is added if it is not already
            if val is not None:
                self.system_params[idx].setHidden(False)
                try:
                    self.system_params[idx].setText("{}: {} - {}".format(idx, val, hex(val)))
                except Exception as _:
                    try:
                        self.system_params[idx].setText("{}: {:.3f}".format(idx, val))
                    except Exception as _:
                        self.system_params[idx].setText("{}: {}".format(idx, val))
        else:
            self.__add_system_params_2__(reportId, idx)  # The param is added if it is not already
            if val is not None:
                self.system_params_2[idx].setHidden(False)
                try:
                    self.system_params_2[idx].setText("{}: {} - {}".format(idx, val, hex(val)))
                except Exception as _:
                    try:
                        self.system_params_2[idx].setText("{}: {:.3f}".format(idx, val))
                    except Exception as _:
                        self.system_params_2[idx].setText("{}: {}".format(idx, val))

    def set_close_event(self, func):
        self.view.closeEvent = func

    def show(self):
        """
        This method calls to the .show_() method of the view referenced
        by this class.
        """
        return self.view.show()
