/*
Code automatically generated by asn1scc tool
*/
#include <limits.h>
#include <string.h>
#include <math.h>
#include "Context-onboardapid.h"


const asn1SccContext_onboardapid onboardapid_ctxt = {
    .apid = 2
};


flag asn1SccContext_onboardapid_Equal(const asn1SccContext_onboardapid* pVal1, const asn1SccContext_onboardapid* pVal2)
{
	flag ret=TRUE;

    ret = (pVal1->apid == pVal2->apid);

	return ret;

}

void asn1SccContext_onboardapid_Initialize(asn1SccContext_onboardapid* pVal)
{


	/*set apid */
	asn1SccPusApid_Initialize((&(pVal->apid)));
}

flag asn1SccContext_onboardapid_IsConstraintValid(const asn1SccContext_onboardapid *pVal, int* pErrCode)
{
    flag ret = TRUE;
	
    ret = (pVal->apid <= 2047UL);
    *pErrCode = ret ? 0 :  ERR_CONTEXT_ONBOARDAPID_APID;

	return ret;
}

