#ifndef __PRINTTYPES_H__
#define __PRINTTYPES_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintT_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintPusSequenceCount(const char *paramName, const asn1SccPusSequenceCount *pData);
void PrintPusPacket(const char *paramName, const asn1SccPusPacket *pData);
void PrintPusTC_11_4_Data(const char *paramName, const asn1SccPusTC_11_4_Data *pData);
void PrintPusTM_9_2_Data(const char *paramName, const asn1SccPusTM_9_2_Data *pData);
void PrintPusSecondaryHeaderFlag(const char *paramName, const asn1SccPusSecondaryHeaderFlag *pData);
void PrintPusTM_5_X_Data(const char *paramName, const asn1SccPusTM_5_X_Data *pData);
void PrintPusSt20StoredParam(const char *paramName, const asn1SccPusSt20StoredParam *pData);
void PrintPusSt18ObcpId(const char *paramName, const asn1SccPusSt18ObcpId *pData);
void PrintPusTC_18_1_Data(const char *paramName, const asn1SccPusTC_18_1_Data *pData);
void PrintPusTime(const char *paramName, const asn1SccPusTime *pData);
void PrintPusTmHeader(const char *paramName, const asn1SccPusTmHeader *pData);
void PrintPusTcScheduledActivity(const char *paramName, const asn1SccPusTcScheduledActivity *pData);
void PrintPusApid(const char *paramName, const asn1SccPusApid *pData);
void PrintPusSt03ParameterId(const char *paramName, const asn1SccPusSt03ParameterId *pData);
void PrintPusUInt3(const char *paramName, const asn1SccPusUInt3 *pData);
void PrintPusTC_18_4_5_Data(const char *paramName, const asn1SccPusTC_18_4_5_Data *pData);
void PrintPusServiceType(const char *paramName, const asn1SccPusServiceType *pData);
void PrintPusSt01RequestId(const char *paramName, const asn1SccPusSt01RequestId *pData);
void PrintPusSt23FileName(const char *paramName, const asn1SccPusSt23FileName *pData);
void PrintPusInt32(const char *paramName, const asn1SccPusInt32 *pData);
void PrintPusSt01FailureCode(const char *paramName, const asn1SccPusSt01FailureCode *pData);
void PrintPusTcApplicationDataReduced(const char *paramName, const asn1SccPusTcApplicationDataReduced *pData);
void PrintPusSt18ObcpChecksum(const char *paramName, const asn1SccPusSt18ObcpChecksum *pData);
void PrintPusUInt14(const char *paramName, const asn1SccPusUInt14 *pData);
void PrintPusTcHeader(const char *paramName, const asn1SccPusTcHeader *pData);
void PrintPusTC_12_1_2_Data(const char *paramName, const asn1SccPusTC_12_1_2_Data *pData);
void PrintPusVersionNumber(const char *paramName, const asn1SccPusVersionNumber *pData);
void PrintPusTmHeaderData(const char *paramName, const asn1SccPusTmHeaderData *pData);
void PrintPusTC_19_1_Data(const char *paramName, const asn1SccPusTC_19_1_Data *pData);
void PrintTASTE_Boolean(const char *paramName, const asn1SccTASTE_Boolean *pData);
void PrintPusPacketVersion(const char *paramName, const asn1SccPusPacketVersion *pData);
void PrintPusUInt32(const char *paramName, const asn1SccPusUInt32 *pData);
void PrintPusSubserviceType(const char *paramName, const asn1SccPusSubserviceType *pData);
void PrintPusSt18ObservabilityLevel(const char *paramName, const asn1SccPusSt18ObservabilityLevel *pData);
void PrintPusTC_23_2_3_Data(const char *paramName, const asn1SccPusTC_23_2_3_Data *pData);
void PrintPusSt09ExponentialRate(const char *paramName, const asn1SccPusSt09ExponentialRate *pData);
void PrintPusTC_23_14_Data(const char *paramName, const asn1SccPusTC_23_14_Data *pData);
void PrintPusSt12pmonId(const char *paramName, const asn1SccPusSt12pmonId *pData);
void PrintT_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintPusSt03ParameterArray(const char *paramName, const asn1SccPusSt03ParameterArray *pData);
void PrintPusSt20OnBoardParameterId(const char *paramName, const asn1SccPusSt20OnBoardParameterId *pData);
void PrintPusSt23RepositoryDomain(const char *paramName, const asn1SccPusSt23RepositoryDomain *pData);
void PrintPusSt05Event(const char *paramName, const asn1SccPusSt05Event *pData);
void PrintPusSt05EventId(const char *paramName, const asn1SccPusSt05EventId *pData);
void PrintPusSt03HousekeepingReportId(const char *paramName, const asn1SccPusSt03HousekeepingReportId *pData);
void PrintPusMessageTypeCounter(const char *paramName, const asn1SccPusMessageTypeCounter *pData);
void PrintT_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintPusPacketData(const char *paramName, const asn1SccPusPacketData *pData);
void PrintPusTcApplicationData(const char *paramName, const asn1SccPusTcApplicationData *pData);
void PrintPusMemAddr(const char *paramName, const asn1SccPusMemAddr *pData);
void PrintPusTC_18_13_Data(const char *paramName, const asn1SccPusTC_18_13_Data *pData);
void PrintPusTM_1_X_Data(const char *paramName, const asn1SccPusTM_1_X_Data *pData);
void PrintPusTmSourceData(const char *paramName, const asn1SccPusTmSourceData *pData);
void PrintPusSt01Failure(const char *paramName, const asn1SccPusSt01Failure *pData);
void PrintPusSt01FailureInfo(const char *paramName, const asn1SccPusSt01FailureInfo *pData);
void PrintPusTM_3_25_Data(const char *paramName, const asn1SccPusTM_3_25_Data *pData);
void PrintPusTC_18_3_Data(const char *paramName, const asn1SccPusTC_18_3_Data *pData);
void PrintPusTC_8_1_Data(const char *paramName, const asn1SccPusTC_8_1_Data *pData);
void PrintPusConfigDummyType(const char *paramName, const asn1SccPusConfigDummyType *pData);
void PrintPusUInt16(const char *paramName, const asn1SccPusUInt16 *pData);
void PrintPusTC_19_X_Data(const char *paramName, const asn1SccPusTC_19_X_Data *pData);
void PrintPusUInt11(const char *paramName, const asn1SccPusUInt11 *pData);
void PrintPusUInt8(const char *paramName, const asn1SccPusUInt8 *pData);
void PrintPusTimeReferenceStatus(const char *paramName, const asn1SccPusTimeReferenceStatus *pData);
void PrintPusSt18ObcpCode(const char *paramName, const asn1SccPusSt18ObcpCode *pData);
void PrintPusSt05EventAuxData(const char *paramName, const asn1SccPusSt05EventAuxData *pData);
void PrintT_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintPusPacketReduced(const char *paramName, const asn1SccPusPacketReduced *pData);
void PrintPusUInt64(const char *paramName, const asn1SccPusUInt64 *pData);
void PrintPusSt23RepositoryPath(const char *paramName, const asn1SccPusSt23RepositoryPath *pData);
void PrintPusInt64(const char *paramName, const asn1SccPusInt64 *pData);
void PrintT_Boolean(const char *paramName, const asn1SccT_Boolean *pData);
void PrintPusChecksum(const char *paramName, const asn1SccPusChecksum *pData);
void PrintPusSequenceFlags(const char *paramName, const asn1SccPusSequenceFlags *pData);
void PrintPusTC_18_2_6_12_Data(const char *paramName, const asn1SccPusTC_18_2_6_12_Data *pData);
void PrintPusStepId(const char *paramName, const asn1SccPusStepId *pData);
void PrintPusTC_TM_23_1_4_Data(const char *paramName, const asn1SccPusTC_TM_23_1_4_Data *pData);
void PrintPusPacketDataLength(const char *paramName, const asn1SccPusPacketDataLength *pData);
void PrintPusTC_TM_20_X_Data(const char *paramName, const asn1SccPusTC_TM_20_X_Data *pData);
void PrintPusPacketDataReduced(const char *paramName, const asn1SccPusPacketDataReduced *pData);
void PrintPusTC_9_1_Data(const char *paramName, const asn1SccPusTC_9_1_Data *pData);
void PrintPusUInt4(const char *paramName, const asn1SccPusUInt4 *pData);
void PrintPusPacketType(const char *paramName, const asn1SccPusPacketType *pData);
void PrintPusSt08FunctionId(const char *paramName, const asn1SccPusSt08FunctionId *pData);
void PrintPusSt03StoredParam(const char *paramName, const asn1SccPusSt03StoredParam *pData);
void PrintPusAcknowledgementFlags(const char *paramName, const asn1SccPusAcknowledgementFlags *pData);

#ifdef __cplusplus
}
#endif

#endif
