#ifndef __OCARINA_GENERATED_ACTIVITY_H_
#define __OCARINA_GENERATED_ACTIVITY_H_ 
#include <request.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

void tcdispatch_deliver 
    (__po_hi_request_t* request);

void* tcdispatch_job (void);

void tmdispatch_deliver 
    (__po_hi_request_t* request);

void* tmdispatch_job (void);

void st05_deliver 
    (__po_hi_request_t* request);

void* st05_job (void);

void st03_deliver 
    (__po_hi_request_t* request);

void* st03_job (void);

void* onboardsoftware_job (void);

void vt_ground_newtm_deliver 
    (__po_hi_request_t* request);

void* vt_ground_newtm_job (void);

void vt_ground_triggertmgui_deliver 
    (__po_hi_request_t* request);

void* vt_ground_triggertmgui_job (void);

void vt_tcqueue_newtc_deliver 
    (__po_hi_request_t* request);

void* vt_tcqueue_newtc_job (void);

void vt_events_debugeventstrigger_deliver 
    (__po_hi_request_t* request);

void* vt_events_debugeventstrigger_job (void);

void vt_st19_eventactiontrigger_deliver 
    (__po_hi_request_t* request);

void* vt_st19_eventactiontrigger_job (void);

void vt_st12_pmontrigger_deliver 
    (__po_hi_request_t* request);

void* vt_st12_pmontrigger_job (void);

void vt_trigger_hkreporttrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_hkreporttrigger_job (void);

void vt_trigger_tmdispatchtrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_tmdispatchtrigger_job (void);

void vt_trigger_eventactiontrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_eventactiontrigger_job (void);

void vt_trigger_tcdispatchtrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_tcdispatchtrigger_job (void);

void vt_trigger_pmontrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_pmontrigger_job (void);

void vt_trigger_eventreporttrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_eventreporttrigger_job (void);

void vt_trigger_debugeventtrigger_deliver 
    (__po_hi_request_t* request);

void* vt_trigger_debugeventtrigger_job (void);

void __po_hi_main_deliver 
    (__po_hi_request_t* request);

#endif
