#include <types.h>
#include <po_hi_gqueue.h>
#include <deployment.h>
#include <po_hi_types.h>
#include <request.h>
#include <po_hi_task.h>
#include <activity.h>
#include <po_hi_main.h>
#include <po_hi_time.h>
#include <po_hi_transport.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object ground_protected;
extern process_package__taste_protected_object tcqueue_protected;
extern process_package__taste_protected_object tmqueue_protected;
extern process_package__taste_protected_object st17_protected;
extern process_package__taste_protected_object st01_protected;
extern process_package__taste_protected_object st08_protected;
extern process_package__taste_protected_object onboardapid_protected;
extern process_package__taste_protected_object st09_protected;
extern process_package__taste_protected_object timereportapid_protected;
extern process_package__taste_protected_object events_protected;
extern process_package__taste_protected_object st19_protected;
extern process_package__taste_protected_object housekeeping_protected;
extern process_package__taste_protected_object st12_protected;
extern process_package__taste_protected_object st11_protected;
extern process_package__taste_protected_object st18_protected;
extern process_package__taste_protected_object obcpengine_protected;
extern process_package__taste_protected_object st23_protected;
extern process_package__taste_protected_object filemanagement_protected;
extern process_package__taste_protected_object st20_protected;
extern process_package__taste_protected_object onboardparams_protected;
extern process_package__taste_protected_object trigger_protected;
__po_hi_port_t __po_hi_tcdispatch_outport_newtc_vt_local_destinations[1] = {vt_tcqueue_newtc_global_inport_artificial_newtc};
__po_hi_port_id_t __po_hi_tcdispatch_woffsets[__po_hi_tcdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tcdispatch_offsets[__po_hi_tcdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tcdispatch_used_size[__po_hi_tcdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tcdispatch_empties[__po_hi_tcdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tcdispatch_first[__po_hi_tcdispatch_nb_ports];
__po_hi_request_t __po_hi_tcdispatch_recent[__po_hi_tcdispatch_nb_ports];
__po_hi_port_t __po_hi_tcdispatch_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_tcdispatch_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_tcdispatch_history[1];
__po_hi_port_id_t __po_hi_tcdispatch_n_dest[__po_hi_tcdispatch_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_tcdispatch_fifo_size[__po_hi_tcdispatch_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_tcdispatch_destinations[__po_hi_tcdispatch_nb_ports] = {NULL,__po_hi_tcdispatch_outport_newtc_vt_local_destinations};

/*!
 * \fn void tcdispatch_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task tcdispatch
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (tcdispatch_deliver) stores the incoming request for the tasktcdispatch
 */
void tcdispatch_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case tcdispatch_global_inport_tctrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_tcdispatch_k, tcdispatch_local_inport_tctrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* tcdispatch_job (void)
 * \brief Function executed by the task tcdispatch
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : tcdispatch*/
extern void po_hi_c_tcdispatch_tctrigger 
    (__po_hi_task_id self);
void* tcdispatch_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_tcdispatch_k, __po_hi_tcdispatch_nb_ports, __po_hi_tcdispatch_queue, __po_hi_tcdispatch_fifo_size, __po_hi_tcdispatch_first, __po_hi_tcdispatch_offsets, __po_hi_tcdispatch_woffsets, __po_hi_tcdispatch_n_dest, __po_hi_tcdispatch_destinations, __po_hi_tcdispatch_used_size, __po_hi_tcdispatch_history, __po_hi_tcdispatch_recent, __po_hi_tcdispatch_empties, __po_hi_tcdispatch_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_tcdispatch_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_tcdispatch_k, &(port));
    __po_hi_compute_next_period (x86_partition_tcdispatch_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case tcdispatch_local_inport_tctrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_tcdispatch_k, tcdispatch_local_inport_tctrigger);

        po_hi_c_tcdispatch_tctrigger (x86_partition_tcdispatch_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_tcdispatch_k, tcdispatch_global_outport_newtc_vt);
    __po_hi_wait_for_next_period (x86_partition_tcdispatch_k);
  }
}

__po_hi_port_t __po_hi_tmdispatch_outport_newtm_local_destinations[1] = {vt_ground_newtm_global_inport_artificial_newtm};
__po_hi_port_id_t __po_hi_tmdispatch_woffsets[__po_hi_tmdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tmdispatch_offsets[__po_hi_tmdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tmdispatch_used_size[__po_hi_tmdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tmdispatch_empties[__po_hi_tmdispatch_nb_ports];
__po_hi_port_id_t __po_hi_tmdispatch_first[__po_hi_tmdispatch_nb_ports];
__po_hi_request_t __po_hi_tmdispatch_recent[__po_hi_tmdispatch_nb_ports];
__po_hi_port_t __po_hi_tmdispatch_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_tmdispatch_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_tmdispatch_history[1];
__po_hi_port_id_t __po_hi_tmdispatch_n_dest[__po_hi_tmdispatch_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_tmdispatch_fifo_size[__po_hi_tmdispatch_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_tmdispatch_destinations[__po_hi_tmdispatch_nb_ports] = {NULL,__po_hi_tmdispatch_outport_newtm_local_destinations};

/*!
 * \fn void tmdispatch_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task tmdispatch
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (tmdispatch_deliver) stores the incoming request for the tasktmdispatch
 */
void tmdispatch_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case tmdispatch_global_inport_tmtrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_tmdispatch_k, tmdispatch_local_inport_tmtrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* tmdispatch_job (void)
 * \brief Function executed by the task tmdispatch
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : tmdispatch*/
extern void po_hi_c_tmdispatch_tmtrigger 
    (__po_hi_task_id self);
void* tmdispatch_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_tmdispatch_k, __po_hi_tmdispatch_nb_ports, __po_hi_tmdispatch_queue, __po_hi_tmdispatch_fifo_size, __po_hi_tmdispatch_first, __po_hi_tmdispatch_offsets, __po_hi_tmdispatch_woffsets, __po_hi_tmdispatch_n_dest, __po_hi_tmdispatch_destinations, __po_hi_tmdispatch_used_size, __po_hi_tmdispatch_history, __po_hi_tmdispatch_recent, __po_hi_tmdispatch_empties, __po_hi_tmdispatch_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_tmdispatch_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_tmdispatch_k, &(port));
    __po_hi_compute_next_period (x86_partition_tmdispatch_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case tmdispatch_local_inport_tmtrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_tmdispatch_k, tmdispatch_local_inport_tmtrigger);

        po_hi_c_tmdispatch_tmtrigger (x86_partition_tmdispatch_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_tmdispatch_k, tmdispatch_global_outport_newtm);
    __po_hi_wait_for_next_period (x86_partition_tmdispatch_k);
  }
}

__po_hi_port_id_t __po_hi_st05_woffsets[__po_hi_st05_nb_ports];
__po_hi_port_id_t __po_hi_st05_offsets[__po_hi_st05_nb_ports];
__po_hi_port_id_t __po_hi_st05_used_size[__po_hi_st05_nb_ports];
__po_hi_port_id_t __po_hi_st05_empties[__po_hi_st05_nb_ports];
__po_hi_port_id_t __po_hi_st05_first[__po_hi_st05_nb_ports];
__po_hi_request_t __po_hi_st05_recent[__po_hi_st05_nb_ports];
__po_hi_port_t __po_hi_st05_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_st05_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_st05_history[1];
__po_hi_port_id_t __po_hi_st05_n_dest[__po_hi_st05_nb_ports] = {0};
__po_hi_port_id_t __po_hi_st05_fifo_size[__po_hi_st05_nb_ports] = {1};
__po_hi_port_t* __po_hi_st05_destinations[__po_hi_st05_nb_ports] = {NULL};

/*!
 * \fn void st05_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task st05
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (st05_deliver) stores the incoming request for the taskst05
 */
void st05_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case st05_global_inport_eventreporttrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_st05_k, st05_local_inport_eventreporttrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* st05_job (void)
 * \brief Function executed by the task st05
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : st05*/
extern void po_hi_c_st05_eventreporttrigger 
    (__po_hi_task_id self);
void* st05_job (void)
{
  __po_hi_local_port_t port;

  __po_hi_gqueue_init (x86_partition_st05_k, __po_hi_st05_nb_ports, __po_hi_st05_queue, __po_hi_st05_fifo_size, __po_hi_st05_first, __po_hi_st05_offsets, __po_hi_st05_woffsets, __po_hi_st05_n_dest, __po_hi_st05_destinations, __po_hi_st05_used_size, __po_hi_st05_history, __po_hi_st05_recent, __po_hi_st05_empties, __po_hi_st05_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_st05_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_st05_k, &(port));
    __po_hi_compute_next_period (x86_partition_st05_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case st05_local_inport_eventreporttrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_st05_k, st05_local_inport_eventreporttrigger);

        po_hi_c_st05_eventreporttrigger (x86_partition_st05_k);

        break;
      }
      default:
      {
        break;
      }
    }
    __po_hi_wait_for_next_period (x86_partition_st05_k);
  }
}

__po_hi_port_id_t __po_hi_st03_woffsets[__po_hi_st03_nb_ports];
__po_hi_port_id_t __po_hi_st03_offsets[__po_hi_st03_nb_ports];
__po_hi_port_id_t __po_hi_st03_used_size[__po_hi_st03_nb_ports];
__po_hi_port_id_t __po_hi_st03_empties[__po_hi_st03_nb_ports];
__po_hi_port_id_t __po_hi_st03_first[__po_hi_st03_nb_ports];
__po_hi_request_t __po_hi_st03_recent[__po_hi_st03_nb_ports];
__po_hi_port_t __po_hi_st03_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_st03_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_st03_history[1];
__po_hi_port_id_t __po_hi_st03_n_dest[__po_hi_st03_nb_ports] = {0};
__po_hi_port_id_t __po_hi_st03_fifo_size[__po_hi_st03_nb_ports] = {1};
__po_hi_port_t* __po_hi_st03_destinations[__po_hi_st03_nb_ports] = {NULL};

/*!
 * \fn void st03_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task st03
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (st03_deliver) stores the incoming request for the taskst03
 */
void st03_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case st03_global_inport_hkreporttrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_st03_k, st03_local_inport_hkreporttrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* st03_job (void)
 * \brief Function executed by the task st03
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : st03*/
extern void po_hi_c_st03_hkreporttrigger 
    (__po_hi_task_id self);
void* st03_job (void)
{
  __po_hi_local_port_t port;

  __po_hi_gqueue_init (x86_partition_st03_k, __po_hi_st03_nb_ports, __po_hi_st03_queue, __po_hi_st03_fifo_size, __po_hi_st03_first, __po_hi_st03_offsets, __po_hi_st03_woffsets, __po_hi_st03_n_dest, __po_hi_st03_destinations, __po_hi_st03_used_size, __po_hi_st03_history, __po_hi_st03_recent, __po_hi_st03_empties, __po_hi_st03_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_st03_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_st03_k, &(port));
    __po_hi_compute_next_period (x86_partition_st03_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case st03_local_inport_hkreporttrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_st03_k, st03_local_inport_hkreporttrigger);

        po_hi_c_st03_hkreporttrigger (x86_partition_st03_k);

        break;
      }
      default:
      {
        break;
      }
    }
    __po_hi_wait_for_next_period (x86_partition_st03_k);
  }
}


/*!
 * \fn void* onboardsoftware_job (void)
 * \brief Function executed by the task onboardsoftware
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : onboardsoftware*/
extern void po_hi_c_onboardsoftware_debugtrigger 
    (__po_hi_task_id self);
void* onboardsoftware_job (void)
{

  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_onboardsoftware_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_onboardsoftware_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_onboardsoftware_debugtrigger (x86_partition_onboardsoftware_k);
    __po_hi_wait_for_next_period (x86_partition_onboardsoftware_k);
  }
}

__po_hi_port_t __po_hi_vt_ground_newtm_outport_newtc_vt_local_destinations[1] = {vt_tcqueue_newtc_global_inport_artificial_newtc};
__po_hi_port_id_t __po_hi_vt_ground_newtm_woffsets[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_newtm_offsets[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_newtm_used_size[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_newtm_empties[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_newtm_first[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_request_t __po_hi_vt_ground_newtm_recent[__po_hi_vt_ground_newtm_nb_ports];
__po_hi_port_t __po_hi_vt_ground_newtm_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_ground_newtm_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_ground_newtm_history[1];
__po_hi_port_id_t __po_hi_vt_ground_newtm_n_dest[__po_hi_vt_ground_newtm_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_ground_newtm_fifo_size[__po_hi_vt_ground_newtm_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_ground_newtm_destinations[__po_hi_vt_ground_newtm_nb_ports] = {NULL,__po_hi_vt_ground_newtm_outport_newtc_vt_local_destinations};

/*!
 * \fn void vt_ground_newtm_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_ground_newtm
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_ground_newtm_deliver) stores the incoming request for the 
 * taskvt_ground_newtm
 */
void vt_ground_newtm_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_ground_newtm_global_inport_artificial_newtm:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_ground_newtm_k, vt_ground_newtm_local_inport_artificial_newtm, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_ground_newtm_job (void)
 * \brief Function executed by the task vt_ground_newtm
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_ground_newtm*/
extern void po_hi_c_vt_ground_newtm_artificial_newtm 
    (__po_hi_task_id self,
    dataview__puspacket_buffer_impl inport_artificial_newtm);
void* vt_ground_newtm_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_newtm_request;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_ground_newtm_k, __po_hi_vt_ground_newtm_nb_ports, __po_hi_vt_ground_newtm_queue, __po_hi_vt_ground_newtm_fifo_size, __po_hi_vt_ground_newtm_first, __po_hi_vt_ground_newtm_offsets, __po_hi_vt_ground_newtm_woffsets, __po_hi_vt_ground_newtm_n_dest, __po_hi_vt_ground_newtm_destinations, __po_hi_vt_ground_newtm_used_size, __po_hi_vt_ground_newtm_history, __po_hi_vt_ground_newtm_recent, __po_hi_vt_ground_newtm_empties, __po_hi_vt_ground_newtm_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_ground_newtm_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_ground_newtm_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_ground_newtm_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_ground_newtm_local_inport_artificial_newtm:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (x86_partition_vt_ground_newtm_k, vt_ground_newtm_local_inport_artificial_newtm))
        {
                  __po_hi_gqueue_get_value (x86_partition_vt_ground_newtm_k, vt_ground_newtm_local_inport_artificial_newtm, &(inport_artificial_newtm_request));
          __po_hi_gqueue_next_value (x86_partition_vt_ground_newtm_k, vt_ground_newtm_local_inport_artificial_newtm);

        }

        po_hi_c_vt_ground_newtm_artificial_newtm (x86_partition_vt_ground_newtm_k, inport_artificial_newtm_request.vars.vt_ground_newtm_global_inport_artificial_newtm.vt_ground_newtm_global_inport_artificial_newtm);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_ground_newtm_k, vt_ground_newtm_global_outport_newtc_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_ground_newtm_k);
  }
}

__po_hi_port_t __po_hi_vt_ground_triggertmgui_outport_newtc_vt_local_destinations[1] = {vt_tcqueue_newtc_global_inport_artificial_newtc};
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_woffsets[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_offsets[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_used_size[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_empties[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_first[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_request_t __po_hi_vt_ground_triggertmgui_recent[__po_hi_vt_ground_triggertmgui_nb_ports];
__po_hi_port_t __po_hi_vt_ground_triggertmgui_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_ground_triggertmgui_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_ground_triggertmgui_history[0];
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_n_dest[__po_hi_vt_ground_triggertmgui_nb_ports] = {1};
__po_hi_port_id_t __po_hi_vt_ground_triggertmgui_fifo_size[__po_hi_vt_ground_triggertmgui_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_ground_triggertmgui_destinations[__po_hi_vt_ground_triggertmgui_nb_ports] = {__po_hi_vt_ground_triggertmgui_outport_newtc_vt_local_destinations};

/*!
 * \fn void* vt_ground_triggertmgui_job (void)
 * \brief Function executed by the task vt_ground_triggertmgui
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_ground_triggertmgui*/
extern void po_hi_c_vt_ground_triggertmgui_artificial_triggertmgui 
    (__po_hi_task_id self);
void* vt_ground_triggertmgui_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_ground_triggertmgui_k, __po_hi_vt_ground_triggertmgui_nb_ports, __po_hi_vt_ground_triggertmgui_queue, __po_hi_vt_ground_triggertmgui_fifo_size, __po_hi_vt_ground_triggertmgui_first, __po_hi_vt_ground_triggertmgui_offsets, __po_hi_vt_ground_triggertmgui_woffsets, __po_hi_vt_ground_triggertmgui_n_dest, __po_hi_vt_ground_triggertmgui_destinations, __po_hi_vt_ground_triggertmgui_used_size, __po_hi_vt_ground_triggertmgui_history, __po_hi_vt_ground_triggertmgui_recent, __po_hi_vt_ground_triggertmgui_empties, __po_hi_vt_ground_triggertmgui_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_ground_triggertmgui_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_ground_triggertmgui_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_ground_triggertmgui_artificial_triggertmgui (x86_partition_vt_ground_triggertmgui_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_ground_triggertmgui_k, vt_ground_triggertmgui_global_outport_newtc_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_ground_triggertmgui_k);
  }
}

__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_woffsets[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_offsets[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_used_size[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_empties[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_first[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_request_t __po_hi_vt_tcqueue_newtc_recent[__po_hi_vt_tcqueue_newtc_nb_ports];
__po_hi_port_t __po_hi_vt_tcqueue_newtc_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_tcqueue_newtc_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_tcqueue_newtc_history[1];
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_n_dest[__po_hi_vt_tcqueue_newtc_nb_ports] = {0};
__po_hi_port_id_t __po_hi_vt_tcqueue_newtc_fifo_size[__po_hi_vt_tcqueue_newtc_nb_ports] = {1};
__po_hi_port_t* __po_hi_vt_tcqueue_newtc_destinations[__po_hi_vt_tcqueue_newtc_nb_ports] = {NULL};

/*!
 * \fn void vt_tcqueue_newtc_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_tcqueue_newtc
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_tcqueue_newtc_deliver) stores the incoming request for the 
 * taskvt_tcqueue_newtc
 */
void vt_tcqueue_newtc_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_tcqueue_newtc_global_inport_artificial_newtc:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_tcqueue_newtc_k, vt_tcqueue_newtc_local_inport_artificial_newtc, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_tcqueue_newtc_job (void)
 * \brief Function executed by the task vt_tcqueue_newtc
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_tcqueue_newtc*/
extern void po_hi_c_vt_tcqueue_newtc_artificial_newtc 
    (__po_hi_task_id self,
    dataview__puspacket_buffer_impl inport_artificial_newtc);
void* vt_tcqueue_newtc_job (void)
{
  __po_hi_local_port_t port;
  static __po_hi_request_t inport_artificial_newtc_request;

  __po_hi_gqueue_init (x86_partition_vt_tcqueue_newtc_k, __po_hi_vt_tcqueue_newtc_nb_ports, __po_hi_vt_tcqueue_newtc_queue, __po_hi_vt_tcqueue_newtc_fifo_size, __po_hi_vt_tcqueue_newtc_first, __po_hi_vt_tcqueue_newtc_offsets, __po_hi_vt_tcqueue_newtc_woffsets, __po_hi_vt_tcqueue_newtc_n_dest, __po_hi_vt_tcqueue_newtc_destinations, __po_hi_vt_tcqueue_newtc_used_size, __po_hi_vt_tcqueue_newtc_history, __po_hi_vt_tcqueue_newtc_recent, __po_hi_vt_tcqueue_newtc_empties, __po_hi_vt_tcqueue_newtc_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_tcqueue_newtc_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_tcqueue_newtc_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_tcqueue_newtc_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_tcqueue_newtc_local_inport_artificial_newtc:
      {
        /* :: Yes if commentary :: */if (__po_hi_gqueue_get_count (x86_partition_vt_tcqueue_newtc_k, vt_tcqueue_newtc_local_inport_artificial_newtc))
        {
                  __po_hi_gqueue_get_value (x86_partition_vt_tcqueue_newtc_k, vt_tcqueue_newtc_local_inport_artificial_newtc, &(inport_artificial_newtc_request));
          __po_hi_gqueue_next_value (x86_partition_vt_tcqueue_newtc_k, vt_tcqueue_newtc_local_inport_artificial_newtc);

        }

        po_hi_c_vt_tcqueue_newtc_artificial_newtc (x86_partition_vt_tcqueue_newtc_k, inport_artificial_newtc_request.vars.vt_tcqueue_newtc_global_inport_artificial_newtc.vt_tcqueue_newtc_global_inport_artificial_newtc);

        break;
      }
      default:
      {
        break;
      }
    }
    __po_hi_wait_for_next_period (x86_partition_vt_tcqueue_newtc_k);
  }
}

__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_woffsets[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_offsets[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_used_size[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_empties[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_first[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_request_t __po_hi_vt_events_debugeventstrigger_recent[__po_hi_vt_events_debugeventstrigger_nb_ports];
__po_hi_port_t __po_hi_vt_events_debugeventstrigger_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_events_debugeventstrigger_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_events_debugeventstrigger_history[1];
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_n_dest[__po_hi_vt_events_debugeventstrigger_nb_ports] = {0};
__po_hi_port_id_t __po_hi_vt_events_debugeventstrigger_fifo_size[__po_hi_vt_events_debugeventstrigger_nb_ports] = {1};
__po_hi_port_t* __po_hi_vt_events_debugeventstrigger_destinations[__po_hi_vt_events_debugeventstrigger_nb_ports] = {NULL};

/*!
 * \fn void vt_events_debugeventstrigger_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_events_debugeventstrigger
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_events_debugeventstrigger_deliver) stores the incoming request for the 
 * taskvt_events_debugeventstrigger
 */
void vt_events_debugeventstrigger_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_events_debugeventstrigger_k, vt_events_debugeventstrigger_local_inport_artificial_debugeventstrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_events_debugeventstrigger_job (void)
 * \brief Function executed by the task vt_events_debugeventstrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_events_debugeventstrigger*/
extern void po_hi_c_vt_events_debugeventstrigger_artificial_debugeventstrigger 
    (__po_hi_task_id self);
void* vt_events_debugeventstrigger_job (void)
{
  __po_hi_local_port_t port;

  __po_hi_gqueue_init (x86_partition_vt_events_debugeventstrigger_k, __po_hi_vt_events_debugeventstrigger_nb_ports, __po_hi_vt_events_debugeventstrigger_queue, __po_hi_vt_events_debugeventstrigger_fifo_size, __po_hi_vt_events_debugeventstrigger_first, __po_hi_vt_events_debugeventstrigger_offsets, __po_hi_vt_events_debugeventstrigger_woffsets, __po_hi_vt_events_debugeventstrigger_n_dest, __po_hi_vt_events_debugeventstrigger_destinations, __po_hi_vt_events_debugeventstrigger_used_size, __po_hi_vt_events_debugeventstrigger_history, __po_hi_vt_events_debugeventstrigger_recent, __po_hi_vt_events_debugeventstrigger_empties, __po_hi_vt_events_debugeventstrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_events_debugeventstrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_events_debugeventstrigger_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_events_debugeventstrigger_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_events_debugeventstrigger_local_inport_artificial_debugeventstrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_vt_events_debugeventstrigger_k, vt_events_debugeventstrigger_local_inport_artificial_debugeventstrigger);

        po_hi_c_vt_events_debugeventstrigger_artificial_debugeventstrigger (x86_partition_vt_events_debugeventstrigger_k);

        break;
      }
      default:
      {
        break;
      }
    }
    __po_hi_wait_for_next_period (x86_partition_vt_events_debugeventstrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_st19_eventactiontrigger_outport_newtc_vt_local_destinations[1] = {vt_tcqueue_newtc_global_inport_artificial_newtc};
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_woffsets[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_offsets[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_used_size[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_empties[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_first[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_request_t __po_hi_vt_st19_eventactiontrigger_recent[__po_hi_vt_st19_eventactiontrigger_nb_ports];
__po_hi_port_t __po_hi_vt_st19_eventactiontrigger_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_st19_eventactiontrigger_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_st19_eventactiontrigger_history[1];
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_n_dest[__po_hi_vt_st19_eventactiontrigger_nb_ports] = {0,1};
__po_hi_port_id_t __po_hi_vt_st19_eventactiontrigger_fifo_size[__po_hi_vt_st19_eventactiontrigger_nb_ports] = {1,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_st19_eventactiontrigger_destinations[__po_hi_vt_st19_eventactiontrigger_nb_ports] = {NULL,__po_hi_vt_st19_eventactiontrigger_outport_newtc_vt_local_destinations};

/*!
 * \fn void vt_st19_eventactiontrigger_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_st19_eventactiontrigger
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_st19_eventactiontrigger_deliver) stores the incoming request for the 
 * taskvt_st19_eventactiontrigger
 */
void vt_st19_eventactiontrigger_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_st19_eventactiontrigger_k, vt_st19_eventactiontrigger_local_inport_artificial_eventactiontrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_st19_eventactiontrigger_job (void)
 * \brief Function executed by the task vt_st19_eventactiontrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_st19_eventactiontrigger*/
extern void po_hi_c_vt_st19_eventactiontrigger_artificial_eventactiontrigger 
    (__po_hi_task_id self);
void* vt_st19_eventactiontrigger_job (void)
{
  __po_hi_local_port_t port;
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_st19_eventactiontrigger_k, __po_hi_vt_st19_eventactiontrigger_nb_ports, __po_hi_vt_st19_eventactiontrigger_queue, __po_hi_vt_st19_eventactiontrigger_fifo_size, __po_hi_vt_st19_eventactiontrigger_first, __po_hi_vt_st19_eventactiontrigger_offsets, __po_hi_vt_st19_eventactiontrigger_woffsets, __po_hi_vt_st19_eventactiontrigger_n_dest, __po_hi_vt_st19_eventactiontrigger_destinations, __po_hi_vt_st19_eventactiontrigger_used_size, __po_hi_vt_st19_eventactiontrigger_history, __po_hi_vt_st19_eventactiontrigger_recent, __po_hi_vt_st19_eventactiontrigger_empties, __po_hi_vt_st19_eventactiontrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_st19_eventactiontrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_st19_eventactiontrigger_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_st19_eventactiontrigger_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_st19_eventactiontrigger_local_inport_artificial_eventactiontrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_vt_st19_eventactiontrigger_k, vt_st19_eventactiontrigger_local_inport_artificial_eventactiontrigger);

        po_hi_c_vt_st19_eventactiontrigger_artificial_eventactiontrigger (x86_partition_vt_st19_eventactiontrigger_k);

        break;
      }
      default:
      {
        break;
      }
    }
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_st19_eventactiontrigger_k, vt_st19_eventactiontrigger_global_outport_newtc_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_st19_eventactiontrigger_k);
  }
}

__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_woffsets[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_offsets[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_used_size[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_empties[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_first[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_request_t __po_hi_vt_st12_pmontrigger_recent[__po_hi_vt_st12_pmontrigger_nb_ports];
__po_hi_port_t __po_hi_vt_st12_pmontrigger_queue[1 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_st12_pmontrigger_total_fifo_size = 1;
__po_hi_local_port_t __po_hi_vt_st12_pmontrigger_history[1];
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_n_dest[__po_hi_vt_st12_pmontrigger_nb_ports] = {0};
__po_hi_port_id_t __po_hi_vt_st12_pmontrigger_fifo_size[__po_hi_vt_st12_pmontrigger_nb_ports] = {1};
__po_hi_port_t* __po_hi_vt_st12_pmontrigger_destinations[__po_hi_vt_st12_pmontrigger_nb_ports] = {NULL};

/*!
 * \fn void vt_st12_pmontrigger_deliver (__po_hi_request_t* request)
 * \brief Function that delivers requests to the task vt_st12_pmontrigger
 *
 * When the generated application received a request, it calls a main delivery
 *  function that redirects to localfunctions for each task. This function 
 * (vt_st12_pmontrigger_deliver) stores the incoming request for the 
 * taskvt_st12_pmontrigger
 */
void vt_st12_pmontrigger_deliver 
    (__po_hi_request_t* request)
{

  switch (request->port)
  {
    case vt_st12_pmontrigger_global_inport_artificial_pmontrigger:
    {
      __po_hi_gqueue_store_in (x86_partition_vt_st12_pmontrigger_k, vt_st12_pmontrigger_local_inport_artificial_pmontrigger, request);

      break;
    }
    default:
    {
      break;
    }
  }
}


/*!
 * \fn void* vt_st12_pmontrigger_job (void)
 * \brief Function executed by the task vt_st12_pmontrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Sporadic task : vt_st12_pmontrigger*/
extern void po_hi_c_vt_st12_pmontrigger_artificial_pmontrigger 
    (__po_hi_task_id self);
void* vt_st12_pmontrigger_job (void)
{
  __po_hi_local_port_t port;

  __po_hi_gqueue_init (x86_partition_vt_st12_pmontrigger_k, __po_hi_vt_st12_pmontrigger_nb_ports, __po_hi_vt_st12_pmontrigger_queue, __po_hi_vt_st12_pmontrigger_fifo_size, __po_hi_vt_st12_pmontrigger_first, __po_hi_vt_st12_pmontrigger_offsets, __po_hi_vt_st12_pmontrigger_woffsets, __po_hi_vt_st12_pmontrigger_n_dest, __po_hi_vt_st12_pmontrigger_destinations, __po_hi_vt_st12_pmontrigger_used_size, __po_hi_vt_st12_pmontrigger_history, __po_hi_vt_st12_pmontrigger_recent, __po_hi_vt_st12_pmontrigger_empties, __po_hi_vt_st12_pmontrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_compute_next_period (x86_partition_vt_st12_pmontrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    __po_hi_gqueue_wait_for_incoming_event (x86_partition_vt_st12_pmontrigger_k, &(port));
    __po_hi_compute_next_period (x86_partition_vt_st12_pmontrigger_k);
    /*  Make_Ports_Compute_Entrypoint*/
    switch (port)
    {
      case vt_st12_pmontrigger_local_inport_artificial_pmontrigger:
      {
        __po_hi_gqueue_next_value (x86_partition_vt_st12_pmontrigger_k, vt_st12_pmontrigger_local_inport_artificial_pmontrigger);

        po_hi_c_vt_st12_pmontrigger_artificial_pmontrigger (x86_partition_vt_st12_pmontrigger_k);

        break;
      }
      default:
      {
        break;
      }
    }
    __po_hi_wait_for_next_period (x86_partition_vt_st12_pmontrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_woffsets[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_offsets[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_used_size[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_empties[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_first[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_hkreporttrigger_recent[__po_hi_vt_trigger_hkreporttrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_hkreporttrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_hkreporttrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_hkreporttrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_n_dest[__po_hi_vt_trigger_hkreporttrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_hkreporttrigger_fifo_size[__po_hi_vt_trigger_hkreporttrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_hkreporttrigger_destinations[__po_hi_vt_trigger_hkreporttrigger_nb_ports] = {__po_hi_vt_trigger_hkreporttrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_hkreporttrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_hkreporttrigger_job (void)
 * \brief Function executed by the task vt_trigger_hkreporttrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_hkreporttrigger*/
extern void po_hi_c_vt_trigger_hkreporttrigger_artificial_hkreporttrigger 
    (__po_hi_task_id self);
void* vt_trigger_hkreporttrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_hkreporttrigger_k, __po_hi_vt_trigger_hkreporttrigger_nb_ports, __po_hi_vt_trigger_hkreporttrigger_queue, __po_hi_vt_trigger_hkreporttrigger_fifo_size, __po_hi_vt_trigger_hkreporttrigger_first, __po_hi_vt_trigger_hkreporttrigger_offsets, __po_hi_vt_trigger_hkreporttrigger_woffsets, __po_hi_vt_trigger_hkreporttrigger_n_dest, __po_hi_vt_trigger_hkreporttrigger_destinations, __po_hi_vt_trigger_hkreporttrigger_used_size, __po_hi_vt_trigger_hkreporttrigger_history, __po_hi_vt_trigger_hkreporttrigger_recent, __po_hi_vt_trigger_hkreporttrigger_empties, __po_hi_vt_trigger_hkreporttrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_hkreporttrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_hkreporttrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_hkreporttrigger_artificial_hkreporttrigger (x86_partition_vt_trigger_hkreporttrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_hkreporttrigger_k, vt_trigger_hkreporttrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_hkreporttrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_woffsets[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_offsets[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_used_size[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_empties[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_first[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_tmdispatchtrigger_recent[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_tmdispatchtrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_tmdispatchtrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_tmdispatchtrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_n_dest[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_tmdispatchtrigger_fifo_size[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_tmdispatchtrigger_destinations[__po_hi_vt_trigger_tmdispatchtrigger_nb_ports] = {__po_hi_vt_trigger_tmdispatchtrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_tmdispatchtrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_tmdispatchtrigger_job (void)
 * \brief Function executed by the task vt_trigger_tmdispatchtrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_tmdispatchtrigger*/
extern void po_hi_c_vt_trigger_tmdispatchtrigger_artificial_tmdispatchtrigger 
    (__po_hi_task_id self);
void* vt_trigger_tmdispatchtrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_tmdispatchtrigger_k, __po_hi_vt_trigger_tmdispatchtrigger_nb_ports, __po_hi_vt_trigger_tmdispatchtrigger_queue, __po_hi_vt_trigger_tmdispatchtrigger_fifo_size, __po_hi_vt_trigger_tmdispatchtrigger_first, __po_hi_vt_trigger_tmdispatchtrigger_offsets, __po_hi_vt_trigger_tmdispatchtrigger_woffsets, __po_hi_vt_trigger_tmdispatchtrigger_n_dest, __po_hi_vt_trigger_tmdispatchtrigger_destinations, __po_hi_vt_trigger_tmdispatchtrigger_used_size, __po_hi_vt_trigger_tmdispatchtrigger_history, __po_hi_vt_trigger_tmdispatchtrigger_recent, __po_hi_vt_trigger_tmdispatchtrigger_empties, __po_hi_vt_trigger_tmdispatchtrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_tmdispatchtrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_tmdispatchtrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_tmdispatchtrigger_artificial_tmdispatchtrigger (x86_partition_vt_trigger_tmdispatchtrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tmdispatchtrigger_k, vt_trigger_tmdispatchtrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_tmdispatchtrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_woffsets[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_offsets[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_used_size[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_empties[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_first[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_eventactiontrigger_recent[__po_hi_vt_trigger_eventactiontrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_eventactiontrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_eventactiontrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_eventactiontrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_n_dest[__po_hi_vt_trigger_eventactiontrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_eventactiontrigger_fifo_size[__po_hi_vt_trigger_eventactiontrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_eventactiontrigger_destinations[__po_hi_vt_trigger_eventactiontrigger_nb_ports] = {__po_hi_vt_trigger_eventactiontrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_eventactiontrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_eventactiontrigger_job (void)
 * \brief Function executed by the task vt_trigger_eventactiontrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_eventactiontrigger*/
extern void po_hi_c_vt_trigger_eventactiontrigger_artificial_eventactiontrigger 
    (__po_hi_task_id self);
void* vt_trigger_eventactiontrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_eventactiontrigger_k, __po_hi_vt_trigger_eventactiontrigger_nb_ports, __po_hi_vt_trigger_eventactiontrigger_queue, __po_hi_vt_trigger_eventactiontrigger_fifo_size, __po_hi_vt_trigger_eventactiontrigger_first, __po_hi_vt_trigger_eventactiontrigger_offsets, __po_hi_vt_trigger_eventactiontrigger_woffsets, __po_hi_vt_trigger_eventactiontrigger_n_dest, __po_hi_vt_trigger_eventactiontrigger_destinations, __po_hi_vt_trigger_eventactiontrigger_used_size, __po_hi_vt_trigger_eventactiontrigger_history, __po_hi_vt_trigger_eventactiontrigger_recent, __po_hi_vt_trigger_eventactiontrigger_empties, __po_hi_vt_trigger_eventactiontrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_eventactiontrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_eventactiontrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_eventactiontrigger_artificial_eventactiontrigger (x86_partition_vt_trigger_eventactiontrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventactiontrigger_k, vt_trigger_eventactiontrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_eventactiontrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_woffsets[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_offsets[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_used_size[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_empties[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_first[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_tcdispatchtrigger_recent[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_tcdispatchtrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_tcdispatchtrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_tcdispatchtrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_n_dest[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_tcdispatchtrigger_fifo_size[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_tcdispatchtrigger_destinations[__po_hi_vt_trigger_tcdispatchtrigger_nb_ports] = {__po_hi_vt_trigger_tcdispatchtrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_tcdispatchtrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_tcdispatchtrigger_job (void)
 * \brief Function executed by the task vt_trigger_tcdispatchtrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_tcdispatchtrigger*/
extern void po_hi_c_vt_trigger_tcdispatchtrigger_artificial_tcdispatchtrigger 
    (__po_hi_task_id self);
void* vt_trigger_tcdispatchtrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_tcdispatchtrigger_k, __po_hi_vt_trigger_tcdispatchtrigger_nb_ports, __po_hi_vt_trigger_tcdispatchtrigger_queue, __po_hi_vt_trigger_tcdispatchtrigger_fifo_size, __po_hi_vt_trigger_tcdispatchtrigger_first, __po_hi_vt_trigger_tcdispatchtrigger_offsets, __po_hi_vt_trigger_tcdispatchtrigger_woffsets, __po_hi_vt_trigger_tcdispatchtrigger_n_dest, __po_hi_vt_trigger_tcdispatchtrigger_destinations, __po_hi_vt_trigger_tcdispatchtrigger_used_size, __po_hi_vt_trigger_tcdispatchtrigger_history, __po_hi_vt_trigger_tcdispatchtrigger_recent, __po_hi_vt_trigger_tcdispatchtrigger_empties, __po_hi_vt_trigger_tcdispatchtrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_tcdispatchtrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_tcdispatchtrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_tcdispatchtrigger_artificial_tcdispatchtrigger (x86_partition_vt_trigger_tcdispatchtrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_tcdispatchtrigger_k, vt_trigger_tcdispatchtrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_tcdispatchtrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_woffsets[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_offsets[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_used_size[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_empties[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_first[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_pmontrigger_recent[__po_hi_vt_trigger_pmontrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_pmontrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_pmontrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_pmontrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_n_dest[__po_hi_vt_trigger_pmontrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_pmontrigger_fifo_size[__po_hi_vt_trigger_pmontrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_pmontrigger_destinations[__po_hi_vt_trigger_pmontrigger_nb_ports] = {__po_hi_vt_trigger_pmontrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_pmontrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_pmontrigger_job (void)
 * \brief Function executed by the task vt_trigger_pmontrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_pmontrigger*/
extern void po_hi_c_vt_trigger_pmontrigger_artificial_pmontrigger 
    (__po_hi_task_id self);
void* vt_trigger_pmontrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_pmontrigger_k, __po_hi_vt_trigger_pmontrigger_nb_ports, __po_hi_vt_trigger_pmontrigger_queue, __po_hi_vt_trigger_pmontrigger_fifo_size, __po_hi_vt_trigger_pmontrigger_first, __po_hi_vt_trigger_pmontrigger_offsets, __po_hi_vt_trigger_pmontrigger_woffsets, __po_hi_vt_trigger_pmontrigger_n_dest, __po_hi_vt_trigger_pmontrigger_destinations, __po_hi_vt_trigger_pmontrigger_used_size, __po_hi_vt_trigger_pmontrigger_history, __po_hi_vt_trigger_pmontrigger_recent, __po_hi_vt_trigger_pmontrigger_empties, __po_hi_vt_trigger_pmontrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_pmontrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_pmontrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_pmontrigger_artificial_pmontrigger (x86_partition_vt_trigger_pmontrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_pmontrigger_k, vt_trigger_pmontrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_pmontrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_woffsets[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_offsets[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_used_size[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_empties[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_first[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_eventreporttrigger_recent[__po_hi_vt_trigger_eventreporttrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_eventreporttrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_eventreporttrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_eventreporttrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_n_dest[__po_hi_vt_trigger_eventreporttrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_eventreporttrigger_fifo_size[__po_hi_vt_trigger_eventreporttrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_eventreporttrigger_destinations[__po_hi_vt_trigger_eventreporttrigger_nb_ports] = {__po_hi_vt_trigger_eventreporttrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_eventreporttrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_eventreporttrigger_job (void)
 * \brief Function executed by the task vt_trigger_eventreporttrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_eventreporttrigger*/
extern void po_hi_c_vt_trigger_eventreporttrigger_artificial_eventreporttrigger 
    (__po_hi_task_id self);
void* vt_trigger_eventreporttrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_eventreporttrigger_k, __po_hi_vt_trigger_eventreporttrigger_nb_ports, __po_hi_vt_trigger_eventreporttrigger_queue, __po_hi_vt_trigger_eventreporttrigger_fifo_size, __po_hi_vt_trigger_eventreporttrigger_first, __po_hi_vt_trigger_eventreporttrigger_offsets, __po_hi_vt_trigger_eventreporttrigger_woffsets, __po_hi_vt_trigger_eventreporttrigger_n_dest, __po_hi_vt_trigger_eventreporttrigger_destinations, __po_hi_vt_trigger_eventreporttrigger_used_size, __po_hi_vt_trigger_eventreporttrigger_history, __po_hi_vt_trigger_eventreporttrigger_recent, __po_hi_vt_trigger_eventreporttrigger_empties, __po_hi_vt_trigger_eventreporttrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_eventreporttrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_eventreporttrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_eventreporttrigger_artificial_eventreporttrigger (x86_partition_vt_trigger_eventreporttrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_eventreporttrigger_k, vt_trigger_eventreporttrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_eventreporttrigger_k);
  }
}

__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_tmtrigger_vt_local_destinations[1] = {tmdispatch_global_inport_tmtrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_hkreporttrigger_vt_local_destinations[1] = {st03_global_inport_hkreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_pmontrigger_vt_local_destinations[1] = {vt_st12_pmontrigger_global_inport_artificial_pmontrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_eventreporttrigger_vt_local_destinations[1] = {st05_global_inport_eventreporttrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_tctrigger_vt_local_destinations[1] = {tcdispatch_global_inport_tctrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_debugeventstrigger_vt_local_destinations[1] = {vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger};
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_outport_eventactiontrigger_vt_local_destinations[1] = {vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger};
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_woffsets[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_offsets[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_used_size[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_empties[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_first[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_request_t __po_hi_vt_trigger_debugeventtrigger_recent[__po_hi_vt_trigger_debugeventtrigger_nb_ports];
__po_hi_port_t __po_hi_vt_trigger_debugeventtrigger_queue[0 * sizeof (__po_hi_request_t)];
__po_hi_uint16_t __po_hi_vt_trigger_debugeventtrigger_total_fifo_size = 0;
__po_hi_local_port_t __po_hi_vt_trigger_debugeventtrigger_history[0];
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_n_dest[__po_hi_vt_trigger_debugeventtrigger_nb_ports] = {1,1,1,1,1,1,1};
__po_hi_port_id_t __po_hi_vt_trigger_debugeventtrigger_fifo_size[__po_hi_vt_trigger_debugeventtrigger_nb_ports] = {__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT,__PO_HI_GQUEUE_FIFO_OUT};
__po_hi_port_t* __po_hi_vt_trigger_debugeventtrigger_destinations[__po_hi_vt_trigger_debugeventtrigger_nb_ports] = {__po_hi_vt_trigger_debugeventtrigger_outport_tmtrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_hkreporttrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_pmontrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_eventreporttrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_tctrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_debugeventstrigger_vt_local_destinations,__po_hi_vt_trigger_debugeventtrigger_outport_eventactiontrigger_vt_local_destinations};

/*!
 * \fn void* vt_trigger_debugeventtrigger_job (void)
 * \brief Function executed by the task vt_trigger_debugeventtrigger
 *
 * This function is executed as soon as the task  is created. It performs the 
 * following operations:  Receive incoming data,  Execute tasks subprograms,  
 * Send output data.
 */
/*  Periodic task : vt_trigger_debugeventtrigger*/
extern void po_hi_c_vt_trigger_debugeventtrigger_artificial_debugeventtrigger 
    (__po_hi_task_id self);
void* vt_trigger_debugeventtrigger_job (void)
{
  __po_hi_int32_t error;

  __po_hi_gqueue_init (x86_partition_vt_trigger_debugeventtrigger_k, __po_hi_vt_trigger_debugeventtrigger_nb_ports, __po_hi_vt_trigger_debugeventtrigger_queue, __po_hi_vt_trigger_debugeventtrigger_fifo_size, __po_hi_vt_trigger_debugeventtrigger_first, __po_hi_vt_trigger_debugeventtrigger_offsets, __po_hi_vt_trigger_debugeventtrigger_woffsets, __po_hi_vt_trigger_debugeventtrigger_n_dest, __po_hi_vt_trigger_debugeventtrigger_destinations, __po_hi_vt_trigger_debugeventtrigger_used_size, __po_hi_vt_trigger_debugeventtrigger_history, __po_hi_vt_trigger_debugeventtrigger_recent, __po_hi_vt_trigger_debugeventtrigger_empties, __po_hi_vt_trigger_debugeventtrigger_total_fifo_size);
  
/*!
 * Waiting for other tasks initialization
 */
  __po_hi_wait_initialization ();
  __po_hi_time_t offset;
  __po_hi_milliseconds (&(offset), 0);
  __po_hi_task_wait_offset (&(offset));
  __po_hi_compute_next_period (x86_partition_vt_trigger_debugeventtrigger_k);
  
/*!
 * Waiting for the first dispatch instant
 */
  __po_hi_wait_for_next_period (x86_partition_vt_trigger_debugeventtrigger_k);
  
/*!
 * Task body
 */
  while (1)
  {
    /*  Make_Thread_Compute_Entrypoint*/
    po_hi_c_vt_trigger_debugeventtrigger_artificial_debugeventtrigger (x86_partition_vt_trigger_debugeventtrigger_k);
    /*  Send the OUT ports*/
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_tmtrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_hkreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_pmontrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_eventreporttrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_tctrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_debugeventstrigger_vt);
    error =
     __po_hi_send_output (x86_partition_vt_trigger_debugeventtrigger_k, vt_trigger_debugeventtrigger_global_outport_eventactiontrigger_vt);
    __po_hi_wait_for_next_period (x86_partition_vt_trigger_debugeventtrigger_k);
  }
}


/*!
 * \fn void __po_hi_main_deliver (__po_hi_request_t* request)
 * \brief Used to deliver request to the appropriate ports
 *
 * This function takes a request as argument (\arg request) and calls the 
 * appropriate function for its delivery.To specify which function should be 
 * called, it extracts the receiver entity using the destination port.
 */
void __po_hi_main_deliver 
    (__po_hi_request_t* request)
{
  __po_hi_entity_t entity;

  entity = __po_hi_get_entity_from_global_port (request->port);
  switch (entity)
  {
    case x86_partition_tcdispatch_k_entity:
    {
      tcdispatch_deliver (request);

      break;
    }
    case x86_partition_tmdispatch_k_entity:
    {
      tmdispatch_deliver (request);

      break;
    }
    case x86_partition_st05_k_entity:
    {
      st05_deliver (request);

      break;
    }
    case x86_partition_st03_k_entity:
    {
      st03_deliver (request);

      break;
    }
    case x86_partition_vt_ground_newtm_k_entity:
    {
      vt_ground_newtm_deliver (request);

      break;
    }
    case x86_partition_vt_tcqueue_newtc_k_entity:
    {
      vt_tcqueue_newtc_deliver (request);

      break;
    }
    case x86_partition_vt_events_debugeventstrigger_k_entity:
    {
      vt_events_debugeventstrigger_deliver (request);

      break;
    }
    case x86_partition_vt_st19_eventactiontrigger_k_entity:
    {
      vt_st19_eventactiontrigger_deliver (request);

      break;
    }
    case x86_partition_vt_st12_pmontrigger_k_entity:
    {
      vt_st12_pmontrigger_deliver (request);

      break;
    }
    default:
    {
      break;
    }
  }
}


