#ifndef __OCARINA_GENERATED_DEPLOYMENT_H_
#define __OCARINA_GENERATED_DEPLOYMENT_H_ 
#include <po_hi_types.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

#define __PO_HI_MY_NODE x86_partition_k

#define __po_hi_tcdispatch_nb_ports 2

#define __po_hi_tmdispatch_nb_ports 2

#define __po_hi_st05_nb_ports 1

#define __po_hi_st03_nb_ports 1

#define __po_hi_vt_ground_newtm_nb_ports 2

#define __po_hi_vt_ground_triggertmgui_nb_ports 1

#define __po_hi_vt_tcqueue_newtc_nb_ports 1

#define __po_hi_vt_events_debugeventstrigger_nb_ports 1

#define __po_hi_vt_st19_eventactiontrigger_nb_ports 2

#define __po_hi_vt_st12_pmontrigger_nb_ports 1

#define __po_hi_vt_trigger_hkreporttrigger_nb_ports 7

#define __po_hi_vt_trigger_tmdispatchtrigger_nb_ports 7

#define __po_hi_vt_trigger_eventactiontrigger_nb_ports 7

#define __po_hi_vt_trigger_tcdispatchtrigger_nb_ports 7

#define __po_hi_vt_trigger_pmontrigger_nb_ports 7

#define __po_hi_vt_trigger_eventreporttrigger_nb_ports 7

#define __po_hi_vt_trigger_debugeventtrigger_nb_ports 7

/*  For each node in the distributed application add an enumerator*/

typedef enum
{
  x86_partition_k = 0
} __po_hi_node_t;

typedef enum
{
  invalid_protocol = -1
} __po_hi_protocol_t;

/*  For each thread in the distributed application nodes, add an enumerator*/

typedef enum
{
  x86_partition_tcdispatch_k_entity = 0,
  x86_partition_tmdispatch_k_entity = 1,
  x86_partition_st05_k_entity = 2,
  x86_partition_st03_k_entity = 3,
  x86_partition_onboardsoftware_k_entity = 4,
  x86_partition_vt_ground_newtm_k_entity = 5,
  x86_partition_vt_ground_triggertmgui_k_entity = 6,
  x86_partition_vt_tcqueue_newtc_k_entity = 7,
  x86_partition_vt_events_debugeventstrigger_k_entity = 8,
  x86_partition_vt_st19_eventactiontrigger_k_entity = 9,
  x86_partition_vt_st12_pmontrigger_k_entity = 10,
  x86_partition_vt_trigger_hkreporttrigger_k_entity = 11,
  x86_partition_vt_trigger_tmdispatchtrigger_k_entity = 12,
  x86_partition_vt_trigger_eventactiontrigger_k_entity = 13,
  x86_partition_vt_trigger_tcdispatchtrigger_k_entity = 14,
  x86_partition_vt_trigger_pmontrigger_k_entity = 15,
  x86_partition_vt_trigger_eventreporttrigger_k_entity = 16,
  x86_partition_vt_trigger_debugeventtrigger_k_entity = 17,
  invalid_entity = -1
} __po_hi_entity_t;

typedef enum
{
  x86_partition_tcdispatch_k = 0,
  x86_partition_tmdispatch_k = 1,
  x86_partition_st05_k = 2,
  x86_partition_st03_k = 3,
  x86_partition_onboardsoftware_k = 4,
  x86_partition_vt_ground_newtm_k = 5,
  x86_partition_vt_ground_triggertmgui_k = 6,
  x86_partition_vt_tcqueue_newtc_k = 7,
  x86_partition_vt_events_debugeventstrigger_k = 8,
  x86_partition_vt_st19_eventactiontrigger_k = 9,
  x86_partition_vt_st12_pmontrigger_k = 10,
  x86_partition_vt_trigger_hkreporttrigger_k = 11,
  x86_partition_vt_trigger_tmdispatchtrigger_k = 12,
  x86_partition_vt_trigger_eventactiontrigger_k = 13,
  x86_partition_vt_trigger_tcdispatchtrigger_k = 14,
  x86_partition_vt_trigger_pmontrigger_k = 15,
  x86_partition_vt_trigger_eventreporttrigger_k = 16,
  x86_partition_vt_trigger_debugeventtrigger_k = 17,
  invalid_task_id = -1
} __po_hi_task_id;

typedef enum
{
  invalid_device_id = -1
} __po_hi_device_id;

typedef enum
{
  invalid_bus_id = -1
} __po_hi_bus_id;

#define __PO_HI_NB_TASKS 18

#define __PO_HI_TASKS_STACK 900000

#define __PO_HI_NB_PROTECTED 21

#define __PO_HI_NB_NODES 1

#define __PO_HI_NB_ENTITIES 18

#define __PO_HI_NB_PORTS 63

typedef enum
{
  tcdispatch_global_inport_tctrigger = 0,
  tcdispatch_global_outport_newtc_vt = 1,
  tmdispatch_global_inport_tmtrigger = 2,
  tmdispatch_global_outport_newtm = 3,
  st05_global_inport_eventreporttrigger = 4,
  st03_global_inport_hkreporttrigger = 5,
  vt_ground_newtm_global_inport_artificial_newtm = 6,
  vt_ground_newtm_global_outport_newtc_vt = 7,
  vt_ground_triggertmgui_global_outport_newtc_vt = 8,
  vt_tcqueue_newtc_global_inport_artificial_newtc = 9,
  vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger = 10,
  vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger = 11,
  vt_st19_eventactiontrigger_global_outport_newtc_vt = 12,
  vt_st12_pmontrigger_global_inport_artificial_pmontrigger = 13,
  vt_trigger_hkreporttrigger_global_outport_tmtrigger_vt = 14,
  vt_trigger_hkreporttrigger_global_outport_hkreporttrigger_vt = 15,
  vt_trigger_hkreporttrigger_global_outport_pmontrigger_vt = 16,
  vt_trigger_hkreporttrigger_global_outport_eventreporttrigger_vt = 17,
  vt_trigger_hkreporttrigger_global_outport_tctrigger_vt = 18,
  vt_trigger_hkreporttrigger_global_outport_debugeventstrigger_vt = 19,
  vt_trigger_hkreporttrigger_global_outport_eventactiontrigger_vt = 20,
  vt_trigger_tmdispatchtrigger_global_outport_tmtrigger_vt = 21,
  vt_trigger_tmdispatchtrigger_global_outport_hkreporttrigger_vt = 22,
  vt_trigger_tmdispatchtrigger_global_outport_pmontrigger_vt = 23,
  vt_trigger_tmdispatchtrigger_global_outport_eventreporttrigger_vt = 24,
  vt_trigger_tmdispatchtrigger_global_outport_tctrigger_vt = 25,
  vt_trigger_tmdispatchtrigger_global_outport_debugeventstrigger_vt = 26,
  vt_trigger_tmdispatchtrigger_global_outport_eventactiontrigger_vt = 27,
  vt_trigger_eventactiontrigger_global_outport_tmtrigger_vt = 28,
  vt_trigger_eventactiontrigger_global_outport_hkreporttrigger_vt = 29,
  vt_trigger_eventactiontrigger_global_outport_pmontrigger_vt = 30,
  vt_trigger_eventactiontrigger_global_outport_eventreporttrigger_vt = 31,
  vt_trigger_eventactiontrigger_global_outport_tctrigger_vt = 32,
  vt_trigger_eventactiontrigger_global_outport_debugeventstrigger_vt = 33,
  vt_trigger_eventactiontrigger_global_outport_eventactiontrigger_vt = 34,
  vt_trigger_tcdispatchtrigger_global_outport_tmtrigger_vt = 35,
  vt_trigger_tcdispatchtrigger_global_outport_hkreporttrigger_vt = 36,
  vt_trigger_tcdispatchtrigger_global_outport_pmontrigger_vt = 37,
  vt_trigger_tcdispatchtrigger_global_outport_eventreporttrigger_vt = 38,
  vt_trigger_tcdispatchtrigger_global_outport_tctrigger_vt = 39,
  vt_trigger_tcdispatchtrigger_global_outport_debugeventstrigger_vt = 40,
  vt_trigger_tcdispatchtrigger_global_outport_eventactiontrigger_vt = 41,
  vt_trigger_pmontrigger_global_outport_tmtrigger_vt = 42,
  vt_trigger_pmontrigger_global_outport_hkreporttrigger_vt = 43,
  vt_trigger_pmontrigger_global_outport_pmontrigger_vt = 44,
  vt_trigger_pmontrigger_global_outport_eventreporttrigger_vt = 45,
  vt_trigger_pmontrigger_global_outport_tctrigger_vt = 46,
  vt_trigger_pmontrigger_global_outport_debugeventstrigger_vt = 47,
  vt_trigger_pmontrigger_global_outport_eventactiontrigger_vt = 48,
  vt_trigger_eventreporttrigger_global_outport_tmtrigger_vt = 49,
  vt_trigger_eventreporttrigger_global_outport_hkreporttrigger_vt = 50,
  vt_trigger_eventreporttrigger_global_outport_pmontrigger_vt = 51,
  vt_trigger_eventreporttrigger_global_outport_eventreporttrigger_vt = 52,
  vt_trigger_eventreporttrigger_global_outport_tctrigger_vt = 53,
  vt_trigger_eventreporttrigger_global_outport_debugeventstrigger_vt = 54,
  vt_trigger_eventreporttrigger_global_outport_eventactiontrigger_vt = 55,
  vt_trigger_debugeventtrigger_global_outport_tmtrigger_vt = 56,
  vt_trigger_debugeventtrigger_global_outport_hkreporttrigger_vt = 57,
  vt_trigger_debugeventtrigger_global_outport_pmontrigger_vt = 58,
  vt_trigger_debugeventtrigger_global_outport_eventreporttrigger_vt = 59,
  vt_trigger_debugeventtrigger_global_outport_tctrigger_vt = 60,
  vt_trigger_debugeventtrigger_global_outport_debugeventstrigger_vt = 61,
  vt_trigger_debugeventtrigger_global_outport_eventactiontrigger_vt = 62,
  invalid_port_t = -1,
  constant_out_identifier = 64
} __po_hi_port_t;

typedef enum
{
  tcdispatch_local_inport_tctrigger = 0,
  tcdispatch_local_outport_newtc_vt = 1,
  tmdispatch_local_inport_tmtrigger = 0,
  tmdispatch_local_outport_newtm = 1,
  st05_local_inport_eventreporttrigger = 0,
  st03_local_inport_hkreporttrigger = 0,
  vt_ground_newtm_local_inport_artificial_newtm = 0,
  vt_ground_newtm_local_outport_newtc_vt = 1,
  vt_ground_triggertmgui_local_outport_newtc_vt = 0,
  vt_tcqueue_newtc_local_inport_artificial_newtc = 0,
  vt_events_debugeventstrigger_local_inport_artificial_debugeventstrigger = 0,
  vt_st19_eventactiontrigger_local_inport_artificial_eventactiontrigger = 0,
  vt_st19_eventactiontrigger_local_outport_newtc_vt = 1,
  vt_st12_pmontrigger_local_inport_artificial_pmontrigger = 0,
  vt_trigger_hkreporttrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_hkreporttrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_hkreporttrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_hkreporttrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_hkreporttrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_hkreporttrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_hkreporttrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_tmdispatchtrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_tmdispatchtrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_tmdispatchtrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_tmdispatchtrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_tmdispatchtrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_tmdispatchtrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_tmdispatchtrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_eventactiontrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_eventactiontrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_eventactiontrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_eventactiontrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_eventactiontrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_eventactiontrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_eventactiontrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_tcdispatchtrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_tcdispatchtrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_tcdispatchtrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_tcdispatchtrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_tcdispatchtrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_tcdispatchtrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_tcdispatchtrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_pmontrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_pmontrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_pmontrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_pmontrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_pmontrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_pmontrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_pmontrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_eventreporttrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_eventreporttrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_eventreporttrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_eventreporttrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_eventreporttrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_eventreporttrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_eventreporttrigger_local_outport_eventactiontrigger_vt = 6,
  vt_trigger_debugeventtrigger_local_outport_tmtrigger_vt = 0,
  vt_trigger_debugeventtrigger_local_outport_hkreporttrigger_vt = 1,
  vt_trigger_debugeventtrigger_local_outport_pmontrigger_vt = 2,
  vt_trigger_debugeventtrigger_local_outport_eventreporttrigger_vt = 3,
  vt_trigger_debugeventtrigger_local_outport_tctrigger_vt = 4,
  vt_trigger_debugeventtrigger_local_outport_debugeventstrigger_vt = 5,
  vt_trigger_debugeventtrigger_local_outport_eventactiontrigger_vt = 6,
  invalid_local_port_t = -1
} __po_hi_local_port_t;

#define __PO_HI_NB_DEVICES 0

#define __PO_HI_NB_BUSES 0

#define __PO_HI_NB_PROTOCOLS 0

#define __PO_HI_PORT_TYPE_CONTENT __po_hi_tcdispatch_nb_ports, __po_hi_tmdispatch_nb_ports, __po_hi_st05_nb_ports, __po_hi_st03_nb_ports, __po_hi_vt_ground_newtm_nb_ports, __po_hi_vt_ground_triggertmgui_nb_ports, __po_hi_vt_tcqueue_newtc_nb_ports, __po_hi_vt_events_debugeventstrigger_nb_ports, __po_hi_vt_st19_eventactiontrigger_nb_ports, __po_hi_vt_st12_pmontrigger_nb_ports, __po_hi_vt_trigger_hkreporttrigger_nb_ports, __po_hi_vt_trigger_tmdispatchtrigger_nb_ports, __po_hi_vt_trigger_eventactiontrigger_nb_ports, __po_hi_vt_trigger_tcdispatchtrigger_nb_ports, __po_hi_vt_trigger_pmontrigger_nb_ports, __po_hi_vt_trigger_eventreporttrigger_nb_ports, __po_hi_vt_trigger_debugeventtrigger_nb_ports

#endif
