#include <types.h>
#include <po_hi_types.h>
#include <po_hi_marshallers.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
void __po_hi_marshall_type_taste_protected_object 
    (process_package__taste_protected_object value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (&(value), message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_unmarshall_type_taste_protected_object 
    (process_package__taste_protected_object* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, sizeof (process_package__taste_protected_object), offset);
}

void __po_hi_marshall_type_puspacket_buffer_max_impl 
    (dataview__puspacket_buffer_max_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_array (value, message, 5784 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_unmarshall_type_puspacket_buffer_max_impl 
    (dataview__puspacket_buffer_max_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_array (value, message, 5784 * sizeof (dataview__stream_element_buffer), offset);
}

void __po_hi_marshall_type_stream_element_buffer 
    (dataview__stream_element_buffer value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_char (value, message, offset);
}

void __po_hi_unmarshall_type_stream_element_buffer 
    (dataview__stream_element_buffer* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_char (value, message, offset);
}

void __po_hi_marshall_type_unsigned_32 
    (base_types__unsigned_32 value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_uint32 (value, message, offset);
}

void __po_hi_unmarshall_type_unsigned_32 
    (base_types__unsigned_32* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_uint32 (value, message, offset);
}

void __po_hi_marshall_type_puspacket_buffer_impl 
    (dataview__puspacket_buffer_impl value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_max_impl (value.buffer, message, offset);
  __po_hi_marshall_uint32 (value.length, message, offset);
}

void __po_hi_unmarshall_type_puspacket_buffer_impl 
    (dataview__puspacket_buffer_impl* value,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_max_impl (&(value->buffer), message, offset);
  __po_hi_unmarshall_uint32 (&(value->length), message, offset);
}

void __po_hi_marshall_request_tcdispatch_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.tcdispatch_global_outport_newtc_vt.tcdispatch_global_outport_newtc_vt, message, offset);
}

void __po_hi_unmarshall_request_tcdispatch_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.tcdispatch_global_outport_newtc_vt.tcdispatch_global_outport_newtc_vt), message, offset);
}

void __po_hi_marshall_request_tmdispatch_outport_newtm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.tmdispatch_global_outport_newtm.tmdispatch_global_outport_newtm, message, offset);
}

void __po_hi_unmarshall_request_tmdispatch_outport_newtm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.tmdispatch_global_outport_newtm.tmdispatch_global_outport_newtm), message, offset);
}

void __po_hi_marshall_request_vt_ground_newtm_inport_artificial_newtm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_ground_newtm_global_inport_artificial_newtm.vt_ground_newtm_global_inport_artificial_newtm, message, offset);
}

void __po_hi_unmarshall_request_vt_ground_newtm_inport_artificial_newtm 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_ground_newtm_global_inport_artificial_newtm.vt_ground_newtm_global_inport_artificial_newtm), message, offset);
}

void __po_hi_marshall_request_vt_ground_newtm_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_ground_newtm_global_outport_newtc_vt.vt_ground_newtm_global_outport_newtc_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_ground_newtm_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_ground_newtm_global_outport_newtc_vt.vt_ground_newtm_global_outport_newtc_vt), message, offset);
}

void __po_hi_marshall_request_vt_ground_triggertmgui_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_ground_triggertmgui_global_outport_newtc_vt.vt_ground_triggertmgui_global_outport_newtc_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_ground_triggertmgui_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_ground_triggertmgui_global_outport_newtc_vt.vt_ground_triggertmgui_global_outport_newtc_vt), message, offset);
}

void __po_hi_marshall_request_vt_tcqueue_newtc_inport_artificial_newtc 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_tcqueue_newtc_global_inport_artificial_newtc.vt_tcqueue_newtc_global_inport_artificial_newtc, message, offset);
}

void __po_hi_unmarshall_request_vt_tcqueue_newtc_inport_artificial_newtc 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_tcqueue_newtc_global_inport_artificial_newtc.vt_tcqueue_newtc_global_inport_artificial_newtc), message, offset);
}

void __po_hi_marshall_request_vt_st19_eventactiontrigger_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_marshall_type_puspacket_buffer_impl (request->vars.vt_st19_eventactiontrigger_global_outport_newtc_vt.vt_st19_eventactiontrigger_global_outport_newtc_vt, message, offset);
}

void __po_hi_unmarshall_request_vt_st19_eventactiontrigger_outport_newtc_vt 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message,
    __po_hi_uint32_t* offset)
{

  __po_hi_unmarshall_type_puspacket_buffer_impl (&(request->vars.vt_st19_eventactiontrigger_global_outport_newtc_vt.vt_st19_eventactiontrigger_global_outport_newtc_vt), message, offset);
}

void __po_hi_marshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_marshall_port (request->port, message);
  switch (request->port)
  {
    case tcdispatch_global_outport_newtc_vt:
    {
      __po_hi_marshall_request_tcdispatch_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case tmdispatch_global_outport_newtm:
    {
      __po_hi_marshall_request_tmdispatch_outport_newtm (request, message, &(offset));

      break;
    }
    case vt_ground_newtm_global_inport_artificial_newtm:
    {
      __po_hi_marshall_request_vt_ground_newtm_inport_artificial_newtm (request, message, &(offset));

      break;
    }
    case vt_ground_newtm_global_outport_newtc_vt:
    {
      __po_hi_marshall_request_vt_ground_newtm_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case vt_ground_triggertmgui_global_outport_newtc_vt:
    {
      __po_hi_marshall_request_vt_ground_triggertmgui_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case vt_tcqueue_newtc_global_inport_artificial_newtc:
    {
      __po_hi_marshall_request_vt_tcqueue_newtc_inport_artificial_newtc (request, message, &(offset));

      break;
    }
    case vt_st19_eventactiontrigger_global_outport_newtc_vt:
    {
      __po_hi_marshall_request_vt_st19_eventactiontrigger_outport_newtc_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}

void __po_hi_unmarshall_request 
    (__po_hi_request_t* request,
    __po_hi_msg_t* message)
{
  __po_hi_uint32_t offset;

  offset = 0;
  __po_hi_unmarshall_port (&(request->port), message);
  switch (request->port)
  {
    case tcdispatch_global_outport_newtc_vt:
    {
      __po_hi_unmarshall_request_tcdispatch_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case tmdispatch_global_outport_newtm:
    {
      __po_hi_unmarshall_request_tmdispatch_outport_newtm (request, message, &(offset));

      break;
    }
    case vt_ground_newtm_global_inport_artificial_newtm:
    {
      __po_hi_unmarshall_request_vt_ground_newtm_inport_artificial_newtm (request, message, &(offset));

      break;
    }
    case vt_ground_newtm_global_outport_newtc_vt:
    {
      __po_hi_unmarshall_request_vt_ground_newtm_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case vt_ground_triggertmgui_global_outport_newtc_vt:
    {
      __po_hi_unmarshall_request_vt_ground_triggertmgui_outport_newtc_vt (request, message, &(offset));

      break;
    }
    case vt_tcqueue_newtc_global_inport_artificial_newtc:
    {
      __po_hi_unmarshall_request_vt_tcqueue_newtc_inport_artificial_newtc (request, message, &(offset));

      break;
    }
    case vt_st19_eventactiontrigger_global_outport_newtc_vt:
    {
      __po_hi_unmarshall_request_vt_st19_eventactiontrigger_outport_newtc_vt (request, message, &(offset));

      break;
    }
    default:
    {
      break;
    }
  }
}


