#ifndef __OCARINA_GENERATED_REQUEST_H_
#define __OCARINA_GENERATED_REQUEST_H_ 
#include <types.h>
#include <po_hi_types.h>
#include <deployment.h>
/*****************************************************/

/*  This file was automatically generated by Ocarina */

/*  Do NOT hand-modify this file, as your            */

/*  changes will be lost when you re-run Ocarina     */

/*****************************************************/

/*  Enumeration type for all the operations in the distributed application.*/

typedef struct
{
  __po_hi_port_t port;

  union
  {
    struct
    {
      __po_hi_bool_t tcdispatch_global_inport_tctrigger;

    } tcdispatch_global_inport_tctrigger;

    struct
    {
      dataview__puspacket_buffer_impl tcdispatch_global_outport_newtc_vt;

    } tcdispatch_global_outport_newtc_vt;

    struct
    {
      __po_hi_bool_t tmdispatch_global_inport_tmtrigger;

    } tmdispatch_global_inport_tmtrigger;

    struct
    {
      dataview__puspacket_buffer_impl tmdispatch_global_outport_newtm;

    } tmdispatch_global_outport_newtm;

    struct
    {
      __po_hi_bool_t st05_global_inport_eventreporttrigger;

    } st05_global_inport_eventreporttrigger;

    struct
    {
      __po_hi_bool_t st03_global_inport_hkreporttrigger;

    } st03_global_inport_hkreporttrigger;

    struct
    {
      dataview__puspacket_buffer_impl vt_ground_newtm_global_inport_artificial_newtm;

    } vt_ground_newtm_global_inport_artificial_newtm;

    struct
    {
      dataview__puspacket_buffer_impl vt_ground_newtm_global_outport_newtc_vt;

    } vt_ground_newtm_global_outport_newtc_vt;

    struct
    {
      dataview__puspacket_buffer_impl vt_ground_triggertmgui_global_outport_newtc_vt;

    } vt_ground_triggertmgui_global_outport_newtc_vt;

    struct
    {
      dataview__puspacket_buffer_impl vt_tcqueue_newtc_global_inport_artificial_newtc;

    } vt_tcqueue_newtc_global_inport_artificial_newtc;

    struct
    {
      __po_hi_bool_t vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger;

    } vt_events_debugeventstrigger_global_inport_artificial_debugeventstrigger;

    struct
    {
      __po_hi_bool_t vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger;

    } vt_st19_eventactiontrigger_global_inport_artificial_eventactiontrigger;

    struct
    {
      dataview__puspacket_buffer_impl vt_st19_eventactiontrigger_global_outport_newtc_vt;

    } vt_st19_eventactiontrigger_global_outport_newtc_vt;

    struct
    {
      __po_hi_bool_t vt_st12_pmontrigger_global_inport_artificial_pmontrigger;

    } vt_st12_pmontrigger_global_inport_artificial_pmontrigger;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_tmtrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_pmontrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_tctrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_hkreporttrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_hkreporttrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_tmtrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_pmontrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_tctrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tmdispatchtrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_tmdispatchtrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_tmtrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_pmontrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_tctrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventactiontrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_eventactiontrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_tmtrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_pmontrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_tctrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_tcdispatchtrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_tcdispatchtrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_tmtrigger_vt;

    } vt_trigger_pmontrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_pmontrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_pmontrigger_vt;

    } vt_trigger_pmontrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_pmontrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_tctrigger_vt;

    } vt_trigger_pmontrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_pmontrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_pmontrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_pmontrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_tmtrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_pmontrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_tctrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_eventreporttrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_eventreporttrigger_global_outport_eventactiontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_tmtrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_tmtrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_hkreporttrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_hkreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_pmontrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_pmontrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_eventreporttrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_eventreporttrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_tctrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_tctrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_debugeventstrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_debugeventstrigger_vt;

    struct
    {
      __po_hi_bool_t vt_trigger_debugeventtrigger_global_outport_eventactiontrigger_vt;

    } vt_trigger_debugeventtrigger_global_outport_eventactiontrigger_vt;

  } vars;

} __po_hi_request_t;

#define __PO_HI_NB_OPERATIONS 0

#endif
