#include "subprograms.h"
#include <types.h>
/*****************************************************/
/*  This file was automatically generated by Ocarina */
/*  Do NOT hand-modify this file, as your            */
/*  changes will be lost when you re-run Ocarina     */
/*****************************************************/
extern process_package__taste_protected_object ground_protected;
extern process_package__taste_protected_object tcqueue_protected;
extern process_package__taste_protected_object tmqueue_protected;
extern process_package__taste_protected_object st17_protected;
extern process_package__taste_protected_object st01_protected;
extern process_package__taste_protected_object st08_protected;
extern process_package__taste_protected_object onboardapid_protected;
extern process_package__taste_protected_object st09_protected;
extern process_package__taste_protected_object timereportapid_protected;
extern process_package__taste_protected_object events_protected;
extern process_package__taste_protected_object st19_protected;
extern process_package__taste_protected_object housekeeping_protected;
extern process_package__taste_protected_object st12_protected;
extern process_package__taste_protected_object st11_protected;
extern process_package__taste_protected_object st18_protected;
extern process_package__taste_protected_object obcpengine_protected;
extern process_package__taste_protected_object st23_protected;
extern process_package__taste_protected_object filemanagement_protected;
extern process_package__taste_protected_object st20_protected;
extern process_package__taste_protected_object onboardparams_protected;
extern process_package__taste_protected_object trigger_protected;

