#ifndef GENERATED_ASN1SCC_Context_pusservices_H
#define GENERATED_ASN1SCC_Context_pusservices_H
/*
Code automatically generated by asn1scc tool
*/
#include "asn1crt.h"
#include "asn1crt_encoding.h"

#include "dataview-uniq.h"

#ifdef  __cplusplus
extern "C" {
#endif


/*-- asn1SccContext_pusservices --------------------------------------------*/
typedef struct {
    asn1SccPusUInt11 apid;

} asn1SccContext_pusservices;

flag asn1SccContext_pusservices_Equal(const asn1SccContext_pusservices* pVal1, const asn1SccContext_pusservices* pVal2);

void asn1SccContext_pusservices_Initialize(asn1SccContext_pusservices* pVal);

#define ERR_CONTEXT_PUSSERVICES		41251  /**/
#define ERR_CONTEXT_PUSSERVICES_APID		41236  /**/
flag asn1SccContext_pusservices_IsConstraintValid(const asn1SccContext_pusservices* pVal, int* pErrCode);

#define ERR_UPER_ENCODE_CONTEXT_PUSSERVICES		41252  /**/
#define ERR_UPER_ENCODE_CONTEXT_PUSSERVICES_APID_2_2		41247  /**/
#define asn1SccContext_pusservices_REQUIRED_BYTES_FOR_ENCODING       2 
#define asn1SccContext_pusservices_REQUIRED_BITS_FOR_ENCODING        11

flag asn1SccContext_pusservices_Encode(const asn1SccContext_pusservices* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_UPER_DECODE_CONTEXT_PUSSERVICES		41253  /**/
#define ERR_UPER_DECODE_CONTEXT_PUSSERVICES_APID_2_2		41248  /**/
flag asn1SccContext_pusservices_Decode(asn1SccContext_pusservices* pVal, BitStream* pBitStrm, int* pErrCode);

#define ERR_ACN_ENCODE_CONTEXT_PUSSERVICES		41254  /**/
#define ERR_ACN_ENCODE_CONTEXT_PUSSERVICES_APID		41239  /**/
#define asn1SccContext_pusservices_REQUIRED_BYTES_FOR_ACN_ENCODING       2 
#define asn1SccContext_pusservices_REQUIRED_BITS_FOR_ACN_ENCODING        11

flag asn1SccContext_pusservices_ACN_Encode(const asn1SccContext_pusservices* pVal, BitStream* pBitStrm, int* pErrCode, flag bCheckConstraints);

#define ERR_ACN_DECODE_CONTEXT_PUSSERVICES		41255  /**/
#define ERR_ACN_DECODE_CONTEXT_PUSSERVICES_APID		41240  /**/
flag asn1SccContext_pusservices_ACN_Decode(asn1SccContext_pusservices* pVal, BitStream* pBitStrm, int* pErrCode);

extern const asn1SccContext_pusservices pusservices_ctxt; 

/* ================= Encoding/Decoding function prototypes =================
 * These functions are placed at the end of the file to make sure all types
 * have been declared first, in case of parameterized ACN encodings
 * ========================================================================= */

 


#ifdef  __cplusplus
}

#endif

#endif
