#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1PusTM_TC_Dummy_Data(const char *paramName, const asn1SccPusTM_TC_Dummy_Data *pData);
void PrintASN1PusTmHeader(const char *paramName, const asn1SccPusTmHeader *pData);
void PrintASN1PusTmSourceData(const char *paramName, const asn1SccPusTmSourceData *pData);
void PrintASN1PusTcHeader(const char *paramName, const asn1SccPusTcHeader *pData);
void PrintASN1PusTC_19_1_Data(const char *paramName, const asn1SccPusTC_19_1_Data *pData);
void PrintASN1PusTcScheduledActivity(const char *paramName, const asn1SccPusTcScheduledActivity *pData);
void PrintASN1PusTC_11_4_Data(const char *paramName, const asn1SccPusTC_11_4_Data *pData);
void PrintASN1PusTcApplicationData(const char *paramName, const asn1SccPusTcApplicationData *pData);
void PrintASN1PusTcApplicationDataReduced(const char *paramName, const asn1SccPusTcApplicationDataReduced *pData);
void PrintASN1PusTmHeaderData(const char *paramName, const asn1SccPusTmHeaderData *pData);
void PrintASN1PusPacketData(const char *paramName, const asn1SccPusPacketData *pData);
void PrintASN1PusPacketDataReduced(const char *paramName, const asn1SccPusPacketDataReduced *pData);
void PrintASN1PusPacket(const char *paramName, const asn1SccPusPacket *pData);
void PrintASN1PusPacketReduced(const char *paramName, const asn1SccPusPacketReduced *pData);
void PrintASN1PusPacketVersion(const char *paramName, const asn1SccPusPacketVersion *pData);
void PrintASN1PusPacketType(const char *paramName, const asn1SccPusPacketType *pData);
void PrintASN1PusSecondaryHeaderFlag(const char *paramName, const asn1SccPusSecondaryHeaderFlag *pData);
void PrintASN1PusApid(const char *paramName, const asn1SccPusApid *pData);
void PrintASN1PusSequenceFlags(const char *paramName, const asn1SccPusSequenceFlags *pData);
void PrintASN1PusSequenceCount(const char *paramName, const asn1SccPusSequenceCount *pData);
void PrintASN1PusPacketDataLength(const char *paramName, const asn1SccPusPacketDataLength *pData);
void PrintASN1PusVersionNumber(const char *paramName, const asn1SccPusVersionNumber *pData);
void PrintASN1PusTimeReferenceStatus(const char *paramName, const asn1SccPusTimeReferenceStatus *pData);
void PrintASN1PusMessageTypeCounter(const char *paramName, const asn1SccPusMessageTypeCounter *pData);
void PrintASN1PusAcknowledgementFlags(const char *paramName, const asn1SccPusAcknowledgementFlags *pData);
void PrintASN1PusChecksum(const char *paramName, const asn1SccPusChecksum *pData);
void PrintASN1PusStepId(const char *paramName, const asn1SccPusStepId *pData);
void PrintASN1PusConfigDummyType(const char *paramName, const asn1SccPusConfigDummyType *pData);
void PrintASN1PusServiceType(const char *paramName, const asn1SccPusServiceType *pData);
void PrintASN1PusSubserviceType(const char *paramName, const asn1SccPusSubserviceType *pData);
void PrintASN1PusSt01FailureCode(const char *paramName, const asn1SccPusSt01FailureCode *pData);
void PrintASN1PusSt01FailureInfo(const char *paramName, const asn1SccPusSt01FailureInfo *pData);
void PrintASN1PusSt01RequestId(const char *paramName, const asn1SccPusSt01RequestId *pData);
void PrintASN1PusSt01Failure(const char *paramName, const asn1SccPusSt01Failure *pData);
void PrintASN1PusTM_1_X_Data(const char *paramName, const asn1SccPusTM_1_X_Data *pData);
void PrintASN1PusSt03StoredParam(const char *paramName, const asn1SccPusSt03StoredParam *pData);
void PrintASN1PusSt03HousekeepingReportId(const char *paramName, const asn1SccPusSt03HousekeepingReportId *pData);
void PrintASN1PusSt03ParameterId(const char *paramName, const asn1SccPusSt03ParameterId *pData);
void PrintASN1PusSt03ParameterArray(const char *paramName, const asn1SccPusSt03ParameterArray *pData);
void PrintASN1PusTM_3_25_Data(const char *paramName, const asn1SccPusTM_3_25_Data *pData);
void PrintASN1PusSt05EventId(const char *paramName, const asn1SccPusSt05EventId *pData);
void PrintASN1PusSt05EventAuxData(const char *paramName, const asn1SccPusSt05EventAuxData *pData);
void PrintASN1PusSt05Event(const char *paramName, const asn1SccPusSt05Event *pData);
void PrintASN1PusTM_5_X_Data(const char *paramName, const asn1SccPusTM_5_X_Data *pData);
void PrintASN1PusSt08FunctionId(const char *paramName, const asn1SccPusSt08FunctionId *pData);
void PrintASN1PusTC_8_1_Data(const char *paramName, const asn1SccPusTC_8_1_Data *pData);
void PrintASN1PusSt09ExponentialRate(const char *paramName, const asn1SccPusSt09ExponentialRate *pData);
void PrintASN1PusTC_9_1_Data(const char *paramName, const asn1SccPusTC_9_1_Data *pData);
void PrintASN1PusTM_9_2_Data(const char *paramName, const asn1SccPusTM_9_2_Data *pData);
void PrintASN1PusSt12pmonId(const char *paramName, const asn1SccPusSt12pmonId *pData);
void PrintASN1PusTC_12_1_2_Data(const char *paramName, const asn1SccPusTC_12_1_2_Data *pData);
void PrintASN1PusSt18ObcpId(const char *paramName, const asn1SccPusSt18ObcpId *pData);
void PrintASN1PusSt18ObcpCode(const char *paramName, const asn1SccPusSt18ObcpCode *pData);
void PrintASN1PusSt18ObcpChecksum(const char *paramName, const asn1SccPusSt18ObcpChecksum *pData);
void PrintASN1PusSt18ObservabilityLevel(const char *paramName, const asn1SccPusSt18ObservabilityLevel *pData);
void PrintASN1PusTC_18_1_Data(const char *paramName, const asn1SccPusTC_18_1_Data *pData);
void PrintASN1PusTC_18_2_6_12_Data(const char *paramName, const asn1SccPusTC_18_2_6_12_Data *pData);
void PrintASN1PusTC_18_3_Data(const char *paramName, const asn1SccPusTC_18_3_Data *pData);
void PrintASN1PusTC_18_4_5_Data(const char *paramName, const asn1SccPusTC_18_4_5_Data *pData);
void PrintASN1PusTC_18_13_Data(const char *paramName, const asn1SccPusTC_18_13_Data *pData);
void PrintASN1PusTC_19_X_Data(const char *paramName, const asn1SccPusTC_19_X_Data *pData);
void PrintASN1PusSt20OnBoardParameterId(const char *paramName, const asn1SccPusSt20OnBoardParameterId *pData);
void PrintASN1PusSt20StoredParam(const char *paramName, const asn1SccPusSt20StoredParam *pData);
void PrintASN1PusTC_TM_20_X_Data(const char *paramName, const asn1SccPusTC_TM_20_X_Data *pData);
void PrintASN1PusSt23RepositoryPath(const char *paramName, const asn1SccPusSt23RepositoryPath *pData);
void PrintASN1PusSt23FileName(const char *paramName, const asn1SccPusSt23FileName *pData);
void PrintASN1PusSt23RepositoryDomain(const char *paramName, const asn1SccPusSt23RepositoryDomain *pData);
void PrintASN1PusTC_TM_23_1_4_Data(const char *paramName, const asn1SccPusTC_TM_23_1_4_Data *pData);
void PrintASN1PusTC_23_2_3_Data(const char *paramName, const asn1SccPusTC_23_2_3_Data *pData);
void PrintASN1PusTC_23_14_Data(const char *paramName, const asn1SccPusTC_23_14_Data *pData);
void PrintASN1PusTime(const char *paramName, const asn1SccPusTime *pData);
void PrintASN1PusUInt3(const char *paramName, const asn1SccPusUInt3 *pData);
void PrintASN1PusUInt4(const char *paramName, const asn1SccPusUInt4 *pData);
void PrintASN1PusUInt8(const char *paramName, const asn1SccPusUInt8 *pData);
void PrintASN1PusUInt11(const char *paramName, const asn1SccPusUInt11 *pData);
void PrintASN1PusUInt14(const char *paramName, const asn1SccPusUInt14 *pData);
void PrintASN1PusUInt16(const char *paramName, const asn1SccPusUInt16 *pData);
void PrintASN1PusUInt32(const char *paramName, const asn1SccPusUInt32 *pData);
void PrintASN1PusUInt64(const char *paramName, const asn1SccPusUInt64 *pData);
void PrintASN1PusInt32(const char *paramName, const asn1SccPusInt32 *pData);
void PrintASN1PusInt64(const char *paramName, const asn1SccPusInt64 *pData);
void PrintASN1PusDouble(const char *paramName, const asn1SccPusDouble *pData);
void PrintASN1PusMemAddr(const char *paramName, const asn1SccPusMemAddr *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);

#ifdef __cplusplus
}
#endif

#endif
