#ifndef __PRINTTYPESASASN1_H__
#define __PRINTTYPESASASN1_H__

#ifdef __cplusplus
extern "C" {
#endif

#include "dataview-uniq.h" // Generated by ASN1SCC

void PrintASN1PusTM_TC_Dummy_Data(const char *paramName, const asn1SccPusTM_TC_Dummy_Data *pData);
void PrintASN1PusTmHeader(const char *paramName, const asn1SccPusTmHeader *pData);
void PrintASN1PusTmSourceData(const char *paramName, const asn1SccPusTmSourceData *pData);
void PrintASN1PusTcHeader(const char *paramName, const asn1SccPusTcHeader *pData);
void PrintASN1PusTC_19_1_Data(const char *paramName, const asn1SccPusTC_19_1_Data *pData);
void PrintASN1PusTcScheduledActivity(const char *paramName, const asn1SccPusTcScheduledActivity *pData);
void PrintASN1PusTC_11_4_Data(const char *paramName, const asn1SccPusTC_11_4_Data *pData);
void PrintASN1PusTcApplicationData(const char *paramName, const asn1SccPusTcApplicationData *pData);
void PrintASN1PusTcApplicationDataReduced(const char *paramName, const asn1SccPusTcApplicationDataReduced *pData);
void PrintASN1PusTmHeaderData(const char *paramName, const asn1SccPusTmHeaderData *pData);
void PrintASN1PusPacketData(const char *paramName, const asn1SccPusPacketData *pData);
void PrintASN1PusPacketDataReduced(const char *paramName, const asn1SccPusPacketDataReduced *pData);
void PrintASN1PusPacket(const char *paramName, const asn1SccPusPacket *pData);
void PrintASN1PusPacketReduced(const char *paramName, const asn1SccPusPacketReduced *pData);
void PrintASN1PusPacketVersion(const char *paramName, const asn1SccPusPacketVersion *pData);
void PrintASN1PusPacketType(const char *paramName, const asn1SccPusPacketType *pData);
void PrintASN1PusSecondaryHeaderFlag(const char *paramName, const asn1SccPusSecondaryHeaderFlag *pData);
void PrintASN1PusApid(const char *paramName, const asn1SccPusApid *pData);
void PrintASN1PusSequenceFlags(const char *paramName, const asn1SccPusSequenceFlags *pData);
void PrintASN1PusSequenceCount(const char *paramName, const asn1SccPusSequenceCount *pData);
void PrintASN1PusPacketDataLength(const char *paramName, const asn1SccPusPacketDataLength *pData);
void PrintASN1PusVersionNumber(const char *paramName, const asn1SccPusVersionNumber *pData);
void PrintASN1PusTimeReferenceStatus(const char *paramName, const asn1SccPusTimeReferenceStatus *pData);
void PrintASN1PusMessageTypeCounter(const char *paramName, const asn1SccPusMessageTypeCounter *pData);
void PrintASN1PusAcknowledgementFlags(const char *paramName, const asn1SccPusAcknowledgementFlags *pData);
void PrintASN1PusChecksum(const char *paramName, const asn1SccPusChecksum *pData);
void PrintASN1PusStepId(const char *paramName, const asn1SccPusStepId *pData);
void PrintASN1PusConfigDummyType(const char *paramName, const asn1SccPusConfigDummyType *pData);
void PrintASN1PusServiceType(const char *paramName, const asn1SccPusServiceType *pData);
void PrintASN1PusSubserviceType(const char *paramName, const asn1SccPusSubserviceType *pData);
void PrintASN1PusSt01FailureCode(const char *paramName, const asn1SccPusSt01FailureCode *pData);
void PrintASN1PusSt01FailureInfo(const char *paramName, const asn1SccPusSt01FailureInfo *pData);
void PrintASN1PusSt01RequestId(const char *paramName, const asn1SccPusSt01RequestId *pData);
void PrintASN1PusSt01Failure(const char *paramName, const asn1SccPusSt01Failure *pData);
void PrintASN1PusTM_1_X_Data(const char *paramName, const asn1SccPusTM_1_X_Data *pData);
void PrintASN1PusSt03StoredParam(const char *paramName, const asn1SccPusSt03StoredParam *pData);
void PrintASN1PusSt03HousekeepingReportId(const char *paramName, const asn1SccPusSt03HousekeepingReportId *pData);
void PrintASN1PusSt03ParameterId(const char *paramName, const asn1SccPusSt03ParameterId *pData);
void PrintASN1PusSt03ParameterArray(const char *paramName, const asn1SccPusSt03ParameterArray *pData);
void PrintASN1PusTM_3_25_Data(const char *paramName, const asn1SccPusTM_3_25_Data *pData);
void PrintASN1PusSt05EventId(const char *paramName, const asn1SccPusSt05EventId *pData);
void PrintASN1PusSt05EventAuxData(const char *paramName, const asn1SccPusSt05EventAuxData *pData);
void PrintASN1PusSt05Event(const char *paramName, const asn1SccPusSt05Event *pData);
void PrintASN1PusTM_5_X_Data(const char *paramName, const asn1SccPusTM_5_X_Data *pData);
void PrintASN1PusSt08FunctionId(const char *paramName, const asn1SccPusSt08FunctionId *pData);
void PrintASN1PusTC_8_1_Data(const char *paramName, const asn1SccPusTC_8_1_Data *pData);
void PrintASN1PusSt09ExponentialRate(const char *paramName, const asn1SccPusSt09ExponentialRate *pData);
void PrintASN1PusTC_9_1_Data(const char *paramName, const asn1SccPusTC_9_1_Data *pData);
void PrintASN1PusTM_9_2_Data(const char *paramName, const asn1SccPusTM_9_2_Data *pData);
void PrintASN1PusSt12pmonId(const char *paramName, const asn1SccPusSt12pmonId *pData);
void PrintASN1PusTC_12_1_2_Data(const char *paramName, const asn1SccPusTC_12_1_2_Data *pData);
void PrintASN1PusSt18ObcpId(const char *paramName, const asn1SccPusSt18ObcpId *pData);
void PrintASN1PusSt18ObcpCode(const char *paramName, const asn1SccPusSt18ObcpCode *pData);
void PrintASN1PusSt18ObcpChecksum(const char *paramName, const asn1SccPusSt18ObcpChecksum *pData);
void PrintASN1PusSt18ObservabilityLevel(const char *paramName, const asn1SccPusSt18ObservabilityLevel *pData);
void PrintASN1PusTC_18_1_Data(const char *paramName, const asn1SccPusTC_18_1_Data *pData);
void PrintASN1PusTC_18_2_6_12_Data(const char *paramName, const asn1SccPusTC_18_2_6_12_Data *pData);
void PrintASN1PusTC_18_3_Data(const char *paramName, const asn1SccPusTC_18_3_Data *pData);
void PrintASN1PusTC_18_4_5_Data(const char *paramName, const asn1SccPusTC_18_4_5_Data *pData);
void PrintASN1PusTC_18_13_Data(const char *paramName, const asn1SccPusTC_18_13_Data *pData);
void PrintASN1PusTC_19_X_Data(const char *paramName, const asn1SccPusTC_19_X_Data *pData);
void PrintASN1PusSt20OnBoardParameterId(const char *paramName, const asn1SccPusSt20OnBoardParameterId *pData);
void PrintASN1PusSt20StoredParam(const char *paramName, const asn1SccPusSt20StoredParam *pData);
void PrintASN1PusTC_TM_20_X_Data(const char *paramName, const asn1SccPusTC_TM_20_X_Data *pData);
void PrintASN1PusTM_200_2_Data(const char *paramName, const asn1SccPusTM_200_2_Data *pData);
void PrintASN1PusTC_200_3_Data(const char *paramName, const asn1SccPusTC_200_3_Data *pData);
void PrintASN1PusTM_200_4_Data(const char *paramName, const asn1SccPusTM_200_4_Data *pData);
void PrintASN1PusTC_200_5_Data(const char *paramName, const asn1SccPusTC_200_5_Data *pData);
void PrintASN1PusTM_200_6_Data(const char *paramName, const asn1SccPusTM_200_6_Data *pData);
void PrintASN1PusTM_200_8_Data(const char *paramName, const asn1SccPusTM_200_8_Data *pData);
void PrintASN1PusTC_200_9_Data(const char *paramName, const asn1SccPusTC_200_9_Data *pData);
void PrintASN1PusTM_200_10_Data(const char *paramName, const asn1SccPusTM_200_10_Data *pData);
void PrintASN1PusTC_200_11_Data(const char *paramName, const asn1SccPusTC_200_11_Data *pData);
void PrintASN1PusTM_200_12_Data(const char *paramName, const asn1SccPusTM_200_12_Data *pData);
void PrintASN1PusTC_200_13_Data(const char *paramName, const asn1SccPusTC_200_13_Data *pData);
void PrintASN1PusTM_200_14_Data(const char *paramName, const asn1SccPusTM_200_14_Data *pData);
void PrintASN1IntegerIntervalDomain(const char *paramName, const asn1SccIntegerIntervalDomain *pData);
void PrintASN1FloatIntervalDomain(const char *paramName, const asn1SccFloatIntervalDomain *pData);
void PrintASN1EnumDomain(const char *paramName, const asn1SccEnumDomain *pData);
void PrintASN1HotdockcmdPred(const char *paramName, const asn1SccHotdockcmdPred *pData);
void PrintASN1HotdockstatusPred(const char *paramName, const asn1SccHotdockstatusPred *pData);
void PrintASN1WmcmdPred(const char *paramName, const asn1SccWmcmdPred *pData);
void PrintASN1BasecmdPred(const char *paramName, const asn1SccBasecmdPred *pData);
void PrintASN1EfcmdPred(const char *paramName, const asn1SccEfcmdPred *pData);
void PrintASN1PlannerPred(const char *paramName, const asn1SccPlannerPred *pData);
void PrintASN1MissionPred(const char *paramName, const asn1SccMissionPred *pData);
void PrintASN1AutonomyPred(const char *paramName, const asn1SccAutonomyPred *pData);
void PrintASN1Boold(const char *paramName, const asn1SccBoold *pData);
void PrintASN1Intd(const char *paramName, const asn1SccIntd *pData);
void PrintASN1Floatd(const char *paramName, const asn1SccFloatd *pData);
void PrintASN1Stringd(const char *paramName, const asn1SccStringd *pData);
void PrintASN1Int2d(const char *paramName, const asn1SccInt2d *pData);
void PrintASN1Slotid(const char *paramName, const asn1SccSlotid *pData);
void PrintASN1Position3D(const char *paramName, const asn1SccPosition3D *pData);
void PrintASN1Quaterniond(const char *paramName, const asn1SccQuaterniond *pData);
void PrintASN1Hotdockcmdstatus(const char *paramName, const asn1SccHotdockcmdstatus *pData);
void PrintASN1Hotdockstatusstatus(const char *paramName, const asn1SccHotdockstatusstatus *pData);
void PrintASN1Wmcmdstatus(const char *paramName, const asn1SccWmcmdstatus *pData);
void PrintASN1Basecmdstatus(const char *paramName, const asn1SccBasecmdstatus *pData);
void PrintASN1Efcmdstatus(const char *paramName, const asn1SccEfcmdstatus *pData);
void PrintASN1Plannerstatus(const char *paramName, const asn1SccPlannerstatus *pData);
void PrintASN1Missionstatus(const char *paramName, const asn1SccMissionstatus *pData);
void PrintASN1Autonomystatus(const char *paramName, const asn1SccAutonomystatus *pData);
void PrintASN1Pus_220_StateId(const char *paramName, const asn1SccPus_220_StateId *pData);
void PrintASN1PusTC_220_1_Data(const char *paramName, const asn1SccPusTC_220_1_Data *pData);
void PrintASN1PusTM_220_3_Data(const char *paramName, const asn1SccPusTM_220_3_Data *pData);
void PrintASN1Pus_220_ActiveIds(const char *paramName, const asn1SccPus_220_ActiveIds *pData);
void PrintASN1PusSt23RepositoryPath(const char *paramName, const asn1SccPusSt23RepositoryPath *pData);
void PrintASN1PusSt23FileName(const char *paramName, const asn1SccPusSt23FileName *pData);
void PrintASN1PusSt23RepositoryDomain(const char *paramName, const asn1SccPusSt23RepositoryDomain *pData);
void PrintASN1PusTC_TM_23_1_4_Data(const char *paramName, const asn1SccPusTC_TM_23_1_4_Data *pData);
void PrintASN1PusTC_23_2_3_Data(const char *paramName, const asn1SccPusTC_23_2_3_Data *pData);
void PrintASN1PusTC_23_14_Data(const char *paramName, const asn1SccPusTC_23_14_Data *pData);
void PrintASN1T_Double(const char *paramName, const asn1SccT_Double *pData);
void PrintASN1T_Float(const char *paramName, const asn1SccT_Float *pData);
void PrintASN1T_Int16(const char *paramName, const asn1SccT_Int16 *pData);
void PrintASN1T_UInt16(const char *paramName, const asn1SccT_UInt16 *pData);
void PrintASN1T_UInt64(const char *paramName, const asn1SccT_UInt64 *pData);
void PrintASN1T_Int64(const char *paramName, const asn1SccT_Int64 *pData);
void PrintASN1T_String(const char *paramName, const asn1SccT_String *pData);
void PrintASN1T_Time(const char *paramName, const asn1SccT_Time *pData);
void PrintASN1PusTime(const char *paramName, const asn1SccPusTime *pData);
void PrintASN1PusUInt3(const char *paramName, const asn1SccPusUInt3 *pData);
void PrintASN1PusUInt4(const char *paramName, const asn1SccPusUInt4 *pData);
void PrintASN1PusUInt8(const char *paramName, const asn1SccPusUInt8 *pData);
void PrintASN1PusUInt11(const char *paramName, const asn1SccPusUInt11 *pData);
void PrintASN1PusUInt14(const char *paramName, const asn1SccPusUInt14 *pData);
void PrintASN1PusUInt16(const char *paramName, const asn1SccPusUInt16 *pData);
void PrintASN1PusUInt32(const char *paramName, const asn1SccPusUInt32 *pData);
void PrintASN1PusUInt64(const char *paramName, const asn1SccPusUInt64 *pData);
void PrintASN1PusInt32(const char *paramName, const asn1SccPusInt32 *pData);
void PrintASN1PusInt64(const char *paramName, const asn1SccPusInt64 *pData);
void PrintASN1PusDouble(const char *paramName, const asn1SccPusDouble *pData);
void PrintASN1PusMemAddr(const char *paramName, const asn1SccPusMemAddr *pData);
void PrintASN1T_Int32(const char *paramName, const asn1SccT_Int32 *pData);
void PrintASN1T_UInt32(const char *paramName, const asn1SccT_UInt32 *pData);
void PrintASN1T_Int8(const char *paramName, const asn1SccT_Int8 *pData);
void PrintASN1T_UInt8(const char *paramName, const asn1SccT_UInt8 *pData);
void PrintASN1T_Boolean(const char *paramName, const asn1SccT_Boolean *pData);

#ifdef __cplusplus
}
#endif

#endif
