/* Body file for function DummyPrivateService
 * Generated by TASTE on 2021-06-10 13:10:09
 * You can edit this file, it will not be overwritten
 * Provided interfaces : forwardTc
 * Required interfaces : 
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 134437 32417 177819 47196
 * Timers              : 
 */
/* There are no required interfaces for this function... */

