
/* Header file for function DummyPrivateService in C language
 * Generated by TASTE on 2021-07-08 16:59:21
 * Context Parameters present : NO
 * Provided interfaces : forwardTc
 * Required interfaces : 
 * User-defined properties for this function:
  *  |_ Taste::Active_Interfaces = any
  *  |_ Taste::coordinates = 134437 32417 177819 47196
 * DO NOT EDIT THIS FILE, IT WILL BE OVERWRITTEN DURING THE BUILD
 */

#pragma once

#include "dataview-uniq.h"

#ifdef __cplusplus
extern "C" {
#endif

#ifdef __unix__
   #include <stdlib.h>
   #include <stdio.h>
#endif

void dummyprivateservice_startup(void);

/* Provided interfaces */
void dummyprivateservice_PI_forwardTc( const asn1SccPusPacket * );

/* Required interfaces */



#ifdef __cplusplus
}
#endif
