/* Body file for function OnBoardSW
 * Generated by TASTE on 2020-09-29 16:52:54
 * Provided interfaces : trigger
 * Required interfaces : getOnBoardParam, getParamValue, pushNewEvent, setOnBoardParam, setParamValue
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 199364 64408 238261 91808
 * Timers              : 
 */
#include "onboardsw_vm_if.h"
#ifdef __unix__
   #include <stdio.h>
#endif




extern void init_pusservices(void);
extern unsigned pusservices_initialized;
extern void init_pusservices(void);
extern unsigned pusservices_initialized;
extern void init_pusservices(void);
extern unsigned pusservices_initialized;
extern void init_pusservices(void);
extern unsigned pusservices_initialized;
extern void init_pusservices(void);
extern unsigned pusservices_initialized;
unsigned onboardsw_initialized = 0;
void init_onboardsw(void)
{
   if (!onboardsw_initialized) {
      onboardsw_initialized = 1;
      // Call user code startup function
      onboardsw_startup();
      // Iterate over all synchronous RIs, and call their parent's
      // init function. Multiple calls are prevented by the "init" guard.
      if (0 == pusservices_initialized) {
          init_pusservices();
      }
      if (0 == pusservices_initialized) {
          init_pusservices();
      }
      if (0 == pusservices_initialized) {
          init_pusservices();
      }
      if (0 == pusservices_initialized) {
          init_pusservices();
      }
      if (0 == pusservices_initialized) {
          init_pusservices();
      }
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function OnBoardSW");
#endif
      onboardsw_initialized = 2;
   }
}
void onboardsw_trigger()
{
   //  Directly call user code, no parameters to pass
   extern void onboardsw_PI_trigger(void);
   onboardsw_PI_trigger();
   // puts ("onboardsw_trigger called");
}

