/* Body file for function OnBoardSW
 * Generated by TASTE on 2020-05-22 09:49:02
 * You can edit this file, it will not be overwritten
 * Provided interfaces : trigger
 * Required interfaces : getOnBoardParam, getParamValue, pushNewEvent, setOnBoardParam, setParamValue
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 199364 64408 238261 91808
 * Timers              : 
 */
#include <stdlib.h>
#ifdef __unix__
   #include <stdio.h>
   #include "PrintTypesAsASN1.h"
   #include "timeInMS.h"
#endif
#include "C_ASN1_Types.h"
#include "dataview-uniq.h"

// reference to flag preventing calls to RIs during the startup transition
extern unsigned onboardsw_initialized;
// in case that happens, use system's abort function to crash the application
extern void abort (void);

void onboardsw_RI_getOnBoardParam
      (const asn1SccPusSt20OnBoardParameterId *IN_paramid,
       asn1SccPusSt20StoredParam *OUT_paramvalue,
       asn1SccPusSt01FailureCode *OUT_isavailable)

{
   // Check that we are not in the startup transition
   if (2 != onboardsw_initialized) {
      #ifdef __unix__
         puts("A call to onboardsw_RI_getOnBoardParam was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1PusSt20OnBoardParameterId ("INNERDATA: getonboardparam::PusSt20OnBoardParameterId::paramid", IN_paramid);
         puts(""); // add newline
         // Log message to PusServices (corresponding PI: getOnBoardParam)
         printf ("INNER: onboardsw,pusservices,getonboardparam,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter paramId
   static asn1SccPusSt20OnBoardParameterId IN_buf_paramid;
   int size_IN_buf_paramid =
      Encode_NATIVE_PusSt20OnBoardParameterId
        ((void *)&IN_buf_paramid,
          sizeof(asn1SccPusSt20OnBoardParameterId),
          (asn1SccPusSt20OnBoardParameterId *)IN_paramid);
   if (-1 == size_IN_buf_paramid) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_getOnBoardParam, parameter paramId");
      #endif
        /* Crash the application due to message loss */
        abort();
   }

   // Buffer for decoding parameter paramValue
   static asn1SccPusSt20StoredParam OUT_buf_paramvalue;
   size_t      size_OUT_buf_paramvalue = 0;
   // Buffer for decoding parameter isAvailable
   static asn1SccPusSt01FailureCode OUT_buf_isavailable;
   size_t      size_OUT_buf_isavailable = 0;

   // Call Middleware interface
   extern void vm_onboardsw_getonboardparam
     (void *, size_t,
      void *, size_t *,
      void *, size_t *);

   vm_onboardsw_getonboardparam
     ((void *)&IN_buf_paramid, (size_t)size_IN_buf_paramid,
      (void *)&OUT_buf_paramvalue, &size_OUT_buf_paramvalue,
      (void *)&OUT_buf_isavailable, &size_OUT_buf_isavailable);


   // Decode parameter paramValue
   if (0 != Decode_NATIVE_PusSt20StoredParam
              (OUT_paramvalue, (void *)&OUT_buf_paramvalue, size_OUT_buf_paramvalue)) {
#ifdef __unix__
      puts ("[ERROR] ASN.1 Decoding failed in onboardsw_RI_getOnBoardParam, parameter paramValue");
#endif
      return;
  }
   // Decode parameter isAvailable
   if (0 != Decode_NATIVE_PusSt01FailureCode
              (OUT_isavailable, (void *)&OUT_buf_isavailable, size_OUT_buf_isavailable)) {
#ifdef __unix__
      puts ("[ERROR] ASN.1 Decoding failed in onboardsw_RI_getOnBoardParam, parameter isAvailable");
#endif
      return;
  }
}void onboardsw_RI_getParamValue
      (const asn1SccPusSt03ParameterId *IN_paramid,
       asn1SccPusSt03StoredParam *OUT_paramvalue,
       asn1SccPusSt01FailureCode *OUT_isavailable)

{
   // Check that we are not in the startup transition
   if (2 != onboardsw_initialized) {
      #ifdef __unix__
         puts("A call to onboardsw_RI_getParamValue was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1PusSt03ParameterId ("INNERDATA: getparamvalue::PusSt03ParameterId::paramid", IN_paramid);
         puts(""); // add newline
         // Log message to PusServices (corresponding PI: getParamValue)
         printf ("INNER: onboardsw,pusservices,getparamvalue,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter paramId
   static asn1SccPusSt03ParameterId IN_buf_paramid;
   int size_IN_buf_paramid =
      Encode_NATIVE_PusSt03ParameterId
        ((void *)&IN_buf_paramid,
          sizeof(asn1SccPusSt03ParameterId),
          (asn1SccPusSt03ParameterId *)IN_paramid);
   if (-1 == size_IN_buf_paramid) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_getParamValue, parameter paramId");
      #endif
        /* Crash the application due to message loss */
        abort();
   }

   // Buffer for decoding parameter paramValue
   static asn1SccPusSt03StoredParam OUT_buf_paramvalue;
   size_t      size_OUT_buf_paramvalue = 0;
   // Buffer for decoding parameter isAvailable
   static asn1SccPusSt01FailureCode OUT_buf_isavailable;
   size_t      size_OUT_buf_isavailable = 0;

   // Call Middleware interface
   extern void vm_onboardsw_getparamvalue
     (void *, size_t,
      void *, size_t *,
      void *, size_t *);

   vm_onboardsw_getparamvalue
     ((void *)&IN_buf_paramid, (size_t)size_IN_buf_paramid,
      (void *)&OUT_buf_paramvalue, &size_OUT_buf_paramvalue,
      (void *)&OUT_buf_isavailable, &size_OUT_buf_isavailable);


   // Decode parameter paramValue
   if (0 != Decode_NATIVE_PusSt03StoredParam
              (OUT_paramvalue, (void *)&OUT_buf_paramvalue, size_OUT_buf_paramvalue)) {
#ifdef __unix__
      puts ("[ERROR] ASN.1 Decoding failed in onboardsw_RI_getParamValue, parameter paramValue");
#endif
      return;
  }
   // Decode parameter isAvailable
   if (0 != Decode_NATIVE_PusSt01FailureCode
              (OUT_isavailable, (void *)&OUT_buf_isavailable, size_OUT_buf_isavailable)) {
#ifdef __unix__
      puts ("[ERROR] ASN.1 Decoding failed in onboardsw_RI_getParamValue, parameter isAvailable");
#endif
      return;
  }
}void onboardsw_RI_pushNewEvent
      (const asn1SccPusSt05Event *IN_eveninfo)

{
   // Check that we are not in the startup transition
   if (2 != onboardsw_initialized) {
      #ifdef __unix__
         puts("A call to onboardsw_RI_pushNewEvent was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1PusSt05Event ("INNERDATA: pushnewevent::PusSt05Event::eveninfo", IN_eveninfo);
         puts(""); // add newline
         // Log message to PusServices (corresponding PI: pushNewEvent)
         printf ("INNER: onboardsw,pusservices,pushnewevent,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter evenInfo
   static asn1SccPusSt05Event IN_buf_eveninfo;
   int size_IN_buf_eveninfo =
      Encode_NATIVE_PusSt05Event
        ((void *)&IN_buf_eveninfo,
          sizeof(asn1SccPusSt05Event),
          (asn1SccPusSt05Event *)IN_eveninfo);
   if (-1 == size_IN_buf_eveninfo) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_pushNewEvent, parameter evenInfo");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_onboardsw_pushnewevent
     (void *, size_t);

   vm_onboardsw_pushnewevent
     ((void *)&IN_buf_eveninfo, (size_t)size_IN_buf_eveninfo);


}void onboardsw_RI_setOnBoardParam
      (const asn1SccPusSt20OnBoardParameterId *IN_paramid,
       const asn1SccPusSt20StoredParam *IN_paramvalue)

{
   // Check that we are not in the startup transition
   if (2 != onboardsw_initialized) {
      #ifdef __unix__
         puts("A call to onboardsw_RI_setOnBoardParam was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1PusSt20OnBoardParameterId ("INNERDATA: setonboardparam::PusSt20OnBoardParameterId::paramid", IN_paramid);
         PrintASN1PusSt20StoredParam ("INNERDATA: setonboardparam::PusSt20StoredParam::paramvalue", IN_paramvalue);
         puts(""); // add newline
         // Log message to PusServices (corresponding PI: setOnBoardParam)
         printf ("INNER: onboardsw,pusservices,setonboardparam,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter paramId
   static asn1SccPusSt20OnBoardParameterId IN_buf_paramid;
   int size_IN_buf_paramid =
      Encode_NATIVE_PusSt20OnBoardParameterId
        ((void *)&IN_buf_paramid,
          sizeof(asn1SccPusSt20OnBoardParameterId),
          (asn1SccPusSt20OnBoardParameterId *)IN_paramid);
   if (-1 == size_IN_buf_paramid) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_setOnBoardParam, parameter paramId");
      #endif
        /* Crash the application due to message loss */
        abort();
   }
   // Encode parameter paramValue
   static asn1SccPusSt20StoredParam IN_buf_paramvalue;
   int size_IN_buf_paramvalue =
      Encode_NATIVE_PusSt20StoredParam
        ((void *)&IN_buf_paramvalue,
          sizeof(asn1SccPusSt20StoredParam),
          (asn1SccPusSt20StoredParam *)IN_paramvalue);
   if (-1 == size_IN_buf_paramvalue) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_setOnBoardParam, parameter paramValue");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_onboardsw_setonboardparam
     (void *, size_t,
      void *, size_t);

   vm_onboardsw_setonboardparam
     ((void *)&IN_buf_paramid, (size_t)size_IN_buf_paramid,
      (void *)&IN_buf_paramvalue, (size_t)size_IN_buf_paramvalue);


}void onboardsw_RI_setParamValue
      (const asn1SccPusSt03ParameterId *IN_paramid,
       const asn1SccPusSt03StoredParam *IN_paramvalue)

{
   // Check that we are not in the startup transition
   if (2 != onboardsw_initialized) {
      #ifdef __unix__
         puts("A call to onboardsw_RI_setParamValue was made during system startup.");
         puts("This is not allowed because the system is not yet fully initialized. Please fix your code/models");
      #endif
      // crash the application
      abort();
   }

   #ifdef __unix__
      // Log MSC data on Linux when environment variable is set
      static int innerMsc = -1;
      if (-1 == innerMsc)
         innerMsc = (NULL != getenv("TASTE_INNER_MSC"))?1:0;
      if (1 == innerMsc) {
         long long msc_time = getTimeInMilliseconds();
         PrintASN1PusSt03ParameterId ("INNERDATA: setparamvalue::PusSt03ParameterId::paramid", IN_paramid);
         PrintASN1PusSt03StoredParam ("INNERDATA: setparamvalue::PusSt03StoredParam::paramvalue", IN_paramvalue);
         puts(""); // add newline
         // Log message to PusServices (corresponding PI: setParamValue)
         printf ("INNER: onboardsw,pusservices,setparamvalue,%lld\n", msc_time);
         fflush(stdout);
      }
   #endif
   // Encode parameter paramId
   static asn1SccPusSt03ParameterId IN_buf_paramid;
   int size_IN_buf_paramid =
      Encode_NATIVE_PusSt03ParameterId
        ((void *)&IN_buf_paramid,
          sizeof(asn1SccPusSt03ParameterId),
          (asn1SccPusSt03ParameterId *)IN_paramid);
   if (-1 == size_IN_buf_paramid) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_setParamValue, parameter paramId");
      #endif
        /* Crash the application due to message loss */
        abort();
   }
   // Encode parameter paramValue
   static asn1SccPusSt03StoredParam IN_buf_paramvalue;
   int size_IN_buf_paramvalue =
      Encode_NATIVE_PusSt03StoredParam
        ((void *)&IN_buf_paramvalue,
          sizeof(asn1SccPusSt03StoredParam),
          (asn1SccPusSt03StoredParam *)IN_paramvalue);
   if (-1 == size_IN_buf_paramvalue) {
      #ifdef __unix__
         puts ("[ERROR] ASN.1 Encoding failed in onboardsw_RI_setParamValue, parameter paramValue");
      #endif
        /* Crash the application due to message loss */
        abort();
   }


   // Call Middleware interface
   extern void vm_onboardsw_setparamvalue
     (void *, size_t,
      void *, size_t);

   vm_onboardsw_setparamvalue
     ((void *)&IN_buf_paramid, (size_t)size_IN_buf_paramid,
      (void *)&IN_buf_paramvalue, (size_t)size_IN_buf_paramvalue);


}

