/* Body file for function Ground
 * Generated by TASTE on 2021-07-05 17:17:23
 * Provided interfaces : newTm, triggerTmGUI
 * Required interfaces : newTc
 * User-defined properties for this function:
 *   |_ Taste::Active_Interfaces = any
 *   |_ Taste::coordinates = 79368 65667 105509 89131
 * Timers              : 
 */
#include "ground_vm_if.h"
#include "C_ASN1_Types.h"
#ifdef __unix__
   #include <stdio.h>
#endif




unsigned ground_initialized = 0;
void init_ground(void)
{
   if (!ground_initialized) {
      ground_initialized = 1;
      // Call user code startup function
      ground_startup();
#ifdef __unix__
      puts ("[TASTE] Initialization completed for function Ground");
#endif
      ground_initialized = 2;
   }
}
void ground_newTm
      (const char *IN_tmpacket, size_t IN_tmpacket_len)

{

   static asn1SccPusPacket IN_TMPACKET;
#ifdef __unix__
   asn1SccPusPacket_Initialize(&IN_TMPACKET);
#endif
   if (0 != Decode_NATIVE_PusPacket (&IN_TMPACKET, (void *)IN_tmpacket, IN_tmpacket_len)) {
      #ifdef __unix__
         puts("Error decoding PusPacket in function Ground_newTm");
      #endif
      return;
   }

   //  Declare user code function as external (it may not have a .h if it is in Ada)
   extern void ground_PI_newTm
      (const asn1SccPusPacket *);




   // Call user code
   ground_PI_newTm (&IN_TMPACKET);

}
void ground_triggerTmGUI()
{
   //  Directly call user code, no parameters to pass
   extern void ground_PI_triggerTmGUI(void);
   ground_PI_triggerTmGUI();
   // puts ("ground_triggertmgui called");
}

